/* GENERATED by scripts/build_frontend_data.py -- do not edit by hand.
 * Source: the agent registry's own catalogue (101 AgentCards).
 * Regenerate after any catalogue change; a stale copy here is the
 * failure this generator exists to prevent. */
window.agentCatalogData = {
 "AGT-19": {
  "id": "AGT-19",
  "name": "Strategic Planning Advisor",
  "tierKey": "L0",
  "pattern": "L0_STRATEGIC",
  "apqc": "APQC 1.2.1",
  "department": "Commercial/Finance/Strategy",
  "persona": "CEO / CFO / Executive Committee",
  "process": "CEO / CFO / Executive Committee",
  "authority": "L1 ADVISORY",
  "valueClass": "Class A (Cash)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "max NPV = sum [(P-s)Qr - cQc - mQm - F]/(1+d)^t",
  "mechanism": "Level 0 Executive Advisor governing multi-horizon LOM NPV optimization, dynamic cut-off grade scheduling, commodity price stochastic simulations, and Second-Order Stochastic Dominance (SSD) CapEx ranking.",
  "provenance": [
   {
    "name": "geological_block_models",
    "type": "BQ"
   },
   {
    "name": "financial_ledger",
    "type": "BQ"
   },
   {
    "name": "mine_production_schedule",
    "type": "BQ"
   }
  ],
  "tools": [
   "kenneth_lane_optimizer",
   "ornstein_uhlenbeck_simulator",
   "ssd_capex_evaluator",
   "risk_assessor"
  ],
  "model": "gemini-3.7-flash"
 },
 "S01-1-LITHOLOGY": {
  "id": "S01-1-LITHOLOGY",
  "name": "Drill Lithology Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.1.2",
  "department": "Exploration/Geology",
  "persona": "Exploration Geologist",
  "process": "Exploration Geologist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S01-COORDINATOR",
  "governingEquation": "RQD = (sum(pieces >= 10cm) / total_length) * 100",
  "mechanism": "Processes diamond core logging, RQD measurements, and alteration classifications.",
  "provenance": [
   {
    "name": "drill_holes",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S01-2-GEOSTAT": {
  "id": "S01-2-GEOSTAT",
  "name": "Assay Geostatistics Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.1.2",
  "department": "Exploration/Geology",
  "persona": "Geostatistician",
  "process": "Geostatistician",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S01-COORDINATOR",
  "governingEquation": "Z_hat(x0) = sum(lambda_i * Z(x_i))",
  "mechanism": "Calculates experimental semivariograms, nugget effect, spherical models, and Ordinary Kriging estimations.",
  "provenance": [
   {
    "name": "assay_logs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S01-3-STRUCTURAL": {
  "id": "S01-3-STRUCTURAL",
  "name": "Structural Fault Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.1.3",
  "department": "Exploration/Geology",
  "persona": "Structural Geologist",
  "process": "Structural Geologist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S01-COORDINATOR",
  "governingEquation": "n = (sin(theta)*cos(phi), sin(theta)*sin(phi), cos(theta))",
  "mechanism": "Maps fault kinematics, stereonet orientation dip/strike tensors, and geotechnical domain boundaries.",
  "provenance": [
   {
    "name": "geological_block_models",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S01-COORDINATOR": {
  "id": "S01-COORDINATOR",
  "name": "Geology Swarm Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 3.1.1",
  "department": "Exploration/Geology",
  "persona": "Elena (Chief Mine Geologist)",
  "process": "Elena (Chief Mine Geologist)",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "gamma(h) = 1/(2N(h)) * sum [Z(x_i) - Z(x_i+h)]^2",
  "mechanism": "Arbiter for exploration drillhole assays, 3D lithological domains, and JORC 2012 resource classification.",
  "provenance": [
   {
    "name": "drill_holes",
    "type": "BQ"
   },
   {
    "name": "assay_logs",
    "type": "BQ"
   },
   {
    "name": "geological_block_models",
    "type": "BQ"
   }
  ],
  "tools": [
   "variogram_modeler",
   "rqd_calculator",
   "kriging_solver"
  ],
  "model": "gemini-3.7-flash"
 },
 "S01-R-CRITIC": {
  "id": "S01-R-CRITIC",
  "name": "Resource Critic (JORC / QAQC Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 3.1.1",
  "department": "Exploration/Geology",
  "persona": "Competent Person (CP / QP)",
  "process": "Competent Person (CP / QP)",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S01-COORDINATOR",
  "governingEquation": "JORC Resource Confidence Index & Blank Contamination Variance",
  "mechanism": "Adversarial auditor checking QA/QC blanks, CRM standards, core duplicates, and JORC Competent Person boundaries.",
  "provenance": [
   {
    "name": "assay_logs",
    "type": "BQ"
   },
   {
    "name": "qaqc_standards",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S02-1-GEOTECH": {
  "id": "S02-1-GEOTECH",
  "name": "Pit Wall Geotechnical Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.2.2",
  "department": "Mine Planning/Operations",
  "persona": "Geotechnical Engineer",
  "process": "Geotechnical Engineer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S02-COORDINATOR",
  "governingEquation": "FoS = [c' + (sigma_n - u)*tan(phi')] / tau_m",
  "mechanism": "Calculates Factor of Safety (FoS), pore pressure distribution, and wedge/planar slope stability.",
  "provenance": [
   {
    "name": "geotech_sensors",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S02-2-SCHEDULE": {
  "id": "S02-2-SCHEDULE",
  "name": "Phase Scheduling Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.2.3",
  "department": "Mine Planning/Operations",
  "persona": "Long-Term Planning Engineer",
  "process": "Long-Term Planning Engineer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S02-COORDINATOR",
  "governingEquation": "V_t(S) = max_a [R(S, a) + gamma * V_{t+1}(S')]",
  "mechanism": "Generates medium-term and short-term extraction sequences satisfying mill feed blending constraints.",
  "provenance": [
   {
    "name": "mine_production_schedule",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S02-3-DUMP": {
  "id": "S02-3-DUMP",
  "name": "Waste Dump Stability Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.2.4",
  "department": "Mine Planning/Operations",
  "persona": "Civil Mine Engineer",
  "process": "Civil Mine Engineer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S02-COORDINATOR",
  "governingEquation": "Bishop Method: FoS = sum([c'b + (W - ub)tan(phi')]*m_alpha) / sum(W*sin(alpha))",
  "mechanism": "Models waste rock placement angle of repose, lift compaction, and runout slip circle containment.",
  "provenance": [
   {
    "name": "pit_designs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S02-COORDINATOR": {
  "id": "S02-COORDINATOR",
  "name": "Mine Planning Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 3.2.1",
  "department": "Mine Planning/Operations",
  "persona": "Planning Superintendent",
  "process": "Planning Superintendent",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Lerchs-Grossmann Graph Max-Flow: max sum(w_i * v_i)",
  "mechanism": "Orchestrates pit pushbacks, Lerchs-Grossmann ultimate pit limit optimization, and dynamic phase scheduling.",
  "provenance": [
   {
    "name": "mine_production_schedule",
    "type": "BQ"
   },
   {
    "name": "pit_designs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S02-R-CRITIC": {
  "id": "S02-R-CRITIC",
  "name": "Plan Compliance Critic (Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 3.2.1",
  "department": "Mine Planning/Operations",
  "persona": "Senior Mine Surveyor",
  "process": "Senior Mine Surveyor",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S02-COORDINATOR",
  "governingEquation": "F1 = Mined_Volume / Planned_Volume, F2 = Milled_Metal / Mined_Metal",
  "mechanism": "Evaluates spatial reconciliation (F1 mined vs planned, F2 milled vs mined) and compliance variance.",
  "provenance": [
   {
    "name": "survey_scans",
    "type": "BQ"
   },
   {
    "name": "mine_production_schedule",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S03-1-GEOMETRY": {
  "id": "S03-1-GEOMETRY",
  "name": "Blast Geometry Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.3.2",
  "department": "Mine Planning/Operations",
  "persona": "D&B Engineer",
  "process": "D&B Engineer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S03-COORDINATOR",
  "governingEquation": "B = K_b * d_h * sqrt(rho_e / rho_r)",
  "mechanism": "Calculates optimum burden, spacing, sub-drilling, and stemming lengths based on rock density.",
  "provenance": [
   {
    "name": "blast_designs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S03-2-EXPLOSIVE": {
  "id": "S03-2-EXPLOSIVE",
  "name": "Explosives Energy Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.3.3",
  "department": "Mine Planning/Operations",
  "persona": "Shotfirer Technical Lead",
  "process": "Shotfirer Technical Lead",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S03-COORDINATOR",
  "governingEquation": "q = M_exp / V_rock (kg/m3)",
  "mechanism": "Calculates bulk emulsion vs ANFO energy partitioning, VOD velocity of detonation, and powder factor.",
  "provenance": [
   {
    "name": "explosives_inventory",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S03-3-VIBRATION": {
  "id": "S03-3-VIBRATION",
  "name": "Blast Vibration Sentinel",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.3.4",
  "department": "Mine Planning/Operations",
  "persona": "Environmental Blast Engineer",
  "process": "Environmental Blast Engineer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S03-COORDINATOR",
  "governingEquation": "PPV = K * (D / sqrt(W))^(-beta)",
  "mechanism": "Predicts Peak Particle Velocity (PPV) attenuation curves to protect pit walls and infrastructure.",
  "provenance": [
   {
    "name": "vibration_monitors",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S03-COORDINATOR": {
  "id": "S03-COORDINATOR",
  "name": "Drill & Blast Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 3.3.1",
  "department": "Mine Planning/Operations",
  "persona": "Drill & Blast Superintendent",
  "process": "Drill & Blast Superintendent",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Kuz-Ram: x50 = A * Q^(1/6) * (115/E)^0.63 * (V0/Q)^0.8",
  "mechanism": "Optimizes blast burden, spacing, powder factor, and Kuz-Ram fragmentation distribution.",
  "provenance": [
   {
    "name": "blast_designs",
    "type": "BQ"
   },
   {
    "name": "explosives_inventory",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S03-R-CRITIC": {
  "id": "S03-R-CRITIC",
  "name": "Blast Safety Critic (Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 3.3.1",
  "department": "Mine Planning/Operations",
  "persona": "Statutory Shotfirer",
  "process": "Statutory Shotfirer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S03-COORDINATOR",
  "governingEquation": "Statutory Exclusion Zone Radius & Misfire Detection Gate",
  "mechanism": "Statutory blast exclusion zone verification, misfire detection, and flyrock risk perimeter gate.",
  "provenance": [
   {
    "name": "blast_designs",
    "type": "BQ"
   },
   {
    "name": "safety_permits",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S04-1-SHOVEL": {
  "id": "S04-1-SHOVEL",
  "name": "Shovel Match Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.4.2",
  "department": "Fleet/Haulage",
  "persona": "Dispatch Controller",
  "process": "Dispatch Controller",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S04-COORDINATOR",
  "governingEquation": "Passes = Truck_Capacity / (Shovel_Bucket_Payload * Fill_Factor)",
  "mechanism": "Calculates pass match factor, bucket fill factor, and spotting delay optimization.",
  "provenance": [
   {
    "name": "fleet_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S04-2-ROUTE": {
  "id": "S04-2-ROUTE",
  "name": "Haul Route Optimizer",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.4.3",
  "department": "Fleet/Haulage",
  "persona": "Fleet Planner",
  "process": "Fleet Planner",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S04-COORDINATOR",
  "governingEquation": "min sum(c_ij * x_ij) s.t. network flow continuity",
  "mechanism": "Solves real-time shortest path and congestion re-routing for Caterpillar/Komatsu haul trucks.",
  "provenance": [
   {
    "name": "dispatch_routes",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S04-3-PAYLOAD": {
  "id": "S04-3-PAYLOAD",
  "name": "Truck Payload Sentinel",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.4.4",
  "department": "Fleet/Haulage",
  "persona": "Fleet Controller",
  "process": "Fleet Controller",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S04-COORDINATOR",
  "governingEquation": "P(X > 1.20 * Target_Payload) = 0",
  "mechanism": "Enforces OEM 10/10/20 payload policies to prevent structural suspension and chassis cracking.",
  "provenance": [
   {
    "name": "fleet_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S04-COORDINATOR": {
  "id": "S04-COORDINATOR",
  "name": "Load & Haul Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 3.4.1",
  "department": "Fleet/Haulage",
  "persona": "Dave (Dispatch Superintendent)",
  "process": "Dave (Dispatch Superintendent)",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Little's Law Queueing: L = lambda * W",
  "mechanism": "Dynamic dispatch arbiter maximizing fleet productivity while eliminating shovel hang time and truck queueing.",
  "provenance": [
   {
    "name": "fleet_telemetry",
    "type": "BQ"
   },
   {
    "name": "dispatch_routes",
    "type": "BQ"
   }
  ],
  "tools": [
   "littles_law_haulage_solver"
  ],
  "model": "gemini-3.7-flash"
 },
 "S04-R-CRITIC": {
  "id": "S04-R-CRITIC",
  "name": "Dispatch Safety Critic (Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 3.4.1",
  "department": "Fleet/Haulage",
  "persona": "Mine Safety Lead",
  "process": "Mine Safety Lead",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S04-COORDINATOR",
  "governingEquation": "Haul Road Grade Braking Runaway Distance Envelope",
  "mechanism": "Monitors haul road grade runaway braking envelope, intersection collision proximity, and speed limits.",
  "provenance": [
   {
    "name": "fleet_telemetry",
    "type": "BQ"
   },
   {
    "name": "safety_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S05-1-CSS": {
  "id": "S05-1-CSS",
  "name": "Crusher CSS Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.5.2",
  "department": "Mineral Processing/Plant",
  "persona": "Crusher Technician",
  "process": "Crusher Technician",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S05-COORDINATOR",
  "governingEquation": "Q = 3600 * A_gap * v_discharge",
  "mechanism": "Optimizes hydraulic mantle positioning and Closed Side Setting to match SAG feed size distribution.",
  "provenance": [
   {
    "name": "crusher_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S05-2-FEED": {
  "id": "S05-2-FEED",
  "name": "Feeder Speed Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.5.3",
  "department": "Mineral Processing/Plant",
  "persona": "Control Room Operator",
  "process": "Control Room Operator",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S05-COORDINATOR",
  "governingEquation": "u(t) = Kp*e(t) + Ki*int(e)dt + Kd*de/dt",
  "mechanism": "Regulates apron feeder speed to maintain choke feeding and uniform power draw.",
  "provenance": [
   {
    "name": "crusher_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S05-3-WEAR": {
  "id": "S05-3-WEAR",
  "name": "Mantle Wear Estimator",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.5.4",
  "department": "Mineral Processing/Plant",
  "persona": "Fixed Plant Planner",
  "process": "Fixed Plant Planner",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S05-COORDINATOR",
  "governingEquation": "V = K * (W * L) / H",
  "mechanism": "Tracks mantle and concave liner abrasive wear using Archard wear modeling and tonnage throughput.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   },
   {
    "name": "crusher_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S05-COORDINATOR": {
  "id": "S05-COORDINATOR",
  "name": "Primary Crushing Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 3.5.1",
  "department": "Mineral Processing/Plant",
  "persona": "Fixed Plant Superintendent",
  "process": "Fixed Plant Superintendent",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Bond Comminution: W = 10 Wi (1/sqrt(P80) - 1/sqrt(F80))",
  "mechanism": "Arbiter for primary gyratory crusher throughput, closed side setting (CSS), and apron feeder speed.",
  "provenance": [
   {
    "name": "crusher_telemetry",
    "type": "BQ"
   },
   {
    "name": "assets",
    "type": "BQ"
   }
  ],
  "tools": [
   "bond_comminution_solver"
  ],
  "model": "gemini-3.7-flash"
 },
 "S05-R-CRITIC": {
  "id": "S05-R-CRITIC",
  "name": "Tramp Metal Critic (Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 3.5.1",
  "department": "Mineral Processing/Plant",
  "persona": "Electrical Superintendent",
  "process": "Electrical Superintendent",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S05-COORDINATOR",
  "governingEquation": "Tramp Iron Eddy-Current Sensor Interlock Gate",
  "mechanism": "Eddy-current metal detector watchdog halting crusher feed on GET teeth or drill steel detection.",
  "provenance": [
   {
    "name": "crusher_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S06-1-SAG": {
  "id": "S06-1-SAG",
  "name": "SAG Mill Load Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.6.2",
  "department": "Mineral Processing/Plant",
  "persona": "Mill Operator",
  "process": "Mill Operator",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S06-COORDINATOR",
  "governingEquation": "Acoustic Toe Angle & Ball Charge Trajectory",
  "mechanism": "Analyzes acoustic sensor arrays, bearing pressure, and motor torque to determine internal mill charge toe angle.",
  "provenance": [
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S06-2-BALL": {
  "id": "S06-2-BALL",
  "name": "Ball Mill Power Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.6.3",
  "department": "Mineral Processing/Plant",
  "persona": "Grinding Technician",
  "process": "Grinding Technician",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S06-COORDINATOR",
  "governingEquation": "Austin Population Balance Grinding Kinetics",
  "mechanism": "Optimizes grinding media addition, slurry density, and power draw to achieve target P80 liberation.",
  "provenance": [
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S06-3-CYCLONE": {
  "id": "S06-3-CYCLONE",
  "name": "Hydrocyclone Split Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.6.4",
  "department": "Mineral Processing/Plant",
  "persona": "Slurry Specialist",
  "process": "Slurry Specialist",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S06-COORDINATOR",
  "governingEquation": "Plitt Cut Size: d50c = (50.5 * Dc^0.46 * Di^0.6 * Do^0.68) / (Du^0.71 * h^0.38 * Q^0.45)",
  "mechanism": "Calculates Plitt cut size d50c, circulating load ratio, and vortex finder pressure to maintain flotation feed size.",
  "provenance": [
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S06-COORDINATOR": {
  "id": "S06-COORDINATOR",
  "name": "Grinding & Milling Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 3.6.1",
  "department": "Mineral Processing/Plant",
  "persona": "Concentrator Superintendent",
  "process": "Concentrator Superintendent",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Morrell Specific Energy: W = 4 * M_i * (x2^f(x2) - x1^f(x1))",
  "mechanism": "Coordinates SAG mill load, ball mill power draw, water addition, and hydrocyclone classification.",
  "provenance": [
   {
    "name": "plant_telemetry",
    "type": "BQ"
   },
   {
    "name": "assets",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S06-R-CRITIC": {
  "id": "S06-R-CRITIC",
  "name": "Slurry Density Critic (Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 3.6.1",
  "department": "Mineral Processing/Plant",
  "persona": "Process Chemist",
  "process": "Process Chemist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S06-COORDINATOR",
  "governingEquation": "Pipeline Critical Settling Velocity & Slurry Viscosity Limits",
  "mechanism": "Watches pipeline critical settling velocity, trunnion bearing temperature, and slurry rheology limits.",
  "provenance": [
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S07-1-REAGENT": {
  "id": "S07-1-REAGENT",
  "name": "Collector Dosing Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.7.2",
  "department": "Mineral Processing/Plant",
  "persona": "Flotation Technician",
  "process": "Flotation Technician",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S07-COORDINATOR",
  "governingEquation": "theta = (K * C) / (1 + K * C)",
  "mechanism": "Calculates potassium amyl xanthate (PAX) and frother addition rates based on ore mineralogy.",
  "provenance": [
   {
    "name": "reagent_inventory",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S07-2-AIR": {
  "id": "S07-2-AIR",
  "name": "Froth Air Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.7.3",
  "department": "Mineral Processing/Plant",
  "persona": "Plant Metallurgist",
  "process": "Plant Metallurgist",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S07-COORDINATOR",
  "governingEquation": "Gas Holdup: eps_g = J_g / (u_b + J_l)",
  "mechanism": "Regulates superficial gas velocity Jg and froth depth to control bubble residence time and entrainment.",
  "provenance": [
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S07-3-GRADE": {
  "id": "S07-3-GRADE",
  "name": "Concentrate Grade Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.7.4",
  "department": "Mineral Processing/Plant",
  "persona": "Smelter Marketing Liaison",
  "process": "Smelter Marketing Liaison",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S07-COORDINATOR",
  "governingEquation": "Separation Efficiency: SE = R_val - R_gangue",
  "mechanism": "Monitors cleaner bank concentrate assays and separation efficiency SE.",
  "provenance": [
   {
    "name": "flotation_assays",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S07-COORDINATOR": {
  "id": "S07-COORDINATOR",
  "name": "Flotation Recovery Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 3.7.1",
  "department": "Mineral Processing/Plant",
  "persona": "Marcus (Chief Metallurgist)",
  "process": "Marcus (Chief Metallurgist)",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Langmuir Kinetics: R(t) = R_inf * [1 - exp(-k*t)]",
  "mechanism": "Arbiter balancing copper recovery percentage against final concentrate grade and smelter penalty elements.",
  "provenance": [
   {
    "name": "flotation_assays",
    "type": "BQ"
   },
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S07-R-CRITIC": {
  "id": "S07-R-CRITIC",
  "name": "Smelter Penalty Critic (Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 3.7.1",
  "department": "Mineral Processing/Plant",
  "persona": "Commercial Metallurgist",
  "process": "Commercial Metallurgist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class A (Cash)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S07-COORDINATOR",
  "governingEquation": "Arsenic / Bismuth Penalty Threshold Matrix",
  "mechanism": "Adversarial auditor tracking deleterious penalty elements (Arsenic > 2000ppm, Bismuth, Antimony).",
  "provenance": [
   {
    "name": "flotation_assays",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S08-1-WATER": {
  "id": "S08-1-WATER",
  "name": "Decant Water Return Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.8.2",
  "department": "Mineral Processing/Plant",
  "persona": "Water Treatment Operator",
  "process": "Water Treatment Operator",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S08-COORDINATOR",
  "governingEquation": "V_ret = V_in - V_evap - V_seep - V_pore",
  "mechanism": "Tracks reclaim barge pumping rates, evaporation losses, and decant pond volume.",
  "provenance": [
   {
    "name": "water_balance_logs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S08-2-PORE": {
  "id": "S08-2-PORE",
  "name": "Piezometer Pressure Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.8.3",
  "department": "Mineral Processing/Plant",
  "persona": "Geotech Instrumentation Tech",
  "process": "Geotech Instrumentation Tech",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S08-COORDINATOR",
  "governingEquation": "Terzaghi Consolidation: du/dt = c_v * (d2u / dz2)",
  "mechanism": "Monitors vibrating wire piezometer pore water pressure and Terzaghi consolidation dissipation.",
  "provenance": [
   {
    "name": "tsf_piezometers",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S08-3-THICK": {
  "id": "S08-3-THICK",
  "name": "Slurry Thickener Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 3.8.4",
  "department": "Mineral Processing/Plant",
  "persona": "Dewatering Technician",
  "process": "Dewatering Technician",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S08-COORDINATOR",
  "governingEquation": "Kynch Sedimentation Solids Flux Theory",
  "mechanism": "Optimizes flocculant dosing, bed pressure, and underflow density for high-rate thickeners.",
  "provenance": [
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S08-COORDINATOR": {
  "id": "S08-COORDINATOR",
  "name": "Tailings (TSF) Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 3.8.1",
  "department": "Mineral Processing/Plant",
  "persona": "TSF Manager (Engineer of Record)",
  "process": "TSF Manager (Engineer of Record)",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "GISTM Dam Conformance & Phreatic Surface Line",
  "mechanism": "Global Industry Standard on Tailings Management (GISTM) conformance coordinator and water loop arbiter.",
  "provenance": [
   {
    "name": "tsf_piezometers",
    "type": "BQ"
   },
   {
    "name": "water_balance_logs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S08-R-CRITIC": {
  "id": "S08-R-CRITIC",
  "name": "TSF Liquefaction Critic (Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 3.8.1",
  "department": "Mineral Processing/Plant",
  "persona": "Statutory Geotechnical Reviewer",
  "process": "Statutory Geotechnical Reviewer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S08-COORDINATOR",
  "governingEquation": "Critical State Soil Mechanics & Static Liquefaction Index",
  "mechanism": "Adversarial geotech auditor checking static liquefaction state, dam crest freeboard, and spillway capacity.",
  "provenance": [
   {
    "name": "tsf_piezometers",
    "type": "BQ"
   },
   {
    "name": "safety_permits",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S09-1-VIBRATION": {
  "id": "S09-1-VIBRATION",
  "name": "Vibration FFT Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 9.3.2",
  "department": "Asset Integrity/Maintenance",
  "persona": "Vibration Analyst (Category III)",
  "process": "Vibration Analyst (Category III)",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S09-COORDINATOR",
  "governingEquation": "ISO 10816-3 RMS Velocity & BPFI Harmonics",
  "mechanism": "Processes 10-1000 Hz accelerometer streams and extracts ISO 10816-3 RMS velocity and bearing defect frequencies.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   },
   {
    "name": "crusher_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S09-2-TRIBOLOGY": {
  "id": "S09-2-TRIBOLOGY",
  "name": "Oil Tribology Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 9.3.2",
  "department": "Asset Integrity/Maintenance",
  "persona": "Lubrication Technician",
  "process": "Lubrication Technician",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S09-COORDINATOR",
  "governingEquation": "PQ Index & Karl Fischer Moisture PPM",
  "mechanism": "Monitors Particle Quantifier (PQ) index, Karl Fischer moisture PPM, viscosity, and elemental wear metals.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   },
   {
    "name": "lube_samples",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S09-3-THERMAL": {
  "id": "S09-3-THERMAL",
  "name": "Thermal IR Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 9.3.2",
  "department": "Asset Integrity/Maintenance",
  "persona": "Thermographer",
  "process": "Thermographer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S09-COORDINATOR",
  "governingEquation": "Delta T Component Temperature Rise Model",
  "mechanism": "Assesses high-speed shaft bearing temperatures, heat dissipation rates, and thermal runaway Delta-T.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   },
   {
    "name": "crusher_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S09-COORDINATOR": {
  "id": "S09-COORDINATOR",
  "name": "Asset Reliability Swarm Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 9.3.2",
  "department": "Asset Integrity/Maintenance",
  "persona": "Priya (Reliability Superintendent)",
  "process": "Priya (Reliability Superintendent)",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Weibull Hazard Rate: h(t) = (beta / eta) * (t / eta)^(beta - 1)",
  "mechanism": "P0 Crisis Arbiter and Reliability Superintendent orchestrating vibration FFT, tribology, and thermal runaway forensics.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   },
   {
    "name": "crusher_telemetry",
    "type": "BQ"
   },
   {
    "name": "erp_work_orders",
    "type": "SAP"
   }
  ],
  "tools": [
   "vibration_iso10816_solver"
  ],
  "model": "gemini-3.7-flash"
 },
 "S09-R-CRITIC": {
  "id": "S09-R-CRITIC",
  "name": "Maintenance Safety Critic (Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 9.3.2",
  "department": "Asset Integrity/Maintenance",
  "persona": "Safety Supervisor",
  "process": "Safety Supervisor",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S09-COORDINATOR",
  "governingEquation": "LOTO Isolation Integrity & Failure Window Safety Gate",
  "mechanism": "Adversarial safety auditor enforcing Lockout/Tagout (LOTO 09-CR-LOTO-03) isolation integrity and 48hr failure window.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   },
   {
    "name": "erp_work_orders",
    "type": "SAP"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S10-1-CONTRACT": {
  "id": "S10-1-CONTRACT",
  "name": "Contract Rate Auditor",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 4.2.2",
  "department": "Supply Chain/Logistics",
  "persona": "Procurement Analyst",
  "process": "Procurement Analyst",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class A (Cash)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S10-COORDINATOR",
  "governingEquation": "Levenshtein Distance & Unit Price Deviation",
  "mechanism": "Validates supplier unit prices against signed master service agreements (MSA) using fuzzy string matching.",
  "provenance": [
   {
    "name": "vendor_contracts",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S10-2-ESCALATE": {
  "id": "S10-2-ESCALATE",
  "name": "PPI Indexation Auditor",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 4.2.3",
  "department": "Supply Chain/Logistics",
  "persona": "Commercial Specialist",
  "process": "Commercial Specialist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class A (Cash)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S10-COORDINATOR",
  "governingEquation": "P_t = P_0 * [a + b*(L_t/L_0) + c*(M_t/M_0)]",
  "mechanism": "Calculates contract indexation formulas based on Producer Price Index (PPI) labor and diesel benchmarks.",
  "provenance": [
   {
    "name": "vendor_contracts",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S10-3-WARRANTY": {
  "id": "S10-3-WARRANTY",
  "name": "Warranty Recovery Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 4.2.4",
  "department": "Supply Chain/Logistics",
  "persona": "Asset Accountant",
  "process": "Asset Accountant",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class A (Cash)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S10-COORDINATOR",
  "governingEquation": "MTBF vs Warranty Period Recovery Claimer",
  "mechanism": "Cross-references component premature failure history (MTBF) against OEM warranty clauses.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   },
   {
    "name": "vendor_contracts",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S10-COORDINATOR": {
  "id": "S10-COORDINATOR",
  "name": "Procurement Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 4.2.1",
  "department": "Supply Chain/Logistics",
  "persona": "Sarah (Supply Chain Superintendent)",
  "process": "Sarah (Supply Chain Superintendent)",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class A (Cash)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Invoice Contract Matching & Rate Card Variance",
  "mechanism": "Arbiter for contract invoice rate-card matching, price escalation indices, and warranty claim recovery.",
  "provenance": [
   {
    "name": "vendor_contracts",
    "type": "BQ"
   },
   {
    "name": "invoices",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S10-R-CRITIC": {
  "id": "S10-R-CRITIC",
  "name": "Anti-Bribery Audit Critic (Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 4.2.1",
  "department": "Supply Chain/Logistics",
  "persona": "Internal Auditor",
  "process": "Internal Auditor",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S10-COORDINATOR",
  "governingEquation": "Vendor Beneficial Ownership & Single-Source Flags",
  "mechanism": "Adversarial auditor scanning single-source contracts, beneficial ownership, and FCPA anti-bribery red flags.",
  "provenance": [
   {
    "name": "vendor_contracts",
    "type": "BQ"
   },
   {
    "name": "invoices",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S11-1-STOCK": {
  "id": "S11-1-STOCK",
  "name": "Safety Stock Optimizer",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 4.3.2",
  "department": "Supply Chain/Logistics",
  "persona": "Inventory Planner",
  "process": "Inventory Planner",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class A (Cash)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S11-COORDINATOR",
  "governingEquation": "SS = Z_alpha * sqrt(L * sigma_D^2 + D^2 * sigma_L^2)",
  "mechanism": "Calculates dynamic safety stock buffers accounting for lead-time demand standard deviations.",
  "provenance": [
   {
    "name": "spares_inventory",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S11-2-LEADTIME": {
  "id": "S11-2-LEADTIME",
  "name": "Vendor Lead Time Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 4.3.3",
  "department": "Supply Chain/Logistics",
  "persona": "Supply Expediter",
  "process": "Supply Expediter",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S11-COORDINATOR",
  "governingEquation": "Gamma Distribution Lead Time Modeling",
  "mechanism": "Fits Gamma distributions to supplier shipment delays and port customs clearance lead times.",
  "provenance": [
   {
    "name": "purchase_orders",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S11-3-HOLDING": {
  "id": "S11-3-HOLDING",
  "name": "Carrying Cost Analyzer",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 4.3.4",
  "department": "Supply Chain/Logistics",
  "persona": "Cost Controller",
  "process": "Cost Controller",
  "authority": "L1 ADVISORY",
  "valueClass": "Class A (Cash)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S11-COORDINATOR",
  "governingEquation": "H = C_unit * (i + w + o)",
  "mechanism": "Evaluates working capital tie-up, warehouse insurance, and obsolescence depreciation rates.",
  "provenance": [
   {
    "name": "spares_inventory",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S11-COORDINATOR": {
  "id": "S11-COORDINATOR",
  "name": "Spares Inventory Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 4.3.1",
  "department": "Supply Chain/Logistics",
  "persona": "Warehouse Superintendent",
  "process": "Warehouse Superintendent",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class A (Cash)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Wilson EOQ: Q* = sqrt(2*D*S / H)",
  "mechanism": "Coordinates Economic Order Quantity (EOQ), safety stock levels, and warehouse carrying cost reduction.",
  "provenance": [
   {
    "name": "spares_inventory",
    "type": "BQ"
   },
   {
    "name": "purchase_orders",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S11-R-CRITIC": {
  "id": "S11-R-CRITIC",
  "name": "Dead Stock Critic (Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 4.3.1",
  "department": "Supply Chain/Logistics",
  "persona": "Finance Auditor",
  "process": "Finance Auditor",
  "authority": "L1 ADVISORY",
  "valueClass": "Class A (Cash)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S11-COORDINATOR",
  "governingEquation": "Inactive Inventory Aging (>365 Days) Write-Down",
  "mechanism": "Identifies non-moving stock (>365 days) and triggers scrap or vendor buyback recommendations.",
  "provenance": [
   {
    "name": "spares_inventory",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S12-1-RAIL": {
  "id": "S12-1-RAIL",
  "name": "Train Cycle Dispatch Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 4.4.2",
  "department": "Supply Chain/Logistics",
  "persona": "Rail Controller",
  "process": "Rail Controller",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S12-COORDINATOR",
  "governingEquation": "Railway Headway & Velocity Optimization",
  "mechanism": "Optimizes locomotive cycle headway, payload tonnage, and diesel consumption across 400km heavy-haul corridors.",
  "provenance": [
   {
    "name": "rail_schedules",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S12-2-BLEND": {
  "id": "S12-2-BLEND",
  "name": "Port Stockpile Blend Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 4.4.3",
  "department": "Supply Chain/Logistics",
  "persona": "Port Metallurgist",
  "process": "Port Metallurgist",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S12-COORDINATOR",
  "governingEquation": "Linear Blend Optimization: min ||A*x - b||",
  "mechanism": "Solves linear programming multi-stockpile blend optimization to meet customer concentrate specifications.",
  "provenance": [
   {
    "name": "stockpiles",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S12-3-BERTH": {
  "id": "S12-3-BERTH",
  "name": "Marine Laytime & Demurrage Specialist",
  "tierKey": "L2",
  "pattern": "A_SPECIALIST",
  "apqc": "APQC 4.4.4",
  "department": "Supply Chain/Logistics",
  "persona": "Marine Broker",
  "process": "Marine Broker",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class A (Cash)",
  "hitl": false,
  "endpoint": "in_process",
  "parent": "S12-COORDINATOR",
  "governingEquation": "BIMCO Laytime Pro-Rata & Demurrage Liability",
  "mechanism": "Calculates BIMCO Statement of Fact laytime usage, weather interruptions, and demurrage penalties.",
  "provenance": [
   {
    "name": "port_vessels",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S12-COORDINATOR": {
  "id": "S12-COORDINATOR",
  "name": "Supply Chain & Port Coordinator",
  "tierKey": "L2",
  "pattern": "A_COORDINATOR",
  "apqc": "APQC 4.4.1",
  "department": "Supply Chain/Logistics",
  "persona": "Logistics Manager",
  "process": "Logistics Manager",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class A (Cash)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Dynamic Network Sim: min sum(Rail + Port + Demurrage)",
  "mechanism": "Orchestrates train scheduling, stockpile blending, vessel laytime, and demurrage avoidance.",
  "provenance": [
   {
    "name": "rail_schedules",
    "type": "BQ"
   },
   {
    "name": "port_vessels",
    "type": "BQ"
   },
   {
    "name": "stockpiles",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "S12-R-CRITIC": {
  "id": "S12-R-CRITIC",
  "name": "Moisture & TML Critic (Red Team)",
  "tierKey": "L2",
  "pattern": "A_CRITIC",
  "apqc": "APQC 4.4.1",
  "department": "Supply Chain/Logistics",
  "persona": "Cargo Surveyor",
  "process": "Cargo Surveyor",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "in_process",
  "parent": "S12-COORDINATOR",
  "governingEquation": "IMSBC Transportable Moisture Limit (TML) Interlock",
  "mechanism": "Enforces International Maritime Solid Bulk Cargoes (IMSBC) Transportable Moisture Limit (TML) interlocks.",
  "provenance": [
   {
    "name": "port_vessels",
    "type": "BQ"
   },
   {
    "name": "stockpiles",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D01": {
  "id": "D01",
  "name": "Core Image Segmenter",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.1.2",
  "department": "Exploration/Geology",
  "persona": "Elena (Mine Geologist)",
  "process": "Elena (Mine Geologist)",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "ResNet-UNet Rock Classifier (<12s/tray)",
  "mechanism": "Performs automated semantic segmentation of diamond drill core trays and RQD computation in <12s.",
  "provenance": [
   {
    "name": "drill_holes",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D02": {
  "id": "D02",
  "name": "Hyperspectral Mineral Mapper",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.1.2",
  "department": "Exploration/Geology",
  "persona": "Geochemist",
  "process": "Geochemist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "SWIR/VNIR Spectral Feature Extractor",
  "mechanism": "Extracts SWIR/VNIR spectral features to quantify copper alteration and compute CuEq with QA/QC validation.",
  "provenance": [
   {
    "name": "drill_holes",
    "type": "BQ"
   },
   {
    "name": "assay_logs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D03": {
  "id": "D03",
  "name": "JORC Classification Auditor",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.1.1",
  "department": "Exploration/Geology",
  "persona": "Competent Person",
  "process": "Competent Person",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Spatial Drill Spacing Confidence Index",
  "mechanism": "Computes spatial drill spacing confidence index and spherical variogram kriging variance for JORC audit.",
  "provenance": [
   {
    "name": "drill_holes",
    "type": "BQ"
   },
   {
    "name": "geological_block_models",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D04": {
  "id": "D04",
  "name": "Blast Wave Front Sim",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.3.2",
  "department": "Mine Planning/Operations",
  "persona": "D&B Specialist",
  "process": "D&B Specialist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Chapman-Jouguet Detonation Hugoniot Solver",
  "mechanism": "Solves Chapman-Jouguet detonation Hugoniot equations for explosive pressure pulse propagation.",
  "provenance": [
   {
    "name": "blast_designs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D05": {
  "id": "D05",
  "name": "Flyrock Trajectory Predictor",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.3.1",
  "department": "Mine Planning/Operations",
  "persona": "Shotfirer",
  "process": "Shotfirer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Ballistic Range: R = (v0^2 * sin(2*theta)) / g",
  "mechanism": "Ballistic physics solver estimating maximum flyrock travel distance and safety exclusion zone.",
  "provenance": [
   {
    "name": "blast_designs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D06": {
  "id": "D06",
  "name": "In-Situ Fragment Analyzer",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.3.3",
  "department": "Mine Planning/Operations",
  "persona": "D&B Engineer",
  "process": "D&B Engineer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Split-Desktop High-Res Image Segmentation",
  "mechanism": "High-resolution muckpile optical segmentation calculating Rosin-Rammler size distribution curves.",
  "provenance": [
   {
    "name": "blast_designs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D07": {
  "id": "D07",
  "name": "Radar Slope Displacement",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.2.2",
  "department": "Mine Planning/Operations",
  "persona": "Geotech Engineer",
  "process": "Geotech Engineer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "InSAR Phase Shift Velocity Gradient Delta_phi",
  "mechanism": "Tracks real-time InSAR slope radar displacement and applies Fukuzono inverse velocity failure forecasting.",
  "provenance": [
   {
    "name": "geotech_sensors",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D08": {
  "id": "D08",
  "name": "Borehole Seismicity Sentinel",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.2.2",
  "department": "Mine Planning/Operations",
  "persona": "Microseismic Technician",
  "process": "Microseismic Technician",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Gutenberg-Richter Law: log(N) = a - b*M",
  "mechanism": "Monitors microseismic acoustic emissions and applies Gutenberg-Richter magnitude frequency laws.",
  "provenance": [
   {
    "name": "geotech_sensors",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D09": {
  "id": "D09",
  "name": "Bench Drainage Permeability",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.2.4",
  "department": "Mine Planning/Operations",
  "persona": "Hydrogeologist",
  "process": "Hydrogeologist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Darcy's Law: Q = -k * A * (dh / dl)",
  "mechanism": "Solves Darcy's law for pore pressure dissipation and open-pit bench horizontal drain discharge.",
  "provenance": [
   {
    "name": "pit_designs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D10": {
  "id": "D10",
  "name": "Haul Road Rolling Resist",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.4.3",
  "department": "Fleet/Haulage",
  "persona": "Civil Road Superintendent",
  "process": "Civil Road Superintendent",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Rolling Resistance: RR = W * (C_rr + sin(theta))",
  "mechanism": "Computes haul road dynamic rolling resistance coefficient from truck wheel torque and road grade.",
  "provenance": [
   {
    "name": "fleet_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D11": {
  "id": "D11",
  "name": "Fleet Fuel Burn Sentinel",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.4.4",
  "department": "Fleet/Haulage",
  "persona": "Energy Manager",
  "process": "Energy Manager",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Specific Fuel Consumption: SFC = m_dot_f / P_engine",
  "mechanism": "Monitors haul truck ECM engine telemetry to calculate brake-specific fuel consumption (L/tonne-km).",
  "provenance": [
   {
    "name": "fleet_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D12": {
  "id": "D12",
  "name": "Tire TKPH Telemetry Agent",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.4.4",
  "department": "Fleet/Haulage",
  "persona": "Mobile Fleet Maintenance Lead",
  "process": "Mobile Fleet Maintenance Lead",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "TKPH = Q_avg * V_avg <= Rating",
  "mechanism": "Calculates Tonne-Kilometre-Per-Hour thermal ratings to prevent tire delamination blowouts.",
  "provenance": [
   {
    "name": "fleet_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D13": {
  "id": "D13",
  "name": "Shovel GET Tooth Sentinel",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.4.2",
  "department": "Fleet/Haulage",
  "persona": "Shovel Operator",
  "process": "Shovel Operator",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "YOLOv8 Ground Engaging Tool Watcher",
  "mechanism": "Computer vision and payload inertial watchdog detecting lost ground engaging tool bucket teeth.",
  "provenance": [
   {
    "name": "fleet_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D14": {
  "id": "D14",
  "name": "Autogenous Grinding Sound",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.6.2",
  "department": "Mineral Processing/Plant",
  "persona": "Mill Operator",
  "process": "Mill Operator",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Acoustic Power Spectrum 1/3 Octave Band FFT",
  "mechanism": "Processes 1/3-octave band acoustic sensor arrays on SAG mills to identify ball-on-liner impact modes.",
  "provenance": [
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D15": {
  "id": "D15",
  "name": "Trommel Screen Blinding",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.6.4",
  "department": "Mineral Processing/Plant",
  "persona": "Concentrator Technician",
  "process": "Concentrator Technician",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Aperture Occlusion Optical Flow Percentage",
  "mechanism": "Quantifies screen mesh aperture blinding and near-size pegging on SAG discharge trommels.",
  "provenance": [
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D16": {
  "id": "D16",
  "name": "Slurry Pump Cavitation",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.6.4",
  "department": "Mineral Processing/Plant",
  "persona": "Fixed Plant Fitter",
  "process": "Fixed Plant Fitter",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Net Positive Suction Head: NPSHa > NPSHr",
  "mechanism": "Computes Net Positive Suction Head Available (NPSHa) vs Required (NPSHr) to detect pump cavitation.",
  "provenance": [
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D17": {
  "id": "D17",
  "name": "Sump Level Anti-Surge",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.6.4",
  "department": "Mineral Processing/Plant",
  "persona": "Process Control Specialist",
  "process": "Process Control Specialist",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Mass Balance Continuity: A * (dh/dt) = Q_in - Q_out",
  "mechanism": "Dynamic mass balance continuity solver regulating variable speed drive pumps to prevent sump overflow.",
  "provenance": [
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D18": {
  "id": "D18",
  "name": "Froth Bubble Sizing/Color",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.7.2",
  "department": "Mineral Processing/Plant",
  "persona": "Flotation Technician",
  "process": "Flotation Technician",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Sauter Mean Bubble Diameter d32 & RGB Grade Proxy",
  "mechanism": "Extracts Sauter mean bubble diameter d32 and RGB chromaticity from flotation froth camera feeds.",
  "provenance": [
   {
    "name": "flotation_assays",
    "type": "BQ"
   },
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D19": {
  "id": "D19",
  "name": "Xanthate Degradation",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.7.2",
  "department": "Mineral Processing/Plant",
  "persona": "Reagent Chemist",
  "process": "Reagent Chemist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "1st-Order Hydrolysis Kinetics: C(t) = C_0 * exp(-k*t)",
  "mechanism": "Arrhenius chemical kinetics model tracking temperature and pH-dependent hydrolysis of xanthate collectors.",
  "provenance": [
   {
    "name": "reagent_inventory",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D20": {
  "id": "D20",
  "name": "Acid Mine Drainage ORP",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.8.2",
  "department": "Mineral Processing/Plant",
  "persona": "Environmental Superintendent",
  "process": "Environmental Superintendent",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Nernst Equation: E_h = E0 - (RT/nF) * ln(Q)",
  "mechanism": "Nernst electrochemical equation solver calculating net acid generation potential and lime neutralization.",
  "provenance": [
   {
    "name": "water_balance_logs",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D21": {
  "id": "D21",
  "name": "Tailings Beach Slope",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.8.1",
  "department": "Mineral Processing/Plant",
  "persona": "TSF Engineer",
  "process": "TSF Engineer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Non-Newtonian Yield Stress: tau_y = rho * g * h * sin(theta)",
  "mechanism": "Non-Newtonian yield stress subaerial deposition model predicting tailings beach angle theta.",
  "provenance": [
   {
    "name": "tsf_piezometers",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D22": {
  "id": "D22",
  "name": "Transformer Dissolved Gas",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 9.3.2",
  "department": "Asset Integrity/Maintenance",
  "persona": "HV Electrician",
  "process": "HV Electrician",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Duval Triangle & DGA Ratio (Acetylene / Hydrogen)",
  "mechanism": "IEC 60599 dissolved gas analyzer (DGA) evaluating Duval Triangle 1 coordinates for transformer arcing faults.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D23": {
  "id": "D23",
  "name": "Motor Partial Discharge",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 9.3.2",
  "department": "Asset Integrity/Maintenance",
  "persona": "Electrical Engineer",
  "process": "Electrical Engineer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "High-Frequency Transient Phase-Resolved PD",
  "mechanism": "High-frequency phase-resolved partial discharge pulse counter assessing 6.6kV/11kV stator dielectric health.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D24": {
  "id": "D24",
  "name": "Conveyor Belt Rip Ultra",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 9.3.2",
  "department": "Asset Integrity/Maintenance",
  "persona": "Belt Splicer Lead",
  "process": "Belt Splicer Lead",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Time-of-Flight Acoustic Wave Attenuation",
  "mechanism": "Acoustic time-of-flight transducer array assessing overland conveyor steel cord rips and puncture tears.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D25": {
  "id": "D25",
  "name": "Chute Wear Ultrasonic",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 9.3.2",
  "department": "Asset Integrity/Maintenance",
  "persona": "Boilermaker Lead",
  "process": "Boilermaker Lead",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Ultrasonic Thickness Pulse-Echo Gauge: d = (v * t) / 2",
  "mechanism": "Archard abrasive wear model tracking Hardox 500 transfer chute wear plates to forecast reline shutdowns.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D26": {
  "id": "D26",
  "name": "Maintenance Work Backlog",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 9.3.1",
  "department": "Asset Integrity/Maintenance",
  "persona": "Tom (Maintenance Planner)",
  "process": "Tom (Maintenance Planner)",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Critical Path Method (CPM) Schedule Float",
  "mechanism": "Calculates ready-to-work maintenance backlog in crew weeks and Critical Path Method (CPM) schedule float.",
  "provenance": [
   {
    "name": "erp_work_orders",
    "type": "SAP"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D27": {
  "id": "D27",
  "name": "Contractor Idle Fee Audit",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 4.2.3",
  "department": "Commercial/Finance/Strategy",
  "persona": "Commercial Manager",
  "process": "Commercial Manager",
  "authority": "L1 ADVISORY",
  "valueClass": "Class A (Cash)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Standby Hours vs Daily Rate Dispute Validator",
  "mechanism": "Cross-references contractor standby invoices against FMS GPS telematics to eliminate over-billing.",
  "provenance": [
   {
    "name": "vendor_contracts",
    "type": "BQ"
   },
   {
    "name": "fleet_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D28": {
  "id": "D28",
  "name": "Fuel Bunkering Density",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 4.2.4",
  "department": "Commercial/Finance/Strategy",
  "persona": "Fuel Logistics Officer",
  "process": "Fuel Logistics Officer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class A (Cash)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "API Gravity: API = (141.5 / SG) - 131.5",
  "mechanism": "ASTM D1250 petroleum temperature compensation standardizing gross diesel delivery volume to 15 deg C.",
  "provenance": [
   {
    "name": "purchase_orders",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D29": {
  "id": "D29",
  "name": "Grinding Ball Wear Batch",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 3.6.3",
  "department": "Asset Integrity/Maintenance",
  "persona": "Plant Metallurgist",
  "process": "Plant Metallurgist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Bond Wear Rate: M_ball = 0.16 * (Wi - 7)^0.5",
  "mechanism": "Calculates daily forged steel grinding ball wear (g/kWh) using Bond wear equations to schedule charging.",
  "provenance": [
   {
    "name": "spares_inventory",
    "type": "BQ"
   },
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D30": {
  "id": "D30",
  "name": "Lube Oil Cleanliness",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 9.3.2",
  "department": "Asset Integrity/Maintenance",
  "persona": "Tribologist",
  "process": "Tribologist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "ISO 4406 Solid Contamination Cleanliness Code",
  "mechanism": "Converts optical particle counts (>=4, 6, 14 microns) into standard 3-digit ISO 4406 cleanliness codes.",
  "provenance": [
   {
    "name": "assets",
    "type": "BQ"
   },
   {
    "name": "lube_samples",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D31": {
  "id": "D31",
  "name": "Duplicate Invoice Match",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 4.2.2",
  "department": "Commercial/Finance/Strategy",
  "persona": "Accounts Payable Lead",
  "process": "Accounts Payable Lead",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class A (Cash)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Levenshtein Distance & Exact Amount Hash Match",
  "mechanism": "Scans accounts payable invoices with Levenshtein fuzzy vendor matching and exact amount hashes.",
  "provenance": [
   {
    "name": "invoices",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D32": {
  "id": "D32",
  "name": "Consignment Stock Logger",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 4.3.2",
  "department": "Supply Chain/Logistics",
  "persona": "Warehouse Clerk",
  "process": "Warehouse Clerk",
  "authority": "L2 BOUNDED ACTION",
  "valueClass": "Class A (Cash)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "RFID Tag vs SAP Movement Type 201 Reconciler",
  "mechanism": "Reconciles physical RFID warehouse gate departure logs against SAP ERP Movement Type 201 records.",
  "provenance": [
   {
    "name": "spares_inventory",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D33": {
  "id": "D33",
  "name": "Laytime BIMCO Parser",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 4.4.4",
  "department": "Supply Chain/Logistics",
  "persona": "Logistics Officer",
  "process": "Logistics Officer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class A (Cash)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "BIMCO Laytime Standard Statement of Fact Parser",
  "mechanism": "Parses BIMCO Statement of Fact records, calculating weather working day deductions and demurrage.",
  "provenance": [
   {
    "name": "port_vessels",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D34": {
  "id": "D34",
  "name": "Reagent Shelf Life",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 4.3.3",
  "department": "Supply Chain/Logistics",
  "persona": "Hazmat Technician",
  "process": "Hazmat Technician",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Arrhenius Reaction: k = A * exp(-E_a / RT)",
  "mechanism": "Arrhenius kinetic model evaluating thermal degradation and potency loss of bulk flotation collectors.",
  "provenance": [
   {
    "name": "reagent_inventory",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D35": {
  "id": "D35",
  "name": "Locomotive Brake Curve",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 4.4.2",
  "department": "Supply Chain/Logistics",
  "persona": "Rail Master",
  "process": "Rail Master",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Braking Distance: d = v^2 / [2g*(mu +- theta)]",
  "mechanism": "Heavy-haul locomotive braking distance solver calculating kinetic energy and regenerative retard limits.",
  "provenance": [
   {
    "name": "rail_schedules",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D36": {
  "id": "D36",
  "name": "Shiploader 3D LiDAR",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 4.4.4",
  "department": "Supply Chain/Logistics",
  "persona": "Shiploader Operator",
  "process": "Shiploader Operator",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "3D LiDAR Collision Margin: Distance > 5.0m",
  "mechanism": "Continuous 3D LiDAR point cloud anti-collision sentinel checking clearance between shiploader and ship hatch.",
  "provenance": [
   {
    "name": "port_vessels",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D37": {
  "id": "D37",
  "name": "SAFTE Driver Fatigue",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 10.1.1",
  "department": "Safety/OHSE/ESG",
  "persona": "Jack (Mine Safety Lead)",
  "process": "Jack (Mine Safety Lead)",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "SAFTE Score: E(t) = S(t) + C(t) - P(t)",
  "mechanism": "Biomathematical circadian fatigue evaluation analyzing driver sleep logs and PVT reaction times.",
  "provenance": [
   {
    "name": "fatigue_monitoring_logs",
    "type": "BQ"
   }
  ],
  "tools": [
   "safte_circadian_fatigue_solver"
  ],
  "model": "gemini-3.7-flash"
 },
 "D38": {
  "id": "D38",
  "name": "Confined Space Gas",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 10.1.2",
  "department": "Safety/OHSE/ESG",
  "persona": "Industrial Hygienist",
  "process": "Industrial Hygienist",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Gas Limits: LEL < 10%, O2 in [19.5, 23.5]%, H2S < 10ppm",
  "mechanism": "Real-time multi-gas sentinel monitoring O2, LEL, H2S, and CO atmospheric levels in mills and sumps.",
  "provenance": [
   {
    "name": "safety_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D39": {
  "id": "D39",
  "name": "Carbon Scope 1/2 Tracker",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 10.3.1",
  "department": "Safety/OHSE/ESG",
  "persona": "Sustainability Lead",
  "process": "Sustainability Lead",
  "authority": "L1 ADVISORY",
  "valueClass": "Class B (Metric)",
  "hitl": false,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "GHG Protocol: CO2e = sum(Fuel * EF) + (Grid_MWh * EF)",
  "mechanism": "GHG Protocol emissions calculator determining Scope 1 diesel and Scope 2 grid carbon intensity per tonne Cu.",
  "provenance": [
   {
    "name": "fleet_telemetry",
    "type": "BQ"
   },
   {
    "name": "plant_telemetry",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 },
 "D40": {
  "id": "D40",
  "name": "Statutory Permit Guardian",
  "tierKey": "L3",
  "pattern": "B_DEEP",
  "apqc": "APQC 10.2.1",
  "department": "Safety/OHSE/ESG",
  "persona": "Legal Counsel & Compliance Officer",
  "process": "Legal Counsel & Compliance Officer",
  "authority": "L1 ADVISORY",
  "valueClass": "Class C (Risk)",
  "hitl": true,
  "endpoint": "cloud_run",
  "parent": null,
  "governingEquation": "Regulatory Obligation NLP Entity Matcher & Tenement Lease Auditor",
  "mechanism": "Monitors tenement lease expiry, EPA environmental licenses, and water abstraction statutory rights.",
  "provenance": [
   {
    "name": "tenement_leases",
    "type": "BQ"
   },
   {
    "name": "safety_permits",
    "type": "BQ"
   }
  ],
  "tools": [],
  "model": "gemini-3.7-flash"
 }
};

window.agentTierCounts = {
 "L0": 1,
 "L2": 60,
 "L3": 40
};
