/* GENERATED by scripts/build_data_graph.py -- do not edit by hand.
 * Source: live `genial-union-475913-i7.mining_data` -- table storage and INFORMATION_SCHEMA.COLUMNS.
 * Layer and domain are classifications declared in the generator; every
 * other field is read straight from BigQuery. */
window.dataGraph = {
 "nodes": [
  {
   "id": "agent_approvals",
   "layer": "control",
   "layerLabel": "Agent control plane",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 746,
   "bytes": 149597,
   "columnCount": 11,
   "columns": [
    {
     "name": "approval_id",
     "type": "STRING"
    },
    {
     "name": "agent_id",
     "type": "STRING"
    },
    {
     "name": "action_type",
     "type": "STRING"
    },
    {
     "name": "target_entity",
     "type": "STRING"
    },
    {
     "name": "decision",
     "type": "STRING"
    },
    {
     "name": "approver_principal",
     "type": "STRING"
    },
    {
     "name": "decided_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "hold_duration_ms",
     "type": "INT64"
    },
    {
     "name": "agent_reasoning_snapshot",
     "type": "STRING"
    },
    {
     "name": "unverified_flags",
     "type": "ARRAY<STRING>"
    },
    {
     "name": "source_tables",
     "type": "ARRAY<STRING>"
    }
   ],
   "weight": 2.879,
   "readBy": []
  },
  {
   "id": "agent_catalog",
   "layer": "control",
   "layerLabel": "Agent control plane",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 100,
   "bytes": 15898,
   "columnCount": 11,
   "columns": [
    {
     "name": "agent_id",
     "type": "STRING"
    },
    {
     "name": "display_name",
     "type": "STRING"
    },
    {
     "name": "pattern",
     "type": "STRING"
    },
    {
     "name": "swarm_id",
     "type": "STRING"
    },
    {
     "name": "swarm_role",
     "type": "STRING"
    },
    {
     "name": "apqc_code",
     "type": "STRING"
    },
    {
     "name": "persona",
     "type": "STRING"
    },
    {
     "name": "value_branch",
     "type": "STRING"
    },
    {
     "name": "model_tier",
     "type": "STRING"
    },
    {
     "name": "hitl_required",
     "type": "BOOL"
    },
    {
     "name": "source_tables",
     "type": "ARRAY<STRING>"
    }
   ],
   "weight": 2.041,
   "readBy": []
  },
  {
   "id": "agent_run_log",
   "layer": "control",
   "layerLabel": "Agent control plane",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 918,
   "bytes": 111894,
   "columnCount": 10,
   "columns": [
    {
     "name": "run_id",
     "type": "STRING"
    },
    {
     "name": "agent_id",
     "type": "STRING"
    },
    {
     "name": "parent_run_id",
     "type": "STRING"
    },
    {
     "name": "pattern",
     "type": "STRING"
    },
    {
     "name": "status",
     "type": "STRING"
    },
    {
     "name": "blocked_reason",
     "type": "STRING"
    },
    {
     "name": "started_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "ended_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "tables_read",
     "type": "ARRAY<STRING>"
    },
    {
     "name": "rows_scanned",
     "type": "INT64"
    }
   ],
   "weight": 2.968,
   "readBy": []
  },
  {
   "id": "assay_logs",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 7,
   "columns": [
    {
     "name": "drill_hole_id",
     "type": "STRING"
    },
    {
     "name": "depth_start_meters",
     "type": "FLOAT64"
    },
    {
     "name": "depth_end_meters",
     "type": "FLOAT64"
    },
    {
     "name": "geology_code",
     "type": "STRING"
    },
    {
     "name": "copper_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "gold_grade_gpt",
     "type": "FLOAT64"
    },
    {
     "name": "logged_at",
     "type": "TIMESTAMP"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "D02",
    "S01-2-GEOSTAT",
    "S01-COORDINATOR",
    "S01-R-CRITIC"
   ]
  },
  {
   "id": "asset_clustering_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 8,
   "bytes": 14796,
   "columnCount": 0,
   "columns": [],
   "weight": 1.255,
   "readBy": []
  },
  {
   "id": "asset_dependencies",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 3,
   "bytes": 135,
   "columnCount": 4,
   "columns": [
    {
     "name": "impact_score",
     "type": "FLOAT64"
    },
    {
     "name": "dependency_type",
     "type": "STRING"
    },
    {
     "name": "target_id",
     "type": "STRING"
    },
    {
     "name": "source_id",
     "type": "STRING"
    }
   ],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "assets",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 88,
   "bytes": 19003,
   "columnCount": 8,
   "columns": [
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "asset_name",
     "type": "STRING"
    },
    {
     "name": "asset_type",
     "type": "STRING"
    },
    {
     "name": "current_state",
     "type": "STRING"
    },
    {
     "name": "criticality_rating",
     "type": "STRING"
    },
    {
     "name": "installation_date",
     "type": "DATE"
    },
    {
     "name": "location_gis",
     "type": "STRING"
    },
    {
     "name": "physics_parameters",
     "type": "STRING"
    }
   ],
   "weight": 1.991,
   "readBy": [
    "D22",
    "D23",
    "D24",
    "D25",
    "D30",
    "S05-3-WEAR",
    "S05-COORDINATOR",
    "S06-COORDINATOR",
    "S09-1-VIBRATION",
    "S09-2-TRIBOLOGY",
    "S09-3-THERMAL",
    "S09-COORDINATOR",
    "S09-R-CRITIC",
    "S10-3-WARRANTY"
   ]
  },
  {
   "id": "bid_parts_edge",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 25,
   "bytes": 2402,
   "columnCount": 3,
   "columns": [
    {
     "name": "edge_id",
     "type": "STRING"
    },
    {
     "name": "bid_id",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    }
   ],
   "weight": 1.544,
   "readBy": []
  },
  {
   "id": "biometric_fatigue_logs",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 3340,
   "bytes": 136940,
   "columnCount": 6,
   "columns": [
    {
     "name": "sleep_deficit_hours",
     "type": "FLOAT64"
    },
    {
     "name": "microsleep_events_detected",
     "type": "INT64"
    },
    {
     "name": "fatigue_alert_triggered",
     "type": "BOOL"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "heart_rate_bpm",
     "type": "INT64"
    },
    {
     "name": "operator_id",
     "type": "STRING"
    }
   ],
   "weight": 3.525,
   "readBy": []
  },
  {
   "id": "blast_designs",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 180,
   "bytes": 21025,
   "columnCount": 12,
   "columns": [
    {
     "name": "blast_id",
     "type": "STRING"
    },
    {
     "name": "block_id",
     "type": "STRING"
    },
    {
     "name": "design_date",
     "type": "DATE"
    },
    {
     "name": "bench_location",
     "type": "STRING"
    },
    {
     "name": "burden_m",
     "type": "FLOAT64"
    },
    {
     "name": "spacing_m",
     "type": "FLOAT64"
    },
    {
     "name": "hole_diameter_mm",
     "type": "INT64"
    },
    {
     "name": "hole_depth_m",
     "type": "FLOAT64"
    },
    {
     "name": "powder_factor_kg_per_m3",
     "type": "FLOAT64"
    },
    {
     "name": "explosive_type",
     "type": "STRING"
    },
    {
     "name": "designed_by",
     "type": "STRING"
    },
    {
     "name": "approved",
     "type": "BOOL"
    }
   ],
   "weight": 2.279,
   "readBy": [
    "D04",
    "D05",
    "D06",
    "S03-1-GEOMETRY",
    "S03-COORDINATOR",
    "S03-R-CRITIC"
   ]
  },
  {
   "id": "capital_options",
   "layer": "simulation",
   "layerLabel": "Scenario & simulation",
   "domain": "planning",
   "domainLabel": "Planning & strategy",
   "rows": 24,
   "bytes": 3476,
   "columnCount": 3,
   "columns": [
    {
     "name": "option_id",
     "type": "STRING"
    },
    {
     "name": "plan_version_id",
     "type": "STRING"
    },
    {
     "name": "description",
     "type": "STRING"
    }
   ],
   "weight": 1.531,
   "readBy": []
  },
  {
   "id": "contained_metal_price_deck",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 61,
   "bytes": 976,
   "columnCount": 2,
   "columns": [
    {
     "name": "price_date",
     "type": "DATE"
    },
    {
     "name": "contained_metal_price_usd_per_tonne",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.851,
   "readBy": []
  },
  {
   "id": "contract_clauses",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 100,
   "bytes": 52786,
   "columnCount": 7,
   "columns": [
    {
     "name": "contract_id",
     "type": "STRING"
    },
    {
     "name": "clause_id",
     "type": "STRING"
    },
    {
     "name": "clause_type",
     "type": "STRING"
    },
    {
     "name": "clause_text",
     "type": "STRING"
    },
    {
     "name": "recoverable_basis",
     "type": "STRING"
    },
    {
     "name": "doc_id",
     "type": "STRING"
    },
    {
     "name": "source_uri",
     "type": "STRING"
    }
   ],
   "weight": 2.041,
   "readBy": []
  },
  {
   "id": "contract_transactions",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 164,
   "bytes": 11804,
   "columnCount": 6,
   "columns": [
    {
     "name": "transaction_id",
     "type": "STRING"
    },
    {
     "name": "contract_id",
     "type": "STRING"
    },
    {
     "name": "vendor_name",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    },
    {
     "name": "paid_unit_price",
     "type": "FLOAT64"
    },
    {
     "name": "transaction_date",
     "type": "DATE"
    }
   ],
   "weight": 2.241,
   "readBy": []
  },
  {
   "id": "contracts",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 10,
   "bytes": 1987,
   "columnCount": 8,
   "columns": [
    {
     "name": "contract_id",
     "type": "STRING"
    },
    {
     "name": "vendor_name",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    },
    {
     "name": "agreed_unit_price",
     "type": "FLOAT64"
    },
    {
     "name": "effective_from",
     "type": "DATE"
    },
    {
     "name": "effective_to",
     "type": "DATE"
    },
    {
     "name": "bid_id",
     "type": "STRING"
    },
    {
     "name": "rebate_schedule",
     "type": "STRING"
    }
   ],
   "weight": 1.301,
   "readBy": []
  },
  {
   "id": "crusher_states",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "plant",
   "domainLabel": "Processing plant",
   "rows": 167,
   "bytes": 7515,
   "columnCount": 6,
   "columns": [
    {
     "name": "bypass_valve_open",
     "type": "BOOL"
    },
    {
     "name": "feed_rate_tph",
     "type": "FLOAT64"
    },
    {
     "name": "gap_size_setting_mm",
     "type": "FLOAT64"
    },
    {
     "name": "rotational_torque_nm",
     "type": "FLOAT64"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    }
   ],
   "weight": 2.248,
   "readBy": []
  },
  {
   "id": "crusher_telemetry",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 6,
   "columns": [
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "gap_size_setting_mm",
     "type": "FLOAT64"
    },
    {
     "name": "feed_rate_tph",
     "type": "FLOAT64"
    },
    {
     "name": "rotational_torque_nm",
     "type": "FLOAT64"
    },
    {
     "name": "bypass_valve_open",
     "type": "BOOL"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "S05-1-CSS",
    "S05-2-FEED",
    "S05-3-WEAR",
    "S05-COORDINATOR",
    "S05-R-CRITIC",
    "S09-1-VIBRATION",
    "S09-3-THERMAL",
    "S09-COORDINATOR"
   ]
  },
  {
   "id": "dispatch_routes",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 12,
   "columns": [
    {
     "name": "route_id",
     "type": "STRING"
    },
    {
     "name": "source_location",
     "type": "STRING"
    },
    {
     "name": "destination_location",
     "type": "STRING"
    },
    {
     "name": "distance_meters",
     "type": "FLOAT64"
    },
    {
     "name": "average_cycle_time_mins",
     "type": "FLOAT64"
    },
    {
     "name": "congestion_factor",
     "type": "FLOAT64"
    },
    {
     "name": "trip_count",
     "type": "INT64"
    },
    {
     "name": "mean_cycle_time_mins",
     "type": "FLOAT64"
    },
    {
     "name": "mean_queue_wait_mins",
     "type": "FLOAT64"
    },
    {
     "name": "mean_payload_tons",
     "type": "FLOAT64"
    },
    {
     "name": "congestion_index",
     "type": "FLOAT64"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "S04-2-ROUTE",
    "S04-COORDINATOR"
   ]
  },
  {
   "id": "doc_chunks",
   "layer": "corpus",
   "layerLabel": "Unstructured corpus",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 178,
   "bytes": 110203,
   "columnCount": 5,
   "columns": [
    {
     "name": "doc_id",
     "type": "STRING"
    },
    {
     "name": "folder",
     "type": "STRING"
    },
    {
     "name": "file_name",
     "type": "STRING"
    },
    {
     "name": "chunk_index",
     "type": "INT64"
    },
    {
     "name": "chunk_text",
     "type": "STRING"
    }
   ],
   "weight": 2.274,
   "readBy": []
  },
  {
   "id": "doc_chunks_embedded",
   "layer": "corpus",
   "layerLabel": "Unstructured corpus",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 178,
   "bytes": 1205793,
   "columnCount": 8,
   "columns": [
    {
     "name": "ml_generate_embedding_result",
     "type": "ARRAY<FLOAT64>"
    },
    {
     "name": "ml_generate_embedding_statistics",
     "type": "JSON"
    },
    {
     "name": "ml_generate_embedding_status",
     "type": "STRING"
    },
    {
     "name": "doc_id",
     "type": "STRING"
    },
    {
     "name": "folder",
     "type": "STRING"
    },
    {
     "name": "file_name",
     "type": "STRING"
    },
    {
     "name": "chunk_index",
     "type": "INT64"
    },
    {
     "name": "chunk_text",
     "type": "STRING"
    }
   ],
   "weight": 2.274,
   "readBy": []
  },
  {
   "id": "downtime_regression_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 3,
   "bytes": 18109,
   "columnCount": 0,
   "columns": [],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "drill_assay_logs",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "geology",
   "domainLabel": "Geology & resource",
   "rows": 295,
   "bytes": 17890,
   "columnCount": 7,
   "columns": [
    {
     "name": "logged_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "gold_grade_gpt",
     "type": "FLOAT64"
    },
    {
     "name": "depth_end_meters",
     "type": "FLOAT64"
    },
    {
     "name": "depth_start_meters",
     "type": "FLOAT64"
    },
    {
     "name": "copper_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "geology_code",
     "type": "STRING"
    },
    {
     "name": "drill_hole_id",
     "type": "STRING"
    }
   ],
   "weight": 2.484,
   "readBy": []
  },
  {
   "id": "drill_holes",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "geology",
   "domainLabel": "Geology & resource",
   "rows": 30,
   "bytes": 1800,
   "columnCount": 7,
   "columns": [
    {
     "name": "azimuth_degrees",
     "type": "FLOAT64"
    },
    {
     "name": "dip_degrees",
     "type": "FLOAT64"
    },
    {
     "name": "total_depth_meters",
     "type": "FLOAT64"
    },
    {
     "name": "collar_elevation",
     "type": "FLOAT64"
    },
    {
     "name": "collar_easting",
     "type": "FLOAT64"
    },
    {
     "name": "collar_northing",
     "type": "FLOAT64"
    },
    {
     "name": "drill_hole_id",
     "type": "STRING"
    }
   ],
   "weight": 1.602,
   "readBy": [
    "D01",
    "D02",
    "D03",
    "S01-1-LITHOLOGY",
    "S01-COORDINATOR"
   ]
  },
  {
   "id": "erp_work_orders",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 500,
   "bytes": 51117,
   "columnCount": 7,
   "columns": [
    {
     "name": "created_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "repair_cost",
     "type": "FLOAT64"
    },
    {
     "name": "description",
     "type": "STRING"
    },
    {
     "name": "work_order_id",
     "type": "STRING"
    },
    {
     "name": "priority",
     "type": "STRING"
    },
    {
     "name": "status",
     "type": "STRING"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    }
   ],
   "weight": 2.708,
   "readBy": [
    "D26",
    "S09-COORDINATOR",
    "S09-R-CRITIC"
   ]
  },
  {
   "id": "explosives_inventory",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 7,
   "bytes": 576,
   "columnCount": 8,
   "columns": [
    {
     "name": "part_number",
     "type": "STRING"
    },
    {
     "name": "part_description",
     "type": "STRING"
    },
    {
     "name": "stock_level",
     "type": "INT64"
    },
    {
     "name": "reorder_point_limit",
     "type": "INT64"
    },
    {
     "name": "lead_time_days",
     "type": "INT64"
    },
    {
     "name": "unit_price_usd",
     "type": "FLOAT64"
    },
    {
     "name": "un_class",
     "type": "STRING"
    },
    {
     "name": "magazine",
     "type": "STRING"
    }
   ],
   "weight": 1.23,
   "readBy": [
    "S03-2-EXPLOSIVE",
    "S03-COORDINATOR"
   ]
  },
  {
   "id": "fatigue_logs_node",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 3340,
   "bytes": 357380,
   "columnCount": 7,
   "columns": [
    {
     "name": "log_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "operator_id",
     "type": "STRING"
    },
    {
     "name": "heart_rate_bpm",
     "type": "INT64"
    },
    {
     "name": "sleep_deficit_hours",
     "type": "FLOAT64"
    },
    {
     "name": "microsleep_events_detected",
     "type": "INT64"
    },
    {
     "name": "fatigue_alert_triggered",
     "type": "BOOL"
    }
   ],
   "weight": 3.525,
   "readBy": []
  },
  {
   "id": "fatigue_monitoring_logs",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 6,
   "columns": [
    {
     "name": "operator_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "heart_rate_bpm",
     "type": "INT64"
    },
    {
     "name": "sleep_deficit_hours",
     "type": "FLOAT64"
    },
    {
     "name": "microsleep_events_detected",
     "type": "INT64"
    },
    {
     "name": "fatigue_alert_triggered",
     "type": "BOOL"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "D37"
   ]
  },
  {
   "id": "financial_ledger",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 4,
   "columns": [
    {
     "name": "ledger_date",
     "type": "DATE"
    },
    {
     "name": "line_item",
     "type": "STRING"
    },
    {
     "name": "amount_usd",
     "type": "FLOAT64"
    },
    {
     "name": "source_system",
     "type": "STRING"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "AGT-19"
   ]
  },
  {
   "id": "fleet_telemetry",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 7,
   "columns": [
    {
     "name": "vehicle_id",
     "type": "STRING"
    },
    {
     "name": "metric_name",
     "type": "STRING"
    },
    {
     "name": "metric_value",
     "type": "FLOAT64"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "model",
     "type": "STRING"
    },
    {
     "name": "payload_capacity_tons",
     "type": "FLOAT64"
    },
    {
     "name": "operational_status",
     "type": "STRING"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "D10",
    "D11",
    "D12",
    "D13",
    "D27",
    "D39",
    "S04-1-SHOVEL",
    "S04-3-PAYLOAD",
    "S04-COORDINATOR",
    "S04-R-CRITIC"
   ]
  },
  {
   "id": "fleet_vehicles",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "fleet",
   "domainLabel": "Mobile fleet & haulage",
   "rows": 15,
   "bytes": 1639,
   "columnCount": 7,
   "columns": [
    {
     "name": "gps_location",
     "type": "STRING"
    },
    {
     "name": "current_payload_tons",
     "type": "FLOAT64"
    },
    {
     "name": "operational_status",
     "type": "STRING"
    },
    {
     "name": "last_telemetry_sync",
     "type": "TIMESTAMP"
    },
    {
     "name": "payload_capacity_tons",
     "type": "FLOAT64"
    },
    {
     "name": "model",
     "type": "STRING"
    },
    {
     "name": "vehicle_id",
     "type": "STRING"
    }
   ],
   "weight": 1.398,
   "readBy": []
  },
  {
   "id": "flotation_assays",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 6,
   "columns": [
    {
     "name": "concentrator_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "feed_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "concentrate_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "tailings_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "recovery_rate_pct",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "D18",
    "S07-3-GRADE",
    "S07-COORDINATOR",
    "S07-R-CRITIC"
   ]
  },
  {
   "id": "geological_block_models",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "geology",
   "domainLabel": "Geology & resource",
   "rows": 1000,
   "bytes": 72939,
   "columnCount": 8,
   "columns": [
    {
     "name": "gold_grade_gpt_est",
     "type": "FLOAT64"
    },
    {
     "name": "copper_grade_pct_est",
     "type": "FLOAT64"
    },
    {
     "name": "specific_gravity",
     "type": "FLOAT64"
    },
    {
     "name": "lithology_type",
     "type": "STRING"
    },
    {
     "name": "centroid_z",
     "type": "FLOAT64"
    },
    {
     "name": "centroid_y",
     "type": "FLOAT64"
    },
    {
     "name": "centroid_x",
     "type": "FLOAT64"
    },
    {
     "name": "block_id",
     "type": "STRING"
    }
   ],
   "weight": 3.004,
   "readBy": [
    "AGT-19",
    "D03",
    "S01-3-STRUCTURAL",
    "S01-COORDINATOR"
   ]
  },
  {
   "id": "geotech_sensors",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 240,
   "bytes": 18458,
   "columnCount": 8,
   "columns": [
    {
     "name": "reading_id",
     "type": "STRING"
    },
    {
     "name": "sensor_id",
     "type": "STRING"
    },
    {
     "name": "bench_location",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "displacement_mm",
     "type": "FLOAT64"
    },
    {
     "name": "pore_pressure_kpa",
     "type": "FLOAT64"
    },
    {
     "name": "slope_angle_deg",
     "type": "FLOAT64"
    },
    {
     "name": "alarm_state",
     "type": "STRING"
    }
   ],
   "weight": 2.398,
   "readBy": [
    "D07",
    "D08",
    "S02-1-GEOTECH"
   ]
  },
  {
   "id": "haul_cycle_log",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "fleet",
   "domainLabel": "Mobile fleet & haulage",
   "rows": 3340,
   "bytes": 193720,
   "columnCount": 7,
   "columns": [
    {
     "name": "route_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "trip_count",
     "type": "INT64"
    },
    {
     "name": "mean_cycle_time_mins",
     "type": "FLOAT64"
    },
    {
     "name": "mean_queue_wait_mins",
     "type": "FLOAT64"
    },
    {
     "name": "mean_payload_tons",
     "type": "FLOAT64"
    },
    {
     "name": "congestion_index",
     "type": "FLOAT64"
    }
   ],
   "weight": 3.525,
   "readBy": []
  },
  {
   "id": "haulage_routes",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "fleet",
   "domainLabel": "Mobile fleet & haulage",
   "rows": 10,
   "bytes": 691,
   "columnCount": 6,
   "columns": [
    {
     "name": "average_cycle_time_mins",
     "type": "FLOAT64"
    },
    {
     "name": "source_location",
     "type": "STRING"
    },
    {
     "name": "congestion_factor",
     "type": "FLOAT64"
    },
    {
     "name": "distance_meters",
     "type": "FLOAT64"
    },
    {
     "name": "destination_location",
     "type": "STRING"
    },
    {
     "name": "route_id",
     "type": "STRING"
    }
   ],
   "weight": 1.301,
   "readBy": []
  },
  {
   "id": "incident_involvements",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 5,
   "bytes": 205,
   "columnCount": 4,
   "columns": [
    {
     "name": "involvement_id",
     "type": "STRING"
    },
    {
     "name": "incident_id",
     "type": "STRING"
    },
    {
     "name": "vehicle_id",
     "type": "STRING"
    },
    {
     "name": "operator_id",
     "type": "STRING"
    }
   ],
   "weight": 1.176,
   "readBy": []
  },
  {
   "id": "inventory_impact_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 4,
   "bytes": 27161,
   "columnCount": 0,
   "columns": [],
   "weight": 1.146,
   "readBy": []
  },
  {
   "id": "inventory_impact_model_crusher",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 3,
   "bytes": 10101,
   "columnCount": 0,
   "columns": [],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "inventory_impact_model_mill",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 3,
   "bytes": 10101,
   "columnCount": 0,
   "columns": [],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "inventory_impact_model_pump",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 3,
   "bytes": 10101,
   "columnCount": 0,
   "columns": [],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "inventory_levels",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "plant",
   "domainLabel": "Processing plant",
   "rows": 140,
   "bytes": 12384,
   "columnCount": 6,
   "columns": [
    {
     "name": "part_number",
     "type": "STRING"
    },
    {
     "name": "part_description",
     "type": "STRING"
    },
    {
     "name": "stock_level",
     "type": "INT64"
    },
    {
     "name": "reorder_point_limit",
     "type": "INT64"
    },
    {
     "name": "lead_time_days",
     "type": "INT64"
    },
    {
     "name": "unit_price_usd",
     "type": "FLOAT64"
    }
   ],
   "weight": 2.176,
   "readBy": []
  },
  {
   "id": "invoices",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 175,
   "bytes": 11641,
   "columnCount": 5,
   "columns": [
    {
     "name": "invoice_id",
     "type": "STRING"
    },
    {
     "name": "vendor_name",
     "type": "STRING"
    },
    {
     "name": "invoice_number",
     "type": "STRING"
    },
    {
     "name": "amount",
     "type": "FLOAT64"
    },
    {
     "name": "payment_date",
     "type": "DATE"
    }
   ],
   "weight": 2.267,
   "readBy": [
    "D31",
    "S10-COORDINATOR",
    "S10-R-CRITIC"
   ]
  },
  {
   "id": "lube_samples",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 220,
   "bytes": 24462,
   "columnCount": 12,
   "columns": [
    {
     "name": "sample_id",
     "type": "STRING"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "work_order_id",
     "type": "STRING"
    },
    {
     "name": "sampled_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "lubricant_grade",
     "type": "STRING"
    },
    {
     "name": "iron_ppm",
     "type": "FLOAT64"
    },
    {
     "name": "copper_ppm",
     "type": "FLOAT64"
    },
    {
     "name": "silicon_ppm",
     "type": "FLOAT64"
    },
    {
     "name": "water_pct",
     "type": "FLOAT64"
    },
    {
     "name": "viscosity_cst_40c",
     "type": "FLOAT64"
    },
    {
     "name": "iso_4406_code",
     "type": "STRING"
    },
    {
     "name": "verdict",
     "type": "STRING"
    }
   ],
   "weight": 2.362,
   "readBy": [
    "D30",
    "S09-2-TRIBOLOGY"
   ]
  },
  {
   "id": "maintenance_logs",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 152,
   "bytes": 24566,
   "columnCount": 6,
   "columns": [
    {
     "name": "parts_replaced",
     "type": "ARRAY<STRING>"
    },
    {
     "name": "log_entry_id",
     "type": "STRING"
    },
    {
     "name": "actual_duration_hours",
     "type": "FLOAT64"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "technician_notes",
     "type": "STRING"
    },
    {
     "name": "work_order_id",
     "type": "STRING"
    }
   ],
   "weight": 2.21,
   "readBy": []
  },
  {
   "id": "metallurgical_recovery",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "plant",
   "domainLabel": "Processing plant",
   "rows": 167,
   "bytes": 8183,
   "columnCount": 6,
   "columns": [
    {
     "name": "concentrate_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "recovery_rate_pct",
     "type": "FLOAT64"
    },
    {
     "name": "tailings_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "feed_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "concentrator_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    }
   ],
   "weight": 2.248,
   "readBy": []
  },
  {
   "id": "mine_production_schedule",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 8,
   "columns": [
    {
     "name": "plan_version_id",
     "type": "STRING"
    },
    {
     "name": "published_date",
     "type": "DATE"
    },
    {
     "name": "next_review_date",
     "type": "DATE"
    },
    {
     "name": "assumption_id",
     "type": "STRING"
    },
    {
     "name": "metric_name",
     "type": "STRING"
    },
    {
     "name": "assumed_value",
     "type": "FLOAT64"
    },
    {
     "name": "effective_date",
     "type": "DATE"
    },
    {
     "name": "superseded_date",
     "type": "DATE"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "AGT-19",
    "S02-2-SCHEDULE",
    "S02-COORDINATOR",
    "S02-R-CRITIC"
   ]
  },
  {
   "id": "ontology_concepts",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 25,
   "bytes": 448,
   "columnCount": 2,
   "columns": [
    {
     "name": "concept_name",
     "type": "STRING"
    },
    {
     "name": "concept_type",
     "type": "STRING"
    }
   ],
   "weight": 1.544,
   "readBy": []
  },
  {
   "id": "ontology_triples",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 23,
   "bytes": 1335,
   "columnCount": 5,
   "columns": [
    {
     "name": "object",
     "type": "STRING"
    },
    {
     "name": "subject",
     "type": "STRING"
    },
    {
     "name": "confidence_score",
     "type": "FLOAT64"
    },
    {
     "name": "predicate",
     "type": "STRING"
    },
    {
     "name": "triple_id",
     "type": "STRING"
    }
   ],
   "weight": 1.519,
   "readBy": []
  },
  {
   "id": "operator_vehicle_assignments",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "fleet",
   "domainLabel": "Mobile fleet & haulage",
   "rows": 5,
   "bytes": 209,
   "columnCount": 5,
   "columns": [
    {
     "name": "assignment_id",
     "type": "STRING"
    },
    {
     "name": "operator_id",
     "type": "STRING"
    },
    {
     "name": "vehicle_id",
     "type": "STRING"
    },
    {
     "name": "shift_date",
     "type": "DATE"
    },
    {
     "name": "shift_type",
     "type": "STRING"
    }
   ],
   "weight": 1.176,
   "readBy": []
  },
  {
   "id": "operators_node",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 20,
   "bytes": 680,
   "columnCount": 2,
   "columns": [
    {
     "name": "operator_id",
     "type": "STRING"
    },
    {
     "name": "operator_role",
     "type": "STRING"
    }
   ],
   "weight": 1.477,
   "readBy": []
  },
  {
   "id": "pit_designs",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 8,
   "columns": [
    {
     "name": "block_id",
     "type": "STRING"
    },
    {
     "name": "centroid_x",
     "type": "FLOAT64"
    },
    {
     "name": "centroid_y",
     "type": "FLOAT64"
    },
    {
     "name": "centroid_z",
     "type": "FLOAT64"
    },
    {
     "name": "lithology_type",
     "type": "STRING"
    },
    {
     "name": "specific_gravity",
     "type": "FLOAT64"
    },
    {
     "name": "copper_grade_pct_est",
     "type": "FLOAT64"
    },
    {
     "name": "gold_grade_gpt_est",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "D09",
    "S02-3-DUMP",
    "S02-COORDINATOR"
   ]
  },
  {
   "id": "plan_assumptions",
   "layer": "simulation",
   "layerLabel": "Scenario & simulation",
   "domain": "planning",
   "domainLabel": "Planning & strategy",
   "rows": 42,
   "bytes": 2740,
   "columnCount": 6,
   "columns": [
    {
     "name": "assumption_id",
     "type": "STRING"
    },
    {
     "name": "plan_version_id",
     "type": "STRING"
    },
    {
     "name": "metric_name",
     "type": "STRING"
    },
    {
     "name": "assumed_value",
     "type": "FLOAT64"
    },
    {
     "name": "effective_date",
     "type": "DATE"
    },
    {
     "name": "superseded_date",
     "type": "DATE"
    }
   ],
   "weight": 1.716,
   "readBy": []
  },
  {
   "id": "plan_scenarios",
   "layer": "simulation",
   "layerLabel": "Scenario & simulation",
   "domain": "planning",
   "domainLabel": "Planning & strategy",
   "rows": 12,
   "bytes": 3040,
   "columnCount": 5,
   "columns": [
    {
     "name": "scenario_id",
     "type": "STRING"
    },
    {
     "name": "plan_version_id",
     "type": "STRING"
    },
    {
     "name": "assumption_delta",
     "type": "STRING"
    },
    {
     "name": "reversal_trigger",
     "type": "STRING"
    },
    {
     "name": "reversal_cost",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.342,
   "readBy": []
  },
  {
   "id": "plan_versions",
   "layer": "simulation",
   "layerLabel": "Scenario & simulation",
   "domain": "planning",
   "domainLabel": "Planning & strategy",
   "rows": 6,
   "bytes": 168,
   "columnCount": 3,
   "columns": [
    {
     "name": "plan_version_id",
     "type": "STRING"
    },
    {
     "name": "published_date",
     "type": "DATE"
    },
    {
     "name": "next_review_date",
     "type": "DATE"
    }
   ],
   "weight": 1.204,
   "readBy": []
  },
  {
   "id": "plant_telemetry",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 5,
   "columns": [
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "metric_name",
     "type": "STRING"
    },
    {
     "name": "metric_value",
     "type": "FLOAT64"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "asset_class",
     "type": "STRING"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "D14",
    "D15",
    "D16",
    "D17",
    "D18",
    "D29",
    "D39",
    "S06-1-SAG",
    "S06-2-BALL",
    "S06-3-CYCLONE",
    "S06-COORDINATOR",
    "S06-R-CRITIC",
    "S07-2-AIR",
    "S07-COORDINATOR",
    "S08-3-THICK"
   ]
  },
  {
   "id": "port_vessels",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 40,
   "bytes": 5026,
   "columnCount": 11,
   "columns": [
    {
     "name": "vessel_id",
     "type": "STRING"
    },
    {
     "name": "vessel_name",
     "type": "STRING"
    },
    {
     "name": "berth",
     "type": "STRING"
    },
    {
     "name": "laycan_start",
     "type": "DATE"
    },
    {
     "name": "arrival_date",
     "type": "DATE"
    },
    {
     "name": "departure_date",
     "type": "DATE"
    },
    {
     "name": "consist_ids",
     "type": "ARRAY<STRING>"
    },
    {
     "name": "loaded_tonnes",
     "type": "FLOAT64"
    },
    {
     "name": "moisture_pct",
     "type": "FLOAT64"
    },
    {
     "name": "tml_pct",
     "type": "FLOAT64"
    },
    {
     "name": "demurrage_days",
     "type": "INT64"
    }
   ],
   "weight": 1.699,
   "readBy": [
    "D33",
    "D36",
    "S12-3-BERTH",
    "S12-COORDINATOR",
    "S12-R-CRITIC"
   ]
  },
  {
   "id": "procurement_bids",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 300,
   "bytes": 21775,
   "columnCount": 7,
   "columns": [
    {
     "name": "technical_rating_score",
     "type": "FLOAT64"
    },
    {
     "name": "compliance_checked",
     "type": "BOOL"
    },
    {
     "name": "rfp_id",
     "type": "STRING"
    },
    {
     "name": "proposed_cost",
     "type": "FLOAT64"
    },
    {
     "name": "bid_status",
     "type": "STRING"
    },
    {
     "name": "vendor_name",
     "type": "STRING"
    },
    {
     "name": "bid_id",
     "type": "STRING"
    }
   ],
   "weight": 2.491,
   "readBy": []
  },
  {
   "id": "purchase_orders",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 180,
   "bytes": 29604,
   "columnCount": 13,
   "columns": [
    {
     "name": "po_id",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    },
    {
     "name": "part_description",
     "type": "STRING"
    },
    {
     "name": "vendor_name",
     "type": "STRING"
    },
    {
     "name": "contract_id",
     "type": "STRING"
    },
    {
     "name": "order_date",
     "type": "DATE"
    },
    {
     "name": "promised_date",
     "type": "DATE"
    },
    {
     "name": "received_date",
     "type": "DATE"
    },
    {
     "name": "quoted_lead_time_days",
     "type": "INT64"
    },
    {
     "name": "actual_lead_time_days",
     "type": "INT64"
    },
    {
     "name": "qty_ordered",
     "type": "INT64"
    },
    {
     "name": "unit_price_usd",
     "type": "FLOAT64"
    },
    {
     "name": "line_value_usd",
     "type": "FLOAT64"
    }
   ],
   "weight": 2.279,
   "readBy": [
    "D28",
    "S11-2-LEADTIME",
    "S11-COORDINATOR"
   ]
  },
  {
   "id": "qaqc_standards",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 8,
   "columns": [
    {
     "name": "drill_hole_id",
     "type": "STRING"
    },
    {
     "name": "depth_start_meters",
     "type": "FLOAT64"
    },
    {
     "name": "depth_end_meters",
     "type": "FLOAT64"
    },
    {
     "name": "geology_code",
     "type": "STRING"
    },
    {
     "name": "copper_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "gold_grade_gpt",
     "type": "FLOAT64"
    },
    {
     "name": "logged_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "both_elements_assayed",
     "type": "BOOL"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "S01-R-CRITIC"
   ]
  },
  {
   "id": "radio_communications",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 573,
   "bytes": 77157,
   "columnCount": 6,
   "columns": [
    {
     "name": "emergency_keyword_flag",
     "type": "BOOL"
    },
    {
     "name": "audio_gcs_path",
     "type": "STRING"
    },
    {
     "name": "sentiment_score",
     "type": "FLOAT64"
    },
    {
     "name": "channel_id",
     "type": "STRING"
    },
    {
     "name": "transcript",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    }
   ],
   "weight": 2.766,
   "readBy": []
  },
  {
   "id": "rail_schedules",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 120,
   "bytes": 11220,
   "columnCount": 10,
   "columns": [
    {
     "name": "consist_id",
     "type": "STRING"
    },
    {
     "name": "origin_stockpile_id",
     "type": "STRING"
    },
    {
     "name": "origin_location",
     "type": "STRING"
    },
    {
     "name": "destination_port",
     "type": "STRING"
    },
    {
     "name": "departure_date",
     "type": "DATE"
    },
    {
     "name": "arrival_date",
     "type": "DATE"
    },
    {
     "name": "wagons",
     "type": "INT64"
    },
    {
     "name": "payload_tonnes",
     "type": "FLOAT64"
    },
    {
     "name": "cycle_time_hours",
     "type": "FLOAT64"
    },
    {
     "name": "delayed",
     "type": "BOOL"
    }
   ],
   "weight": 2.114,
   "readBy": [
    "D35",
    "S12-1-RAIL",
    "S12-COORDINATOR"
   ]
  },
  {
   "id": "reagent_inventory",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 10,
   "bytes": 840,
   "columnCount": 7,
   "columns": [
    {
     "name": "part_number",
     "type": "STRING"
    },
    {
     "name": "part_description",
     "type": "STRING"
    },
    {
     "name": "stock_level",
     "type": "INT64"
    },
    {
     "name": "reorder_point_limit",
     "type": "INT64"
    },
    {
     "name": "lead_time_days",
     "type": "INT64"
    },
    {
     "name": "unit_price_usd",
     "type": "FLOAT64"
    },
    {
     "name": "reagent_class",
     "type": "STRING"
    }
   ],
   "weight": 1.301,
   "readBy": [
    "D19",
    "D34",
    "S07-1-REAGENT"
   ]
  },
  {
   "id": "rebate_claims",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 6,
   "bytes": 270,
   "columnCount": 5,
   "columns": [
    {
     "name": "claim_id",
     "type": "STRING"
    },
    {
     "name": "contract_id",
     "type": "STRING"
    },
    {
     "name": "period",
     "type": "STRING"
    },
    {
     "name": "amount_claimed",
     "type": "FLOAT64"
    },
    {
     "name": "amount_entitled",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.204,
   "readBy": []
  },
  {
   "id": "rfp_items",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 3,
   "bytes": 99,
   "columnCount": 2,
   "columns": [
    {
     "name": "rfp_id",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    }
   ],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "safety_incidents",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 60,
   "bytes": 12501,
   "columnCount": 8,
   "columns": [
    {
     "name": "investigation_status",
     "type": "STRING"
    },
    {
     "name": "root_cause",
     "type": "STRING"
    },
    {
     "name": "description",
     "type": "STRING"
    },
    {
     "name": "gps_location",
     "type": "STRING"
    },
    {
     "name": "location_description",
     "type": "STRING"
    },
    {
     "name": "severity_level",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "incident_id",
     "type": "STRING"
    }
   ],
   "weight": 1.845,
   "readBy": []
  },
  {
   "id": "safety_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 5,
   "bytes": 10188,
   "columnCount": 0,
   "columns": [],
   "weight": 1.176,
   "readBy": []
  },
  {
   "id": "safety_permits",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 6,
   "columns": [
    {
     "name": "permit_reference",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "location_description",
     "type": "STRING"
    },
    {
     "name": "severity_level",
     "type": "STRING"
    },
    {
     "name": "investigation_status",
     "type": "STRING"
    },
    {
     "name": "cleared",
     "type": "BOOL"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "D40",
    "S03-R-CRITIC",
    "S08-R-CRITIC"
   ]
  },
  {
   "id": "safety_telemetry",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 6,
   "columns": [
    {
     "name": "incident_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "gps_location",
     "type": "STRING"
    },
    {
     "name": "location_description",
     "type": "STRING"
    },
    {
     "name": "severity_level",
     "type": "STRING"
    },
    {
     "name": "investigation_status",
     "type": "STRING"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "D38",
    "S04-R-CRITIC"
   ]
  },
  {
   "id": "simulation_runs",
   "layer": "simulation",
   "layerLabel": "Scenario & simulation",
   "domain": "planning",
   "domainLabel": "Planning & strategy",
   "rows": 150,
   "bytes": 37234,
   "columnCount": 6,
   "columns": [
    {
     "name": "projected_cooling_curve",
     "type": "STRING"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "recalculated_parameters",
     "type": "STRING"
    },
    {
     "name": "nba_executed",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "run_id",
     "type": "STRING"
    }
   ],
   "weight": 2.204,
   "readBy": []
  },
  {
   "id": "spares_inventory",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 9,
   "columns": [
    {
     "name": "part_number",
     "type": "STRING"
    },
    {
     "name": "part_description",
     "type": "STRING"
    },
    {
     "name": "stock_level",
     "type": "INT64"
    },
    {
     "name": "reorder_point_limit",
     "type": "INT64"
    },
    {
     "name": "lead_time_days",
     "type": "INT64"
    },
    {
     "name": "unit_price_usd",
     "type": "FLOAT64"
    },
    {
     "name": "stock_value_usd",
     "type": "FLOAT64"
    },
    {
     "name": "units_above_reorder",
     "type": "INT64"
    },
    {
     "name": "at_or_below_reorder",
     "type": "BOOL"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "D29",
    "D32",
    "S11-1-STOCK",
    "S11-3-HOLDING",
    "S11-COORDINATOR",
    "S11-R-CRITIC"
   ]
  },
  {
   "id": "stockpiles",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 60,
   "bytes": 4543,
   "columnCount": 8,
   "columns": [
    {
     "name": "stockpile_id",
     "type": "STRING"
    },
    {
     "name": "location",
     "type": "STRING"
    },
    {
     "name": "as_at",
     "type": "DATE"
    },
    {
     "name": "material_class",
     "type": "STRING"
    },
    {
     "name": "tonnes",
     "type": "FLOAT64"
    },
    {
     "name": "contained_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "moisture_pct",
     "type": "FLOAT64"
    },
    {
     "name": "reclaim_rate_tph",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.845,
   "readBy": [
    "S12-2-BLEND",
    "S12-COORDINATOR",
    "S12-R-CRITIC"
   ]
  },
  {
   "id": "survey_scans",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 120,
   "bytes": 11547,
   "columnCount": 10,
   "columns": [
    {
     "name": "scan_id",
     "type": "STRING"
    },
    {
     "name": "block_id",
     "type": "STRING"
    },
    {
     "name": "scan_date",
     "type": "DATE"
    },
    {
     "name": "scanner_type",
     "type": "STRING"
    },
    {
     "name": "point_count",
     "type": "INT64"
    },
    {
     "name": "designed_volume_m3",
     "type": "FLOAT64"
    },
    {
     "name": "measured_volume_m3",
     "type": "FLOAT64"
    },
    {
     "name": "centroid_x",
     "type": "FLOAT64"
    },
    {
     "name": "centroid_y",
     "type": "FLOAT64"
    },
    {
     "name": "centroid_z",
     "type": "FLOAT64"
    }
   ],
   "weight": 2.114,
   "readBy": [
    "S02-R-CRITIC"
   ]
  },
  {
   "id": "telemetry_alarm_risk_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 7,
   "bytes": 54291,
   "columnCount": 0,
   "columns": [],
   "weight": 1.23,
   "readBy": []
  },
  {
   "id": "telemetry_stream",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "fleet",
   "domainLabel": "Mobile fleet & haulage",
   "rows": 25946,
   "bytes": 1089720,
   "columnCount": 4,
   "columns": [
    {
     "name": "metric_name",
     "type": "STRING"
    },
    {
     "name": "metric_value",
     "type": "FLOAT64"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    }
   ],
   "weight": 4.414,
   "readBy": []
  },
  {
   "id": "tenement_leases",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 6,
   "bytes": 718,
   "columnCount": 11,
   "columns": [
    {
     "name": "tenement_id",
     "type": "STRING"
    },
    {
     "name": "holder",
     "type": "STRING"
    },
    {
     "name": "status",
     "type": "STRING"
    },
    {
     "name": "grant_date",
     "type": "DATE"
    },
    {
     "name": "expiry_date",
     "type": "DATE"
    },
    {
     "name": "area_hectares",
     "type": "FLOAT64"
    },
    {
     "name": "min_x",
     "type": "FLOAT64"
    },
    {
     "name": "max_x",
     "type": "FLOAT64"
    },
    {
     "name": "min_y",
     "type": "FLOAT64"
    },
    {
     "name": "max_y",
     "type": "FLOAT64"
    },
    {
     "name": "annual_rent_usd",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.204,
   "readBy": [
    "D40"
   ]
  },
  {
   "id": "text_embedding_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 1,
   "bytes": 99,
   "columnCount": 0,
   "columns": [],
   "weight": 1.041,
   "readBy": []
  },
  {
   "id": "tsf_piezometers",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 200,
   "bytes": 15600,
   "columnCount": 8,
   "columns": [
    {
     "name": "reading_id",
     "type": "STRING"
    },
    {
     "name": "piezometer_id",
     "type": "STRING"
    },
    {
     "name": "tsf_location",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "pore_pressure_kpa",
     "type": "FLOAT64"
    },
    {
     "name": "phreatic_surface_m",
     "type": "FLOAT64"
    },
    {
     "name": "factor_of_safety",
     "type": "FLOAT64"
    },
    {
     "name": "beach_width_m",
     "type": "FLOAT64"
    }
   ],
   "weight": 2.322,
   "readBy": [
    "D21",
    "S08-2-PORE",
    "S08-COORDINATOR",
    "S08-R-CRITIC"
   ]
  },
  {
   "id": "unstructured_docs_metadata",
   "layer": "corpus",
   "layerLabel": "Unstructured corpus",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 60,
   "bytes": 8242,
   "columnCount": 6,
   "columns": [
    {
     "name": "chunk_count",
     "type": "INT64"
    },
    {
     "name": "last_updated",
     "type": "TIMESTAMP"
    },
    {
     "name": "category",
     "type": "STRING"
    },
    {
     "name": "file_path",
     "type": "STRING"
    },
    {
     "name": "title",
     "type": "STRING"
    },
    {
     "name": "doc_id",
     "type": "STRING"
    }
   ],
   "weight": 1.845,
   "readBy": []
  },
  {
   "id": "v_fatigue_scored",
   "layer": "serving",
   "layerLabel": "Serving views",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 0,
   "bytes": 0,
   "columnCount": 3,
   "columns": [
    {
     "name": "operator_id",
     "type": "STRING"
    },
    {
     "name": "log_date",
     "type": "DATE"
    },
    {
     "name": "fatigue_band",
     "type": "STRING"
    }
   ],
   "weight": 1.0,
   "readBy": []
  },
  {
   "id": "vendor_contracts",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 12,
   "columns": [
    {
     "name": "contract_id",
     "type": "STRING"
    },
    {
     "name": "vendor_name",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    },
    {
     "name": "agreed_unit_price",
     "type": "FLOAT64"
    },
    {
     "name": "effective_from",
     "type": "DATE"
    },
    {
     "name": "effective_to",
     "type": "DATE"
    },
    {
     "name": "bid_id",
     "type": "STRING"
    },
    {
     "name": "rebate_schedule",
     "type": "STRING"
    },
    {
     "name": "clause_count",
     "type": "INT64"
    },
    {
     "name": "recoverable_clause_count",
     "type": "INT64"
    },
    {
     "name": "doc_id",
     "type": "STRING"
    },
    {
     "name": "source_uri",
     "type": "STRING"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "D27",
    "S10-1-CONTRACT",
    "S10-2-ESCALATE",
    "S10-3-WARRANTY",
    "S10-COORDINATOR",
    "S10-R-CRITIC"
   ]
  },
  {
   "id": "vibration_monitors",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 0,
   "bytes": 0,
   "columnCount": 3,
   "columns": [
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "vibration_hz",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.0,
   "readBy": [
    "S03-3-VIBRATION"
   ]
  },
  {
   "id": "warranty_claims",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 12,
   "bytes": 649,
   "columnCount": 6,
   "columns": [
    {
     "name": "claim_id",
     "type": "STRING"
    },
    {
     "name": "entitlement_id",
     "type": "STRING"
    },
    {
     "name": "work_order_id",
     "type": "STRING"
    },
    {
     "name": "filed_date",
     "type": "DATE"
    },
    {
     "name": "status",
     "type": "STRING"
    },
    {
     "name": "amount_claimed",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.342,
   "readBy": []
  },
  {
   "id": "warranty_entitlements",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 10,
   "bytes": 1086,
   "columnCount": 7,
   "columns": [
    {
     "name": "entitlement_id",
     "type": "STRING"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "oem_vendor",
     "type": "STRING"
    },
    {
     "name": "component",
     "type": "STRING"
    },
    {
     "name": "coverage_start",
     "type": "DATE"
    },
    {
     "name": "coverage_end",
     "type": "DATE"
    },
    {
     "name": "source_clause",
     "type": "STRING"
    }
   ],
   "weight": 1.301,
   "readBy": []
  },
  {
   "id": "water_balance_logs",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 167,
   "bytes": 11189,
   "columnCount": 8,
   "columns": [
    {
     "name": "log_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "concentrator_id",
     "type": "STRING"
    },
    {
     "name": "inflow_m3",
     "type": "FLOAT64"
    },
    {
     "name": "evaporation_m3",
     "type": "FLOAT64"
    },
    {
     "name": "seepage_m3",
     "type": "FLOAT64"
    },
    {
     "name": "process_return_m3",
     "type": "FLOAT64"
    },
    {
     "name": "net_storage_change_m3",
     "type": "FLOAT64"
    }
   ],
   "weight": 2.248,
   "readBy": [
    "D20",
    "S08-1-WATER",
    "S08-COORDINATOR"
   ]
  },
  {
   "id": "work_order_parts_edge",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 186,
   "bytes": 17956,
   "columnCount": 3,
   "columns": [
    {
     "name": "edge_id",
     "type": "STRING"
    },
    {
     "name": "work_order_id",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    }
   ],
   "weight": 2.292,
   "readBy": []
  }
 ],
 "edges": [
  {
   "source": "agent_approvals",
   "target": "agent_catalog",
   "keys": [
    "agent_id"
   ],
   "weight": 1
  },
  {
   "source": "agent_approvals",
   "target": "agent_run_log",
   "keys": [
    "agent_id"
   ],
   "weight": 1
  },
  {
   "source": "agent_catalog",
   "target": "agent_run_log",
   "keys": [
    "agent_id"
   ],
   "weight": 1
  },
  {
   "source": "agent_run_log",
   "target": "simulation_runs",
   "keys": [
    "run_id"
   ],
   "weight": 1
  },
  {
   "source": "assay_logs",
   "target": "drill_assay_logs",
   "keys": [
    "drill_hole_id",
    "geology_code"
   ],
   "weight": 2
  },
  {
   "source": "assay_logs",
   "target": "drill_holes",
   "keys": [
    "drill_hole_id"
   ],
   "weight": 1
  },
  {
   "source": "assay_logs",
   "target": "qaqc_standards",
   "keys": [
    "drill_hole_id",
    "geology_code"
   ],
   "weight": 2
  },
  {
   "source": "assets",
   "target": "crusher_states",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "crusher_telemetry",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "erp_work_orders",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "lube_samples",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "maintenance_logs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "plant_telemetry",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "simulation_runs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "vibration_monitors",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "contract_transactions",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "contracts",
   "keys": [
    "bid_id",
    "part_number"
   ],
   "weight": 2
  },
  {
   "source": "bid_parts_edge",
   "target": "explosives_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "inventory_levels",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "procurement_bids",
   "keys": [
    "bid_id"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "purchase_orders",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "reagent_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "rfp_items",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "spares_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "vendor_contracts",
   "keys": [
    "bid_id",
    "part_number"
   ],
   "weight": 2
  },
  {
   "source": "bid_parts_edge",
   "target": "work_order_parts_edge",
   "keys": [
    "edge_id",
    "part_number"
   ],
   "weight": 2
  },
  {
   "source": "biometric_fatigue_logs",
   "target": "fatigue_logs_node",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "biometric_fatigue_logs",
   "target": "fatigue_monitoring_logs",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "biometric_fatigue_logs",
   "target": "incident_involvements",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "biometric_fatigue_logs",
   "target": "operator_vehicle_assignments",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "biometric_fatigue_logs",
   "target": "operators_node",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "biometric_fatigue_logs",
   "target": "v_fatigue_scored",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "blast_designs",
   "target": "geological_block_models",
   "keys": [
    "block_id"
   ],
   "weight": 1
  },
  {
   "source": "blast_designs",
   "target": "pit_designs",
   "keys": [
    "block_id"
   ],
   "weight": 1
  },
  {
   "source": "blast_designs",
   "target": "survey_scans",
   "keys": [
    "block_id"
   ],
   "weight": 1
  },
  {
   "source": "capital_options",
   "target": "mine_production_schedule",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "capital_options",
   "target": "plan_assumptions",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "capital_options",
   "target": "plan_scenarios",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "capital_options",
   "target": "plan_versions",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "contract_clauses",
   "target": "contract_transactions",
   "keys": [
    "contract_id"
   ],
   "weight": 1
  },
  {
   "source": "contract_clauses",
   "target": "contracts",
   "keys": [
    "contract_id"
   ],
   "weight": 1
  },
  {
   "source": "contract_clauses",
   "target": "doc_chunks",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "contract_clauses",
   "target": "doc_chunks_embedded",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "contract_clauses",
   "target": "purchase_orders",
   "keys": [
    "contract_id"
   ],
   "weight": 1
  },
  {
   "source": "contract_clauses",
   "target": "rebate_claims",
   "keys": [
    "contract_id"
   ],
   "weight": 1
  },
  {
   "source": "contract_clauses",
   "target": "unstructured_docs_metadata",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "contract_clauses",
   "target": "vendor_contracts",
   "keys": [
    "contract_id",
    "doc_id"
   ],
   "weight": 2
  },
  {
   "source": "contract_transactions",
   "target": "contracts",
   "keys": [
    "contract_id",
    "part_number"
   ],
   "weight": 2
  },
  {
   "source": "contract_transactions",
   "target": "explosives_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contract_transactions",
   "target": "inventory_levels",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contract_transactions",
   "target": "purchase_orders",
   "keys": [
    "contract_id",
    "part_number"
   ],
   "weight": 2
  },
  {
   "source": "contract_transactions",
   "target": "reagent_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contract_transactions",
   "target": "rebate_claims",
   "keys": [
    "contract_id"
   ],
   "weight": 1
  },
  {
   "source": "contract_transactions",
   "target": "rfp_items",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contract_transactions",
   "target": "spares_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contract_transactions",
   "target": "vendor_contracts",
   "keys": [
    "contract_id",
    "part_number"
   ],
   "weight": 2
  },
  {
   "source": "contract_transactions",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "explosives_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "inventory_levels",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "procurement_bids",
   "keys": [
    "bid_id"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "purchase_orders",
   "keys": [
    "contract_id",
    "part_number"
   ],
   "weight": 2
  },
  {
   "source": "contracts",
   "target": "reagent_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "rebate_claims",
   "keys": [
    "contract_id"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "rfp_items",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "spares_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "vendor_contracts",
   "keys": [
    "bid_id",
    "contract_id",
    "part_number"
   ],
   "weight": 3
  },
  {
   "source": "contracts",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "crusher_telemetry",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "erp_work_orders",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "lube_samples",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "maintenance_logs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "plant_telemetry",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "simulation_runs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "vibration_monitors",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_telemetry",
   "target": "erp_work_orders",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_telemetry",
   "target": "lube_samples",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_telemetry",
   "target": "maintenance_logs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_telemetry",
   "target": "plant_telemetry",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_telemetry",
   "target": "simulation_runs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_telemetry",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_telemetry",
   "target": "vibration_monitors",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_telemetry",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "dispatch_routes",
   "target": "haul_cycle_log",
   "keys": [
    "route_id"
   ],
   "weight": 1
  },
  {
   "source": "dispatch_routes",
   "target": "haulage_routes",
   "keys": [
    "route_id"
   ],
   "weight": 1
  },
  {
   "source": "doc_chunks",
   "target": "doc_chunks_embedded",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "doc_chunks",
   "target": "unstructured_docs_metadata",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "doc_chunks",
   "target": "vendor_contracts",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "doc_chunks_embedded",
   "target": "unstructured_docs_metadata",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "doc_chunks_embedded",
   "target": "vendor_contracts",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "drill_assay_logs",
   "target": "drill_holes",
   "keys": [
    "drill_hole_id"
   ],
   "weight": 1
  },
  {
   "source": "drill_assay_logs",
   "target": "qaqc_standards",
   "keys": [
    "drill_hole_id",
    "geology_code"
   ],
   "weight": 2
  },
  {
   "source": "drill_holes",
   "target": "qaqc_standards",
   "keys": [
    "drill_hole_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "lube_samples",
   "keys": [
    "asset_id",
    "work_order_id"
   ],
   "weight": 2
  },
  {
   "source": "erp_work_orders",
   "target": "maintenance_logs",
   "keys": [
    "asset_id",
    "work_order_id"
   ],
   "weight": 2
  },
  {
   "source": "erp_work_orders",
   "target": "plant_telemetry",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "simulation_runs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "vibration_monitors",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "warranty_claims",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "work_order_parts_edge",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  },
  {
   "source": "explosives_inventory",
   "target": "inventory_levels",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "explosives_inventory",
   "target": "purchase_orders",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "explosives_inventory",
   "target": "reagent_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "explosives_inventory",
   "target": "rfp_items",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "explosives_inventory",
   "target": "spares_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "explosives_inventory",
   "target": "vendor_contracts",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "explosives_inventory",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_logs_node",
   "target": "fatigue_monitoring_logs",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_logs_node",
   "target": "incident_involvements",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_logs_node",
   "target": "operator_vehicle_assignments",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_logs_node",
   "target": "operators_node",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_logs_node",
   "target": "v_fatigue_scored",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_logs_node",
   "target": "water_balance_logs",
   "keys": [
    "log_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_monitoring_logs",
   "target": "incident_involvements",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_monitoring_logs",
   "target": "operator_vehicle_assignments",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_monitoring_logs",
   "target": "operators_node",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_monitoring_logs",
   "target": "v_fatigue_scored",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fleet_telemetry",
   "target": "fleet_vehicles",
   "keys": [
    "vehicle_id"
   ],
   "weight": 1
  },
  {
   "source": "fleet_telemetry",
   "target": "incident_involvements",
   "keys": [
    "vehicle_id"
   ],
   "weight": 1
  },
  {
   "source": "fleet_telemetry",
   "target": "operator_vehicle_assignments",
   "keys": [
    "vehicle_id"
   ],
   "weight": 1
  },
  {
   "source": "fleet_vehicles",
   "target": "incident_involvements",
   "keys": [
    "vehicle_id"
   ],
   "weight": 1
  },
  {
   "source": "fleet_vehicles",
   "target": "operator_vehicle_assignments",
   "keys": [
    "vehicle_id"
   ],
   "weight": 1
  },
  {
   "source": "flotation_assays",
   "target": "metallurgical_recovery",
   "keys": [
    "concentrator_id"
   ],
   "weight": 1
  },
  {
   "source": "flotation_assays",
   "target": "water_balance_logs",
   "keys": [
    "concentrator_id"
   ],
   "weight": 1
  },
  {
   "source": "geological_block_models",
   "target": "pit_designs",
   "keys": [
    "block_id"
   ],
   "weight": 1
  },
  {
   "source": "geological_block_models",
   "target": "survey_scans",
   "keys": [
    "block_id"
   ],
   "weight": 1
  },
  {
   "source": "geotech_sensors",
   "target": "tsf_piezometers",
   "keys": [
    "reading_id"
   ],
   "weight": 1
  },
  {
   "source": "haul_cycle_log",
   "target": "haulage_routes",
   "keys": [
    "route_id"
   ],
   "weight": 1
  },
  {
   "source": "incident_involvements",
   "target": "operator_vehicle_assignments",
   "keys": [
    "operator_id",
    "vehicle_id"
   ],
   "weight": 2
  },
  {
   "source": "incident_involvements",
   "target": "operators_node",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "incident_involvements",
   "target": "safety_incidents",
   "keys": [
    "incident_id"
   ],
   "weight": 1
  },
  {
   "source": "incident_involvements",
   "target": "safety_telemetry",
   "keys": [
    "incident_id"
   ],
   "weight": 1
  },
  {
   "source": "incident_involvements",
   "target": "v_fatigue_scored",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "inventory_levels",
   "target": "purchase_orders",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "inventory_levels",
   "target": "reagent_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "inventory_levels",
   "target": "rfp_items",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "inventory_levels",
   "target": "spares_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "inventory_levels",
   "target": "vendor_contracts",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "inventory_levels",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "lube_samples",
   "target": "maintenance_logs",
   "keys": [
    "asset_id",
    "work_order_id"
   ],
   "weight": 2
  },
  {
   "source": "lube_samples",
   "target": "plant_telemetry",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "lube_samples",
   "target": "simulation_runs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "lube_samples",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "lube_samples",
   "target": "vibration_monitors",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "lube_samples",
   "target": "warranty_claims",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  },
  {
   "source": "lube_samples",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "lube_samples",
   "target": "work_order_parts_edge",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "plant_telemetry",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "simulation_runs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "vibration_monitors",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "warranty_claims",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "work_order_parts_edge",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  },
  {
   "source": "metallurgical_recovery",
   "target": "water_balance_logs",
   "keys": [
    "concentrator_id"
   ],
   "weight": 1
  },
  {
   "source": "mine_production_schedule",
   "target": "plan_assumptions",
   "keys": [
    "assumption_id",
    "plan_version_id"
   ],
   "weight": 2
  },
  {
   "source": "mine_production_schedule",
   "target": "plan_scenarios",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "mine_production_schedule",
   "target": "plan_versions",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "operator_vehicle_assignments",
   "target": "operators_node",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "operator_vehicle_assignments",
   "target": "v_fatigue_scored",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "operators_node",
   "target": "v_fatigue_scored",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "pit_designs",
   "target": "survey_scans",
   "keys": [
    "block_id"
   ],
   "weight": 1
  },
  {
   "source": "plan_assumptions",
   "target": "plan_scenarios",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "plan_assumptions",
   "target": "plan_versions",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "plan_scenarios",
   "target": "plan_versions",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "plant_telemetry",
   "target": "simulation_runs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "plant_telemetry",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "plant_telemetry",
   "target": "vibration_monitors",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "plant_telemetry",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "procurement_bids",
   "target": "rfp_items",
   "keys": [
    "rfp_id"
   ],
   "weight": 1
  },
  {
   "source": "procurement_bids",
   "target": "vendor_contracts",
   "keys": [
    "bid_id"
   ],
   "weight": 1
  },
  {
   "source": "purchase_orders",
   "target": "reagent_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "purchase_orders",
   "target": "rebate_claims",
   "keys": [
    "contract_id"
   ],
   "weight": 1
  },
  {
   "source": "purchase_orders",
   "target": "rfp_items",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "purchase_orders",
   "target": "spares_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "purchase_orders",
   "target": "vendor_contracts",
   "keys": [
    "contract_id",
    "part_number"
   ],
   "weight": 2
  },
  {
   "source": "purchase_orders",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "reagent_inventory",
   "target": "rfp_items",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "reagent_inventory",
   "target": "spares_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "reagent_inventory",
   "target": "vendor_contracts",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "reagent_inventory",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "rebate_claims",
   "target": "vendor_contracts",
   "keys": [
    "contract_id"
   ],
   "weight": 1
  },
  {
   "source": "rebate_claims",
   "target": "warranty_claims",
   "keys": [
    "claim_id"
   ],
   "weight": 1
  },
  {
   "source": "rfp_items",
   "target": "spares_inventory",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "rfp_items",
   "target": "vendor_contracts",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "rfp_items",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "safety_incidents",
   "target": "safety_telemetry",
   "keys": [
    "incident_id"
   ],
   "weight": 1
  },
  {
   "source": "simulation_runs",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "simulation_runs",
   "target": "vibration_monitors",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "simulation_runs",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "spares_inventory",
   "target": "vendor_contracts",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "spares_inventory",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "telemetry_stream",
   "target": "vibration_monitors",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "telemetry_stream",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "unstructured_docs_metadata",
   "target": "vendor_contracts",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "vendor_contracts",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "vibration_monitors",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "warranty_claims",
   "target": "warranty_entitlements",
   "keys": [
    "entitlement_id"
   ],
   "weight": 1
  },
  {
   "source": "warranty_claims",
   "target": "work_order_parts_edge",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  }
 ],
 "layers": [
  {
   "key": "model",
   "label": "BQML models"
  },
  {
   "key": "control",
   "label": "Agent control plane"
  },
  {
   "key": "corpus",
   "label": "Unstructured corpus"
  },
  {
   "key": "semantic",
   "label": "Semantic / property graph"
  },
  {
   "key": "serving",
   "label": "Serving views"
  },
  {
   "key": "simulation",
   "label": "Scenario & simulation"
  },
  {
   "key": "operational",
   "label": "Operational records"
  }
 ],
 "domains": [
  {
   "key": "geology",
   "label": "Geology & resource"
  },
  {
   "key": "plant",
   "label": "Processing plant"
  },
  {
   "key": "fleet",
   "label": "Mobile fleet & haulage"
  },
  {
   "key": "hse",
   "label": "Health, safety & people"
  },
  {
   "key": "maintenance",
   "label": "Asset & maintenance"
  },
  {
   "key": "commercial",
   "label": "Commercial & procurement"
  },
  {
   "key": "planning",
   "label": "Planning & strategy"
  },
  {
   "key": "platform",
   "label": "Platform & ontology"
  }
 ],
 "meta": {
  "project": "genial-union-475913-i7",
  "dataset": "mining_data",
  "tableCount": 85,
  "edgeCount": 204,
  "columnCount": 511,
  "rowCount": 44297,
  "excludedCount": 12,
  "excluded": [
   "__mutation_probe",
   "biometric_fatigue_logs_original_20260810",
   "crusher_states_original_20260810",
   "drill_assay_logs_original_20260810",
   "erp_work_orders_original_20260810",
   "fatigue_logs_node_original_20260810",
   "geological_block_models_original_20260810",
   "inventory_levels_original_20260810",
   "maintenance_logs_original_20260810",
   "maintenance_logs_task10_probe",
   "metallurgical_recovery_original_20260810",
   "telemetry_stream_original_20260810"
  ],
  "genericKeysDropped": []
 }
};
