/* GENERATED by scripts/build_data_graph.py -- do not edit by hand.
 * Source: live `genial-union-475913-i7.mining_data` -- table storage and INFORMATION_SCHEMA.COLUMNS.
 * Layer and domain are classifications declared in the generator; every
 * other field is read straight from BigQuery. */
window.dataGraph = {
 "nodes": [
  {
   "id": "agent_approvals",
   "layer": "control",
   "layerLabel": "Agent control plane",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 704,
   "bytes": 141813,
   "columnCount": 11,
   "columns": [
    {
     "name": "approval_id",
     "type": "STRING"
    },
    {
     "name": "agent_id",
     "type": "STRING"
    },
    {
     "name": "action_type",
     "type": "STRING"
    },
    {
     "name": "target_entity",
     "type": "STRING"
    },
    {
     "name": "decision",
     "type": "STRING"
    },
    {
     "name": "approver_principal",
     "type": "STRING"
    },
    {
     "name": "decided_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "hold_duration_ms",
     "type": "INT64"
    },
    {
     "name": "agent_reasoning_snapshot",
     "type": "STRING"
    },
    {
     "name": "unverified_flags",
     "type": "ARRAY<STRING>"
    },
    {
     "name": "source_tables",
     "type": "ARRAY<STRING>"
    }
   ],
   "weight": 2.854,
   "readBy": []
  },
  {
   "id": "agent_catalog",
   "layer": "control",
   "layerLabel": "Agent control plane",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 100,
   "bytes": 15898,
   "columnCount": 11,
   "columns": [
    {
     "name": "agent_id",
     "type": "STRING"
    },
    {
     "name": "display_name",
     "type": "STRING"
    },
    {
     "name": "pattern",
     "type": "STRING"
    },
    {
     "name": "swarm_id",
     "type": "STRING"
    },
    {
     "name": "swarm_role",
     "type": "STRING"
    },
    {
     "name": "apqc_code",
     "type": "STRING"
    },
    {
     "name": "persona",
     "type": "STRING"
    },
    {
     "name": "value_branch",
     "type": "STRING"
    },
    {
     "name": "model_tier",
     "type": "STRING"
    },
    {
     "name": "hitl_required",
     "type": "BOOL"
    },
    {
     "name": "source_tables",
     "type": "ARRAY<STRING>"
    }
   ],
   "weight": 2.041,
   "readBy": []
  },
  {
   "id": "agent_run_log",
   "layer": "control",
   "layerLabel": "Agent control plane",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 855,
   "bytes": 104215,
   "columnCount": 10,
   "columns": [
    {
     "name": "run_id",
     "type": "STRING"
    },
    {
     "name": "agent_id",
     "type": "STRING"
    },
    {
     "name": "parent_run_id",
     "type": "STRING"
    },
    {
     "name": "pattern",
     "type": "STRING"
    },
    {
     "name": "status",
     "type": "STRING"
    },
    {
     "name": "blocked_reason",
     "type": "STRING"
    },
    {
     "name": "started_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "ended_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "tables_read",
     "type": "ARRAY<STRING>"
    },
    {
     "name": "rows_scanned",
     "type": "INT64"
    }
   ],
   "weight": 2.937,
   "readBy": []
  },
  {
   "id": "asset_clustering_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 8,
   "bytes": 14796,
   "columnCount": 0,
   "columns": [],
   "weight": 1.255,
   "readBy": []
  },
  {
   "id": "asset_dependencies",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 3,
   "bytes": 135,
   "columnCount": 4,
   "columns": [
    {
     "name": "impact_score",
     "type": "FLOAT64"
    },
    {
     "name": "dependency_type",
     "type": "STRING"
    },
    {
     "name": "target_id",
     "type": "STRING"
    },
    {
     "name": "source_id",
     "type": "STRING"
    }
   ],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "assets",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 5,
   "bytes": 1213,
   "columnCount": 8,
   "columns": [
    {
     "name": "current_state",
     "type": "STRING"
    },
    {
     "name": "location_gis",
     "type": "STRING"
    },
    {
     "name": "physics_parameters",
     "type": "STRING"
    },
    {
     "name": "criticality_rating",
     "type": "STRING"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "installation_date",
     "type": "DATE"
    },
    {
     "name": "asset_type",
     "type": "STRING"
    },
    {
     "name": "asset_name",
     "type": "STRING"
    }
   ],
   "weight": 1.176,
   "readBy": [
    "D22",
    "D23",
    "D24",
    "D25",
    "D30",
    "S05-3-WEAR",
    "S05-COORDINATOR",
    "S06-COORDINATOR",
    "S09-1-VIBRATION",
    "S09-2-TRIBOLOGY",
    "S09-3-THERMAL",
    "S09-COORDINATOR",
    "S09-R-CRITIC",
    "S10-3-WARRANTY"
   ]
  },
  {
   "id": "bid_parts_edge",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 25,
   "bytes": 2402,
   "columnCount": 3,
   "columns": [
    {
     "name": "edge_id",
     "type": "STRING"
    },
    {
     "name": "bid_id",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    }
   ],
   "weight": 1.544,
   "readBy": []
  },
  {
   "id": "biometric_fatigue_logs",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 3340,
   "bytes": 136940,
   "columnCount": 6,
   "columns": [
    {
     "name": "sleep_deficit_hours",
     "type": "FLOAT64"
    },
    {
     "name": "microsleep_events_detected",
     "type": "INT64"
    },
    {
     "name": "fatigue_alert_triggered",
     "type": "BOOL"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "heart_rate_bpm",
     "type": "INT64"
    },
    {
     "name": "operator_id",
     "type": "STRING"
    }
   ],
   "weight": 3.525,
   "readBy": []
  },
  {
   "id": "capital_options",
   "layer": "simulation",
   "layerLabel": "Scenario & simulation",
   "domain": "planning",
   "domainLabel": "Planning & strategy",
   "rows": 24,
   "bytes": 3476,
   "columnCount": 3,
   "columns": [
    {
     "name": "option_id",
     "type": "STRING"
    },
    {
     "name": "plan_version_id",
     "type": "STRING"
    },
    {
     "name": "description",
     "type": "STRING"
    }
   ],
   "weight": 1.531,
   "readBy": []
  },
  {
   "id": "contained_metal_price_deck",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 61,
   "bytes": 976,
   "columnCount": 2,
   "columns": [
    {
     "name": "price_date",
     "type": "DATE"
    },
    {
     "name": "contained_metal_price_usd_per_tonne",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.851,
   "readBy": []
  },
  {
   "id": "contract_transactions",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 164,
   "bytes": 11804,
   "columnCount": 6,
   "columns": [
    {
     "name": "transaction_id",
     "type": "STRING"
    },
    {
     "name": "contract_id",
     "type": "STRING"
    },
    {
     "name": "vendor_name",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    },
    {
     "name": "paid_unit_price",
     "type": "FLOAT64"
    },
    {
     "name": "transaction_date",
     "type": "DATE"
    }
   ],
   "weight": 2.241,
   "readBy": []
  },
  {
   "id": "contracts",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 10,
   "bytes": 1987,
   "columnCount": 8,
   "columns": [
    {
     "name": "contract_id",
     "type": "STRING"
    },
    {
     "name": "vendor_name",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    },
    {
     "name": "agreed_unit_price",
     "type": "FLOAT64"
    },
    {
     "name": "effective_from",
     "type": "DATE"
    },
    {
     "name": "effective_to",
     "type": "DATE"
    },
    {
     "name": "bid_id",
     "type": "STRING"
    },
    {
     "name": "rebate_schedule",
     "type": "STRING"
    }
   ],
   "weight": 1.301,
   "readBy": []
  },
  {
   "id": "crusher_states",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "plant",
   "domainLabel": "Processing plant",
   "rows": 167,
   "bytes": 7515,
   "columnCount": 6,
   "columns": [
    {
     "name": "bypass_valve_open",
     "type": "BOOL"
    },
    {
     "name": "feed_rate_tph",
     "type": "FLOAT64"
    },
    {
     "name": "gap_size_setting_mm",
     "type": "FLOAT64"
    },
    {
     "name": "rotational_torque_nm",
     "type": "FLOAT64"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    }
   ],
   "weight": 2.248,
   "readBy": []
  },
  {
   "id": "doc_chunks",
   "layer": "corpus",
   "layerLabel": "Unstructured corpus",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 78,
   "bytes": 64057,
   "columnCount": 5,
   "columns": [
    {
     "name": "doc_id",
     "type": "STRING"
    },
    {
     "name": "folder",
     "type": "STRING"
    },
    {
     "name": "file_name",
     "type": "STRING"
    },
    {
     "name": "chunk_index",
     "type": "INT64"
    },
    {
     "name": "chunk_text",
     "type": "STRING"
    }
   ],
   "weight": 1.944,
   "readBy": []
  },
  {
   "id": "doc_chunks_embedded",
   "layer": "corpus",
   "layerLabel": "Unstructured corpus",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 78,
   "bytes": 544147,
   "columnCount": 8,
   "columns": [
    {
     "name": "ml_generate_embedding_result",
     "type": "ARRAY<FLOAT64>"
    },
    {
     "name": "ml_generate_embedding_statistics",
     "type": "JSON"
    },
    {
     "name": "ml_generate_embedding_status",
     "type": "STRING"
    },
    {
     "name": "doc_id",
     "type": "STRING"
    },
    {
     "name": "folder",
     "type": "STRING"
    },
    {
     "name": "file_name",
     "type": "STRING"
    },
    {
     "name": "chunk_index",
     "type": "INT64"
    },
    {
     "name": "chunk_text",
     "type": "STRING"
    }
   ],
   "weight": 1.944,
   "readBy": []
  },
  {
   "id": "downtime_regression_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 3,
   "bytes": 18109,
   "columnCount": 0,
   "columns": [],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "drill_assay_logs",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "geology",
   "domainLabel": "Geology & resource",
   "rows": 295,
   "bytes": 17890,
   "columnCount": 7,
   "columns": [
    {
     "name": "logged_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "gold_grade_gpt",
     "type": "FLOAT64"
    },
    {
     "name": "depth_end_meters",
     "type": "FLOAT64"
    },
    {
     "name": "depth_start_meters",
     "type": "FLOAT64"
    },
    {
     "name": "copper_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "geology_code",
     "type": "STRING"
    },
    {
     "name": "drill_hole_id",
     "type": "STRING"
    }
   ],
   "weight": 2.484,
   "readBy": []
  },
  {
   "id": "drill_holes",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "geology",
   "domainLabel": "Geology & resource",
   "rows": 30,
   "bytes": 1800,
   "columnCount": 7,
   "columns": [
    {
     "name": "azimuth_degrees",
     "type": "FLOAT64"
    },
    {
     "name": "dip_degrees",
     "type": "FLOAT64"
    },
    {
     "name": "total_depth_meters",
     "type": "FLOAT64"
    },
    {
     "name": "collar_elevation",
     "type": "FLOAT64"
    },
    {
     "name": "collar_easting",
     "type": "FLOAT64"
    },
    {
     "name": "collar_northing",
     "type": "FLOAT64"
    },
    {
     "name": "drill_hole_id",
     "type": "STRING"
    }
   ],
   "weight": 1.602,
   "readBy": [
    "D01",
    "D02",
    "D03",
    "S01-1-LITHOLOGY",
    "S01-COORDINATOR"
   ]
  },
  {
   "id": "erp_work_orders",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 500,
   "bytes": 51117,
   "columnCount": 7,
   "columns": [
    {
     "name": "created_at",
     "type": "TIMESTAMP"
    },
    {
     "name": "repair_cost",
     "type": "FLOAT64"
    },
    {
     "name": "description",
     "type": "STRING"
    },
    {
     "name": "work_order_id",
     "type": "STRING"
    },
    {
     "name": "priority",
     "type": "STRING"
    },
    {
     "name": "status",
     "type": "STRING"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    }
   ],
   "weight": 2.708,
   "readBy": [
    "D26",
    "S09-COORDINATOR",
    "S09-R-CRITIC"
   ]
  },
  {
   "id": "fatigue_logs_node",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 3340,
   "bytes": 357380,
   "columnCount": 7,
   "columns": [
    {
     "name": "log_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "operator_id",
     "type": "STRING"
    },
    {
     "name": "heart_rate_bpm",
     "type": "INT64"
    },
    {
     "name": "sleep_deficit_hours",
     "type": "FLOAT64"
    },
    {
     "name": "microsleep_events_detected",
     "type": "INT64"
    },
    {
     "name": "fatigue_alert_triggered",
     "type": "BOOL"
    }
   ],
   "weight": 3.525,
   "readBy": []
  },
  {
   "id": "fleet_vehicles",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "fleet",
   "domainLabel": "Mobile fleet & haulage",
   "rows": 15,
   "bytes": 1639,
   "columnCount": 7,
   "columns": [
    {
     "name": "gps_location",
     "type": "STRING"
    },
    {
     "name": "current_payload_tons",
     "type": "FLOAT64"
    },
    {
     "name": "operational_status",
     "type": "STRING"
    },
    {
     "name": "last_telemetry_sync",
     "type": "TIMESTAMP"
    },
    {
     "name": "payload_capacity_tons",
     "type": "FLOAT64"
    },
    {
     "name": "model",
     "type": "STRING"
    },
    {
     "name": "vehicle_id",
     "type": "STRING"
    }
   ],
   "weight": 1.398,
   "readBy": []
  },
  {
   "id": "geological_block_models",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "geology",
   "domainLabel": "Geology & resource",
   "rows": 1000,
   "bytes": 72939,
   "columnCount": 8,
   "columns": [
    {
     "name": "gold_grade_gpt_est",
     "type": "FLOAT64"
    },
    {
     "name": "copper_grade_pct_est",
     "type": "FLOAT64"
    },
    {
     "name": "specific_gravity",
     "type": "FLOAT64"
    },
    {
     "name": "lithology_type",
     "type": "STRING"
    },
    {
     "name": "centroid_z",
     "type": "FLOAT64"
    },
    {
     "name": "centroid_y",
     "type": "FLOAT64"
    },
    {
     "name": "centroid_x",
     "type": "FLOAT64"
    },
    {
     "name": "block_id",
     "type": "STRING"
    }
   ],
   "weight": 3.004,
   "readBy": [
    "AGT-19",
    "D03",
    "S01-3-STRUCTURAL",
    "S01-COORDINATOR"
   ]
  },
  {
   "id": "haul_cycle_log",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "fleet",
   "domainLabel": "Mobile fleet & haulage",
   "rows": 3340,
   "bytes": 193720,
   "columnCount": 7,
   "columns": [
    {
     "name": "route_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "trip_count",
     "type": "INT64"
    },
    {
     "name": "mean_cycle_time_mins",
     "type": "FLOAT64"
    },
    {
     "name": "mean_queue_wait_mins",
     "type": "FLOAT64"
    },
    {
     "name": "mean_payload_tons",
     "type": "FLOAT64"
    },
    {
     "name": "congestion_index",
     "type": "FLOAT64"
    }
   ],
   "weight": 3.525,
   "readBy": []
  },
  {
   "id": "haulage_routes",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "fleet",
   "domainLabel": "Mobile fleet & haulage",
   "rows": 10,
   "bytes": 691,
   "columnCount": 6,
   "columns": [
    {
     "name": "average_cycle_time_mins",
     "type": "FLOAT64"
    },
    {
     "name": "source_location",
     "type": "STRING"
    },
    {
     "name": "congestion_factor",
     "type": "FLOAT64"
    },
    {
     "name": "distance_meters",
     "type": "FLOAT64"
    },
    {
     "name": "destination_location",
     "type": "STRING"
    },
    {
     "name": "route_id",
     "type": "STRING"
    }
   ],
   "weight": 1.301,
   "readBy": []
  },
  {
   "id": "incident_involvements",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 5,
   "bytes": 205,
   "columnCount": 4,
   "columns": [
    {
     "name": "involvement_id",
     "type": "STRING"
    },
    {
     "name": "incident_id",
     "type": "STRING"
    },
    {
     "name": "vehicle_id",
     "type": "STRING"
    },
    {
     "name": "operator_id",
     "type": "STRING"
    }
   ],
   "weight": 1.176,
   "readBy": []
  },
  {
   "id": "inventory_impact_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 4,
   "bytes": 27161,
   "columnCount": 0,
   "columns": [],
   "weight": 1.146,
   "readBy": []
  },
  {
   "id": "inventory_impact_model_crusher",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 3,
   "bytes": 10101,
   "columnCount": 0,
   "columns": [],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "inventory_impact_model_mill",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 3,
   "bytes": 10101,
   "columnCount": 0,
   "columns": [],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "inventory_impact_model_pump",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 3,
   "bytes": 10101,
   "columnCount": 0,
   "columns": [],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "inventory_levels",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "plant",
   "domainLabel": "Processing plant",
   "rows": 105,
   "bytes": 9772,
   "columnCount": 6,
   "columns": [
    {
     "name": "lead_time_days",
     "type": "INT64"
    },
    {
     "name": "part_description",
     "type": "STRING"
    },
    {
     "name": "reorder_point_limit",
     "type": "INT64"
    },
    {
     "name": "stock_level",
     "type": "INT64"
    },
    {
     "name": "unit_price_usd",
     "type": "FLOAT64"
    },
    {
     "name": "part_number",
     "type": "STRING"
    }
   ],
   "weight": 2.061,
   "readBy": []
  },
  {
   "id": "invoices",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 175,
   "bytes": 11641,
   "columnCount": 5,
   "columns": [
    {
     "name": "invoice_id",
     "type": "STRING"
    },
    {
     "name": "vendor_name",
     "type": "STRING"
    },
    {
     "name": "invoice_number",
     "type": "STRING"
    },
    {
     "name": "amount",
     "type": "FLOAT64"
    },
    {
     "name": "payment_date",
     "type": "DATE"
    }
   ],
   "weight": 2.267,
   "readBy": [
    "D31",
    "S10-COORDINATOR",
    "S10-R-CRITIC"
   ]
  },
  {
   "id": "maintenance_logs",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 152,
   "bytes": 24566,
   "columnCount": 6,
   "columns": [
    {
     "name": "parts_replaced",
     "type": "ARRAY<STRING>"
    },
    {
     "name": "log_entry_id",
     "type": "STRING"
    },
    {
     "name": "actual_duration_hours",
     "type": "FLOAT64"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "technician_notes",
     "type": "STRING"
    },
    {
     "name": "work_order_id",
     "type": "STRING"
    }
   ],
   "weight": 2.21,
   "readBy": []
  },
  {
   "id": "metallurgical_recovery",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "plant",
   "domainLabel": "Processing plant",
   "rows": 167,
   "bytes": 8183,
   "columnCount": 6,
   "columns": [
    {
     "name": "concentrate_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "recovery_rate_pct",
     "type": "FLOAT64"
    },
    {
     "name": "tailings_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "feed_grade_pct",
     "type": "FLOAT64"
    },
    {
     "name": "concentrator_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    }
   ],
   "weight": 2.248,
   "readBy": []
  },
  {
   "id": "ontology_concepts",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 25,
   "bytes": 448,
   "columnCount": 2,
   "columns": [
    {
     "name": "concept_name",
     "type": "STRING"
    },
    {
     "name": "concept_type",
     "type": "STRING"
    }
   ],
   "weight": 1.544,
   "readBy": []
  },
  {
   "id": "ontology_triples",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 23,
   "bytes": 1335,
   "columnCount": 5,
   "columns": [
    {
     "name": "object",
     "type": "STRING"
    },
    {
     "name": "subject",
     "type": "STRING"
    },
    {
     "name": "confidence_score",
     "type": "FLOAT64"
    },
    {
     "name": "predicate",
     "type": "STRING"
    },
    {
     "name": "triple_id",
     "type": "STRING"
    }
   ],
   "weight": 1.519,
   "readBy": []
  },
  {
   "id": "operator_vehicle_assignments",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "fleet",
   "domainLabel": "Mobile fleet & haulage",
   "rows": 5,
   "bytes": 209,
   "columnCount": 5,
   "columns": [
    {
     "name": "assignment_id",
     "type": "STRING"
    },
    {
     "name": "operator_id",
     "type": "STRING"
    },
    {
     "name": "vehicle_id",
     "type": "STRING"
    },
    {
     "name": "shift_date",
     "type": "DATE"
    },
    {
     "name": "shift_type",
     "type": "STRING"
    }
   ],
   "weight": 1.176,
   "readBy": []
  },
  {
   "id": "operators_node",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 20,
   "bytes": 680,
   "columnCount": 2,
   "columns": [
    {
     "name": "operator_id",
     "type": "STRING"
    },
    {
     "name": "operator_role",
     "type": "STRING"
    }
   ],
   "weight": 1.477,
   "readBy": []
  },
  {
   "id": "plan_assumptions",
   "layer": "simulation",
   "layerLabel": "Scenario & simulation",
   "domain": "planning",
   "domainLabel": "Planning & strategy",
   "rows": 42,
   "bytes": 2740,
   "columnCount": 6,
   "columns": [
    {
     "name": "assumption_id",
     "type": "STRING"
    },
    {
     "name": "plan_version_id",
     "type": "STRING"
    },
    {
     "name": "metric_name",
     "type": "STRING"
    },
    {
     "name": "assumed_value",
     "type": "FLOAT64"
    },
    {
     "name": "effective_date",
     "type": "DATE"
    },
    {
     "name": "superseded_date",
     "type": "DATE"
    }
   ],
   "weight": 1.716,
   "readBy": []
  },
  {
   "id": "plan_scenarios",
   "layer": "simulation",
   "layerLabel": "Scenario & simulation",
   "domain": "planning",
   "domainLabel": "Planning & strategy",
   "rows": 12,
   "bytes": 3040,
   "columnCount": 5,
   "columns": [
    {
     "name": "scenario_id",
     "type": "STRING"
    },
    {
     "name": "plan_version_id",
     "type": "STRING"
    },
    {
     "name": "assumption_delta",
     "type": "STRING"
    },
    {
     "name": "reversal_trigger",
     "type": "STRING"
    },
    {
     "name": "reversal_cost",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.342,
   "readBy": []
  },
  {
   "id": "plan_versions",
   "layer": "simulation",
   "layerLabel": "Scenario & simulation",
   "domain": "planning",
   "domainLabel": "Planning & strategy",
   "rows": 6,
   "bytes": 168,
   "columnCount": 3,
   "columns": [
    {
     "name": "plan_version_id",
     "type": "STRING"
    },
    {
     "name": "published_date",
     "type": "DATE"
    },
    {
     "name": "next_review_date",
     "type": "DATE"
    }
   ],
   "weight": 1.204,
   "readBy": []
  },
  {
   "id": "procurement_bids",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 300,
   "bytes": 21775,
   "columnCount": 7,
   "columns": [
    {
     "name": "technical_rating_score",
     "type": "FLOAT64"
    },
    {
     "name": "compliance_checked",
     "type": "BOOL"
    },
    {
     "name": "rfp_id",
     "type": "STRING"
    },
    {
     "name": "proposed_cost",
     "type": "FLOAT64"
    },
    {
     "name": "bid_status",
     "type": "STRING"
    },
    {
     "name": "vendor_name",
     "type": "STRING"
    },
    {
     "name": "bid_id",
     "type": "STRING"
    }
   ],
   "weight": 2.491,
   "readBy": []
  },
  {
   "id": "radio_communications",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 573,
   "bytes": 77157,
   "columnCount": 6,
   "columns": [
    {
     "name": "emergency_keyword_flag",
     "type": "BOOL"
    },
    {
     "name": "audio_gcs_path",
     "type": "STRING"
    },
    {
     "name": "sentiment_score",
     "type": "FLOAT64"
    },
    {
     "name": "channel_id",
     "type": "STRING"
    },
    {
     "name": "transcript",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    }
   ],
   "weight": 2.766,
   "readBy": []
  },
  {
   "id": "rebate_claims",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 6,
   "bytes": 270,
   "columnCount": 5,
   "columns": [
    {
     "name": "claim_id",
     "type": "STRING"
    },
    {
     "name": "contract_id",
     "type": "STRING"
    },
    {
     "name": "period",
     "type": "STRING"
    },
    {
     "name": "amount_claimed",
     "type": "FLOAT64"
    },
    {
     "name": "amount_entitled",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.204,
   "readBy": []
  },
  {
   "id": "rfp_items",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "commercial",
   "domainLabel": "Commercial & procurement",
   "rows": 3,
   "bytes": 99,
   "columnCount": 2,
   "columns": [
    {
     "name": "rfp_id",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    }
   ],
   "weight": 1.114,
   "readBy": []
  },
  {
   "id": "safety_incidents",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 60,
   "bytes": 12501,
   "columnCount": 8,
   "columns": [
    {
     "name": "investigation_status",
     "type": "STRING"
    },
    {
     "name": "root_cause",
     "type": "STRING"
    },
    {
     "name": "description",
     "type": "STRING"
    },
    {
     "name": "gps_location",
     "type": "STRING"
    },
    {
     "name": "location_description",
     "type": "STRING"
    },
    {
     "name": "severity_level",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "incident_id",
     "type": "STRING"
    }
   ],
   "weight": 1.845,
   "readBy": []
  },
  {
   "id": "safety_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 5,
   "bytes": 10188,
   "columnCount": 0,
   "columns": [],
   "weight": 1.176,
   "readBy": []
  },
  {
   "id": "simulation_runs",
   "layer": "simulation",
   "layerLabel": "Scenario & simulation",
   "domain": "planning",
   "domainLabel": "Planning & strategy",
   "rows": 150,
   "bytes": 37234,
   "columnCount": 6,
   "columns": [
    {
     "name": "projected_cooling_curve",
     "type": "STRING"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "recalculated_parameters",
     "type": "STRING"
    },
    {
     "name": "nba_executed",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    },
    {
     "name": "run_id",
     "type": "STRING"
    }
   ],
   "weight": 2.204,
   "readBy": []
  },
  {
   "id": "telemetry_alarm_risk_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 7,
   "bytes": 54291,
   "columnCount": 0,
   "columns": [],
   "weight": 1.23,
   "readBy": []
  },
  {
   "id": "telemetry_stream",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "fleet",
   "domainLabel": "Mobile fleet & haulage",
   "rows": 25946,
   "bytes": 1089720,
   "columnCount": 4,
   "columns": [
    {
     "name": "metric_name",
     "type": "STRING"
    },
    {
     "name": "metric_value",
     "type": "FLOAT64"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "timestamp",
     "type": "TIMESTAMP"
    }
   ],
   "weight": 4.414,
   "readBy": []
  },
  {
   "id": "text_embedding_model",
   "layer": "model",
   "layerLabel": "BQML models",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 1,
   "bytes": 99,
   "columnCount": 0,
   "columns": [],
   "weight": 1.041,
   "readBy": []
  },
  {
   "id": "unstructured_docs_metadata",
   "layer": "corpus",
   "layerLabel": "Unstructured corpus",
   "domain": "platform",
   "domainLabel": "Platform & ontology",
   "rows": 50,
   "bytes": 6756,
   "columnCount": 6,
   "columns": [
    {
     "name": "chunk_count",
     "type": "INT64"
    },
    {
     "name": "last_updated",
     "type": "TIMESTAMP"
    },
    {
     "name": "category",
     "type": "STRING"
    },
    {
     "name": "file_path",
     "type": "STRING"
    },
    {
     "name": "title",
     "type": "STRING"
    },
    {
     "name": "doc_id",
     "type": "STRING"
    }
   ],
   "weight": 1.778,
   "readBy": []
  },
  {
   "id": "v_fatigue_scored",
   "layer": "serving",
   "layerLabel": "Serving views",
   "domain": "hse",
   "domainLabel": "Health, safety & people",
   "rows": 0,
   "bytes": 0,
   "columnCount": 3,
   "columns": [
    {
     "name": "operator_id",
     "type": "STRING"
    },
    {
     "name": "log_date",
     "type": "DATE"
    },
    {
     "name": "fatigue_band",
     "type": "STRING"
    }
   ],
   "weight": 1.0,
   "readBy": []
  },
  {
   "id": "warranty_claims",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 12,
   "bytes": 649,
   "columnCount": 6,
   "columns": [
    {
     "name": "claim_id",
     "type": "STRING"
    },
    {
     "name": "entitlement_id",
     "type": "STRING"
    },
    {
     "name": "work_order_id",
     "type": "STRING"
    },
    {
     "name": "filed_date",
     "type": "DATE"
    },
    {
     "name": "status",
     "type": "STRING"
    },
    {
     "name": "amount_claimed",
     "type": "FLOAT64"
    }
   ],
   "weight": 1.342,
   "readBy": []
  },
  {
   "id": "warranty_entitlements",
   "layer": "operational",
   "layerLabel": "Operational records",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 10,
   "bytes": 1086,
   "columnCount": 7,
   "columns": [
    {
     "name": "entitlement_id",
     "type": "STRING"
    },
    {
     "name": "asset_id",
     "type": "STRING"
    },
    {
     "name": "oem_vendor",
     "type": "STRING"
    },
    {
     "name": "component",
     "type": "STRING"
    },
    {
     "name": "coverage_start",
     "type": "DATE"
    },
    {
     "name": "coverage_end",
     "type": "DATE"
    },
    {
     "name": "source_clause",
     "type": "STRING"
    }
   ],
   "weight": 1.301,
   "readBy": []
  },
  {
   "id": "work_order_parts_edge",
   "layer": "semantic",
   "layerLabel": "Semantic / property graph",
   "domain": "maintenance",
   "domainLabel": "Asset & maintenance",
   "rows": 186,
   "bytes": 17956,
   "columnCount": 3,
   "columns": [
    {
     "name": "edge_id",
     "type": "STRING"
    },
    {
     "name": "work_order_id",
     "type": "STRING"
    },
    {
     "name": "part_number",
     "type": "STRING"
    }
   ],
   "weight": 2.292,
   "readBy": []
  }
 ],
 "edges": [
  {
   "source": "agent_approvals",
   "target": "agent_catalog",
   "keys": [
    "agent_id"
   ],
   "weight": 1
  },
  {
   "source": "agent_approvals",
   "target": "agent_run_log",
   "keys": [
    "agent_id"
   ],
   "weight": 1
  },
  {
   "source": "agent_catalog",
   "target": "agent_run_log",
   "keys": [
    "agent_id"
   ],
   "weight": 1
  },
  {
   "source": "agent_run_log",
   "target": "simulation_runs",
   "keys": [
    "run_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "crusher_states",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "erp_work_orders",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "maintenance_logs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "simulation_runs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "assets",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "contract_transactions",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "contracts",
   "keys": [
    "bid_id",
    "part_number"
   ],
   "weight": 2
  },
  {
   "source": "bid_parts_edge",
   "target": "inventory_levels",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "procurement_bids",
   "keys": [
    "bid_id"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "rfp_items",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "bid_parts_edge",
   "target": "work_order_parts_edge",
   "keys": [
    "edge_id",
    "part_number"
   ],
   "weight": 2
  },
  {
   "source": "biometric_fatigue_logs",
   "target": "fatigue_logs_node",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "biometric_fatigue_logs",
   "target": "incident_involvements",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "biometric_fatigue_logs",
   "target": "operator_vehicle_assignments",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "biometric_fatigue_logs",
   "target": "operators_node",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "biometric_fatigue_logs",
   "target": "v_fatigue_scored",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "capital_options",
   "target": "plan_assumptions",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "capital_options",
   "target": "plan_scenarios",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "capital_options",
   "target": "plan_versions",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "contract_transactions",
   "target": "contracts",
   "keys": [
    "contract_id",
    "part_number"
   ],
   "weight": 2
  },
  {
   "source": "contract_transactions",
   "target": "inventory_levels",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contract_transactions",
   "target": "rebate_claims",
   "keys": [
    "contract_id"
   ],
   "weight": 1
  },
  {
   "source": "contract_transactions",
   "target": "rfp_items",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contract_transactions",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "inventory_levels",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "procurement_bids",
   "keys": [
    "bid_id"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "rebate_claims",
   "keys": [
    "contract_id"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "rfp_items",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "contracts",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "erp_work_orders",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "maintenance_logs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "simulation_runs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "crusher_states",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "doc_chunks",
   "target": "doc_chunks_embedded",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "doc_chunks",
   "target": "unstructured_docs_metadata",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "doc_chunks_embedded",
   "target": "unstructured_docs_metadata",
   "keys": [
    "doc_id"
   ],
   "weight": 1
  },
  {
   "source": "drill_assay_logs",
   "target": "drill_holes",
   "keys": [
    "drill_hole_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "maintenance_logs",
   "keys": [
    "asset_id",
    "work_order_id"
   ],
   "weight": 2
  },
  {
   "source": "erp_work_orders",
   "target": "simulation_runs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "warranty_claims",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "erp_work_orders",
   "target": "work_order_parts_edge",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_logs_node",
   "target": "incident_involvements",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_logs_node",
   "target": "operator_vehicle_assignments",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_logs_node",
   "target": "operators_node",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fatigue_logs_node",
   "target": "v_fatigue_scored",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "fleet_vehicles",
   "target": "incident_involvements",
   "keys": [
    "vehicle_id"
   ],
   "weight": 1
  },
  {
   "source": "fleet_vehicles",
   "target": "operator_vehicle_assignments",
   "keys": [
    "vehicle_id"
   ],
   "weight": 1
  },
  {
   "source": "haul_cycle_log",
   "target": "haulage_routes",
   "keys": [
    "route_id"
   ],
   "weight": 1
  },
  {
   "source": "incident_involvements",
   "target": "operator_vehicle_assignments",
   "keys": [
    "operator_id",
    "vehicle_id"
   ],
   "weight": 2
  },
  {
   "source": "incident_involvements",
   "target": "operators_node",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "incident_involvements",
   "target": "safety_incidents",
   "keys": [
    "incident_id"
   ],
   "weight": 1
  },
  {
   "source": "incident_involvements",
   "target": "v_fatigue_scored",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "inventory_levels",
   "target": "rfp_items",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "inventory_levels",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "simulation_runs",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "warranty_claims",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "maintenance_logs",
   "target": "work_order_parts_edge",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  },
  {
   "source": "operator_vehicle_assignments",
   "target": "operators_node",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "operator_vehicle_assignments",
   "target": "v_fatigue_scored",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "operators_node",
   "target": "v_fatigue_scored",
   "keys": [
    "operator_id"
   ],
   "weight": 1
  },
  {
   "source": "plan_assumptions",
   "target": "plan_scenarios",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "plan_assumptions",
   "target": "plan_versions",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "plan_scenarios",
   "target": "plan_versions",
   "keys": [
    "plan_version_id"
   ],
   "weight": 1
  },
  {
   "source": "procurement_bids",
   "target": "rfp_items",
   "keys": [
    "rfp_id"
   ],
   "weight": 1
  },
  {
   "source": "rebate_claims",
   "target": "warranty_claims",
   "keys": [
    "claim_id"
   ],
   "weight": 1
  },
  {
   "source": "rfp_items",
   "target": "work_order_parts_edge",
   "keys": [
    "part_number"
   ],
   "weight": 1
  },
  {
   "source": "simulation_runs",
   "target": "telemetry_stream",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "simulation_runs",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "telemetry_stream",
   "target": "warranty_entitlements",
   "keys": [
    "asset_id"
   ],
   "weight": 1
  },
  {
   "source": "warranty_claims",
   "target": "warranty_entitlements",
   "keys": [
    "entitlement_id"
   ],
   "weight": 1
  },
  {
   "source": "warranty_claims",
   "target": "work_order_parts_edge",
   "keys": [
    "work_order_id"
   ],
   "weight": 1
  }
 ],
 "layers": [
  {
   "key": "model",
   "label": "BQML models"
  },
  {
   "key": "control",
   "label": "Agent control plane"
  },
  {
   "key": "corpus",
   "label": "Unstructured corpus"
  },
  {
   "key": "semantic",
   "label": "Semantic / property graph"
  },
  {
   "key": "serving",
   "label": "Serving views"
  },
  {
   "key": "simulation",
   "label": "Scenario & simulation"
  },
  {
   "key": "operational",
   "label": "Operational records"
  }
 ],
 "domains": [
  {
   "key": "geology",
   "label": "Geology & resource"
  },
  {
   "key": "plant",
   "label": "Processing plant"
  },
  {
   "key": "fleet",
   "label": "Mobile fleet & haulage"
  },
  {
   "key": "hse",
   "label": "Health, safety & people"
  },
  {
   "key": "maintenance",
   "label": "Asset & maintenance"
  },
  {
   "key": "commercial",
   "label": "Commercial & procurement"
  },
  {
   "key": "planning",
   "label": "Planning & strategy"
  },
  {
   "key": "platform",
   "label": "Platform & ontology"
  }
 ],
 "meta": {
  "project": "genial-union-475913-i7",
  "dataset": "mining_data",
  "tableCount": 55,
  "edgeCount": 81,
  "columnCount": 265,
  "rowCount": 42214,
  "excludedCount": 11,
  "excluded": [
   "biometric_fatigue_logs_original_20260810",
   "crusher_states_original_20260810",
   "drill_assay_logs_original_20260810",
   "erp_work_orders_original_20260810",
   "fatigue_logs_node_original_20260810",
   "geological_block_models_original_20260810",
   "inventory_levels_original_20260810",
   "maintenance_logs_original_20260810",
   "maintenance_logs_task10_probe",
   "metallurgical_recovery_original_20260810",
   "telemetry_stream_original_20260810"
  ],
  "genericKeysDropped": []
 }
};
