// Generated by scripts/build_sales_doc.py — do not edit.
window.SALES_ASSETS = {
 "AGT-19": {
  "video": "../../data/uat/videos/AGT-19/page@034c1ca6db082835450fa94388d4ae76.webm",
  "situation": "Pit 4 copper price projection drops 15% from $4.20/lb to $3.57/lb. With mining cost $3.10/t, milling cost $14.50/t, and 89.5% recovery, calculate dynamic Kenneth Lane cut-off grade sensitivity.",
  "action": "Looks up the geological block model, the financial ledger and the mine production schedule \u2014 the operation's live data \u2014 and answers in its own words: \u201cStrategic Planning Advisory Report\u201d Real figures from the recording: 4.20, 9,259.42, 9,323.40.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S01-COORDINATOR": {
  "video": "../../data/uat/videos/S01-COORDINATOR/page@9a67f58d67441ab5bc0f1b851a57d618.webm",
  "situation": "Synthesize Section 104N drillhole assays into Ordinary Kriging 3D block model.",
  "action": "Looks up drill hole records, assay results and the geological block model \u2014 the operation's live data \u2014 and answers in its own words: \u201cSynthesis of Section 104N Drillhole Assays into Ordinary Kriging 3D Block\u201d Real figures from the recording: 485,148.11, 7,432,325.23, 532.80.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S01-1-LITHOLOGY": {
  "video": "../../data/uat/videos/S01-1-LITHOLOGY/page@4feba7d4aaf8eba0adcdae97a5b91b07.webm",
  "situation": "From drill_holes, profile the drilling campaign: hole count, total metres drilled, the depth distribution, and the azimuth and dip patterns \u2014 show the numbers. Piece-length logging for rock-quality classification is absent: say so plainly, then identify the three holes whose geometry makes them the best candidates for oriented-core re-logging, and why.",
  "action": "Looks up drill hole records \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Drilling Campaign\u201d Real figures from the recording: 8,509.43, 151.73, 228.75.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S01-2-GEOSTAT": {
  "video": "../../data/uat/videos/S01-2-GEOSTAT/page@8df2c03593acec88ed8341a311c0fe53.webm",
  "situation": "Compute estimation variance for copper block grades at Section 104N.",
  "action": "Looks up assay results \u2014 the operation's live data \u2014 and answers in its own words: \u201cGeostatistical Review & Reconciled\u201d Real figures from the recording: 7,432,014.93, 7,432,993.81, 0.949%.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S01-3-STRUCTURAL": {
  "video": "../../data/uat/videos/S01-3-STRUCTURAL/page@fef24161c391db7131ada37dfb2b83ab.webm",
  "situation": "Analyze strike and dip planes on Section 104N fault envelope.",
  "action": "Looks up the geological block model \u2014 the operation's live data \u2014 and answers in its own words: \u201cStructural Fault Analysis: Section 104N Fault\u201d Real figures from the recording: 0.4375, 0.50, 23.63.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S01-R-CRITIC": {
  "video": "../../data/uat/videos/S01-R-CRITIC/page@ea52d241e23224c991107267a5a92d37.webm",
  "situation": "Audit duplicate core sample assay variance against JORC Code standards.",
  "action": "Looks up assay results and QA/QC standards \u2014 the operation's live data \u2014 and answers in its own words: \u201cQA/QC Red Team Audit: Duplicate Core Sample Assay Variance & JORC Code\u201d Real figures from the recording: 100.0%, 0.0, 447.75.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S02-COORDINATOR": {
  "video": "../../data/uat/videos/S02-COORDINATOR/page@7efbdc19e61babee0642e9e4104662b8.webm",
  "situation": "Optimize Phase 3 pushback extraction sequence with 48 deg overall slope.",
  "action": "Looks up the mine production schedule and pit designs \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Executive Optimization\u201d Real figures from the recording: 48.0, 45.0, 9,323.40.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S02-1-GEOTECH": {
  "video": "../../data/uat/videos/S02-1-GEOTECH/page@7c7cfd1d3c60bcf73b109b1a905b2e76.webm",
  "situation": "From the geotech sensors on the 48 degree wall section, report the actual readings: slope angle, displacement, pore pressure and alarm states \u2014 show them. Then compute the simple stability ratio this data supports using a stated assumption of 35 degrees friction angle, in plain arithmetic, give the result as a range, and let the displacement trend make the final call: safe to continue, or hold.",
  "action": "Looks up geotechnical sensor readings \u2014 the operation's live data \u2014 and answers in its own words: \u201cGeotechnical Assessment & Sensor\u201d Real figures from the recording: 47.0, 49.0, 48.0.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S02-2-SCHEDULE": {
  "video": "../../data/uat/videos/S02-2-SCHEDULE/page@ce6228cd49a014efb702ead23753615b.webm",
  "situation": "Sequence shovel assignments to balance 1.8 Mt/month ore extraction.",
  "action": "Looks up the mine production schedule \u2014 the operation's live data \u2014 and answers in its own words: \u201cShovel Sequencing & Extraction\u201d Real figures from the recording: 1.80, 1.180, 1.196.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S02-3-DUMP": {
  "video": "../../data/uat/videos/S02-3-DUMP/page@ae225950de128ccd7df3158d8719eaaf.webm",
  "situation": "Model North Dump toe containment volume and runout angle of repose.",
  "action": "Looks up pit designs \u2014 the operation's live data \u2014 and answers in its own words: \u201cWaste Dump Geotechnical & Stability Report: North Dump Toe Containment & Runout\u201d Real figures from the recording: 2.558, 25.10, 2.050.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S02-R-CRITIC": {
  "video": "../../data/uat/videos/S02-R-CRITIC/page@1bf756eca21b1d7df15a1b28139ca4aa.webm",
  "situation": "Audit spatial compliance between monthly extraction and long-term model.",
  "action": "Looks up survey scans and the mine production schedule \u2014 the operation's live data \u2014 and answers in its own words: \u201cExecutive Summary & Red Team Audit\u201d Real figures from the recording: 898,261.40, 903,312.60, 5,051.20.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S03-COORDINATOR": {
  "video": "../../data/uat/videos/S03-COORDINATOR/page@cee35447fd836eab3ba3da119fe503d6.webm",
  "situation": "From approved blasts in our design records, show the actual range of burden and powder factor used, against the fleet average \u2014 values on screen. For a harder-than-average block, recommend how far to move burden and powder factor while staying inside the range our own data supports, with each calculation step shown in plain numbers, and confirm from explosives inventory that magazine stock covers the recommendation.",
  "action": "Looks up blast designs and explosives inventory \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Baseline Blast Design Parameters (Approved\u201d Real figures from the recording: 4.01, 5.85, 7.48.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S03-1-GEOMETRY": {
  "video": "../../data/uat/videos/S03-1-GEOMETRY/page@421572ba51dbabfe17b6acf639e30158.webm",
  "situation": "From our blast design records, profile the geometry we actually drill: average burden, spacing, hole diameter and hole depth, and the recorded powder factor \u2014 show the values and verify the powder factor arithmetic in plain numbers. Then recommend a staggered pattern for a 15 m production bench that stays inside our own historical envelope, saying which numbers come from data and which are judgment.",
  "action": "Looks up blast designs \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational Blast Geometry\u201d Real figures from the recording: 5.77, 4.01, 7.48.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S03-2-EXPLOSIVE": {
  "video": "../../data/uat/videos/S03-2-EXPLOSIVE/page@83c90c3cd5c8ed412f0698769677ad4b.webm",
  "situation": "Calculate bulk emulsion VOD and shock energy partitioning.",
  "action": "Looks up explosives inventory \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Operational Context & Explosives Inventory\u201d Real figures from the recording: 1.5, 129.64, 35.54.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S03-R-CRITIC": {
  "video": "../../data/uat/videos/S03-R-CRITIC/page@13e14ff4c82e44dad3287ce9f1c41067.webm",
  "situation": "Enforce 500m blast exclusion perimeter and lightning warning gate.",
  "action": "Looks up blast designs and safety permits records \u2014 the operation's live data \u2014 and answers in its own words: \u201cBlast Safety Critic (Red Team) Gate\u201d Real figures from the recording: 82.2%, 17.8%, 0.497.",
  "logic": "Before answering it runs its Statutory Exclusion Zone Radius & Misfire Detection Gate method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S04-COORDINATOR": {
  "video": "../../data/uat/videos/S04-COORDINATOR/page@50fc06df2f6df347b1cdd9de31569522.webm",
  "situation": "Reassign haul trucks to eliminate 3-truck queue at Shovel 04.",
  "action": "Looks up live fleet telemetry and dispatch routes \u2014 the operation's live data \u2014 and answers in its own words: \u201cDynamic Fleet Dispatch & Queue Optimization\u201d Real figures from the recording: 116.8311, 23.1686, 42.0.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S04-1-SHOVEL": {
  "video": "../../data/uat/videos/S04-1-SHOVEL/page@20d64529b379c35428ef108e8138e14d.webm",
  "situation": "Calculate pass match factor for PC8000 shovel loading CAT 797F.",
  "action": "Looks up live fleet telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cPass Match Factor Calculation: PC8000 Shovel & CAT\u201d Real figures from the recording: 240.0 t, 205.02 t, 130.63 t.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S04-2-ROUTE": {
  "video": "../../data/uat/videos/S04-2-ROUTE/page@7856e44b153ea048d02e56290afab239.webm",
  "situation": "Compute shortest path travel time on Pit Alpha south ramp.",
  "action": "Looks up dispatch routes \u2014 the operation's live data \u2014 and answers in its own words: \u201cRoute Optimization Formulation &\u201d Real figures from the recording: 1,031.49, 11.57, 1.27.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S04-3-PAYLOAD": {
  "video": "../../data/uat/videos/S04-3-PAYLOAD/page@59acd839512abfb3142f4d42719222f2.webm",
  "situation": "Audit 10/10/20 payload distribution across 42 haul cycles.",
  "action": "Looks up live fleet telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cOEM 10/10/20 Payload Distribution\u201d Real figures from the recording: 1.20, 240.00, 202.03.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S04-R-CRITIC": {
  "video": "../../data/uat/videos/S04-R-CRITIC/page@32ef3e442b31ba6b2384c2556e9857e2.webm",
  "situation": "Check operator shift hours and SAFTE circadian fatigue index.",
  "action": "Looks up live fleet telemetry and safety telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational & Fatigue Analysis\u201d Real figures from the recording: 7.0, 4.1, 3.0.",
  "logic": "Before answering it runs its Haul Road Grade Braking Runaway Distance Envelope method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S05-COORDINATOR": {
  "video": "../../data/uat/videos/S05-COORDINATOR/page@658e50cf2bacc904f054804c13c337e4.webm",
  "situation": "Crusher-03 mantle wear is at 78%; eddy-current sensor flags tramp iron.",
  "action": "Looks up crusher telemetry and the asset register \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational Assessment & Directives: Primary Crushing Coordinator\u201d Real figures from the recording: 120.0 mm, 120 mm, 135 mm.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S05-1-CSS": {
  "video": "../../data/uat/videos/S05-1-CSS/page@c3b0bfd34be0d15bbf14c7eab3042a9e.webm",
  "situation": "Based on the crusher telemetry data, what hydraulic pressure setpoint does your governing method indicate for a closed-side setting of 135mm? Report the figures from the data and cite the table you read.",
  "action": "Looks up crusher telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cBased on a review of the crusher telemetry dataset in BigQuery, here is the reconciliation of the figures and the operating\u201d Real figures from the recording: 135 mm, 115 mm, 125 mm.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S05-2-FEED": {
  "video": "../../data/uat/videos/S05-2-FEED/page@999fad73fb7022da6dfe706a5e0707e5.webm",
  "situation": "Regulate apron feeder PID loop for choke feeding conditions.",
  "action": "Looks up crusher telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cFeeder Speed Specialist (s05_2_feed) \u2014 Operational Control\u201d Real figures from the recording: 1,026.30, 1,153.23, 1,297.05.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S05-3-WEAR": {
  "video": "../../data/uat/videos/S05-3-WEAR/page@f7122f90f138fb320b084ea1a67705ea.webm",
  "situation": "Predict remaining liner life on Hardox 500 concave plates.",
  "action": "Looks up the asset register and crusher telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cArchard Wear Modeling\u201d Real figures from the recording: 4.90, 5.10, 1,153.23 tph.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S05-R-CRITIC": {
  "video": "../../data/uat/videos/S05-R-CRITIC/page@7512da8f923257b4409deab211e633f4.webm",
  "situation": "Enforce auto-hold on uncrushable steel tooth detection in cavity.",
  "action": "Looks up crusher telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cInterlock Gate Enforcement Notice: Tramp Iron Eddy-Current\u201d Real figures from the recording: 1,153.23 tph, 1,026.30 tph, 1,297.05 tph.",
  "logic": "Before answering it runs its Tramp Iron Eddy-Current Sensor Interlock Gate method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S06-COORDINATOR": {
  "video": "../../data/uat/videos/S06-COORDINATOR/page@29905a526405f1f5a0b1a550833c6915.webm",
  "situation": "SAG Mill #2 power spikes to 14.8 MW, toe acoustic noise dampened.",
  "action": "Looks up plant telemetry and the asset register \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational Assessment & Coordination\u201d Real figures from the recording: 14.8, 3.09, 4.0.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S06-1-SAG": {
  "video": "../../data/uat/videos/S06-1-SAG/page@5d69c40bfeb8b55f1bd62bcc62325956.webm",
  "situation": "From plant telemetry for the SAG mill, trend power draw, rotational speed and any vibration metrics over the last 30 days \u2014 show the values and flag any reading more than 3 standard deviations from its mean. Acoustic arrays are not installed: state that plainly, then argue from the recorded metrics alone whether current operation looks like liner wear, overload, or normal running.",
  "action": "Looks up plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational Assessment & Plant Telemetry Analysis: SAG Mill\u201d Real figures from the recording: 30 days, 3.996, 0.362.",
  "logic": "Before answering it runs its Acoustic Toe Angle & Ball Charge Trajectory method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S06-2-BALL": {
  "video": "../../data/uat/videos/S06-2-BALL/page@cd9dd569aa5adb6c24c5d7cf46c3416e.webm",
  "situation": "Calculate daily grinding media ball charge replenishment for 3,800 tph.",
  "action": "Looks up plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational Reconciliation & Baseline\u201d Real figures from the recording: 3,800 tph, 1,153.25 tph, 1,000.56.",
  "logic": "Before answering it runs its Austin Population Balance Grinding Kinetics method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S06-3-CYCLONE": {
  "video": "../../data/uat/videos/S06-3-CYCLONE/page@db701ce1004ec5f335860561ccf09129.webm",
  "situation": "From plant telemetry, report what the grinding circuit actually records with latest values \u2014 show them. Cyclone geometry and operating pressure are not instrumented: say so plainly, then give an illustrative cut-size answer as a range using standard 10-inch cyclone geometry as a named assumption, in plain arithmetic, and specify the two measurements that would make it exact.",
  "action": "Looks up plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Actual Grinding Circuit\u201d Real figures from the recording: 3.68, 3.6785, 14.80.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S06-R-CRITIC": {
  "video": "../../data/uat/videos/S06-R-CRITIC/page@43366a1adf5e09faf6c4232aed9d8dbf.webm",
  "situation": "Check cyclone feed density and trunnion bearing lubrication.",
  "action": "Looks up plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cCritical Evaluation: Cyclone Feed Density & Trunnion Bearing\u201d Real figures from the recording: 85.20, 71.42, 65.01.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S07-COORDINATOR": {
  "video": "../../data/uat/videos/S07-COORDINATOR/page@261075636ed411842acb0dc4c579ad5e.webm",
  "situation": "Optimize PAX collector dosing for 0.72% Cu ore to maximize recovery.",
  "action": "Looks up flotation assay results and plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cExecutive Optimization\u201d Real figures from the recording: 0.72%, 1.09%, 0.81%.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S07-2-AIR": {
  "video": "../../data/uat/videos/S07-2-AIR/page@972d9b9e73cd200b1fe255468304dafd.webm",
  "situation": "Regulate superficial gas velocity Jg across rougher bank.",
  "action": "Looks up plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cSupervisory Control & Gas Holdup Profile: Rougher Bank Air\u201d Real figures from the recording: 1,153.25 tph, 1,000.56, 1,299.86 tph.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S07-3-GRADE": {
  "video": "../../data/uat/videos/S07-3-GRADE/page@eea13ed81a4ebd9fae30a863160e6093.webm",
  "situation": "Model cleaner bank separation efficiency for 28% Cu concentrate.",
  "action": "Looks up flotation assay results \u2014 the operation's live data \u2014 and answers in its own words: \u201cSeparation Efficiency (SE) Model for 28.0% Cu\u201d Real figures from the recording: 28.0%, 1.0929%, 0.81%.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S07-R-CRITIC": {
  "video": "../../data/uat/videos/S07-R-CRITIC/page@80a870494c8af7389801aac6e355fb4b.webm",
  "situation": "Check concentrate arsenic and bismuth penalty thresholds.",
  "action": "Looks up flotation assay results \u2014 the operation's live data \u2014 and answers in its own words: \u201cSmelter Penalty Critic (Red Team) Audit\u201d Real figures from the recording: 27.41%, 24.99%, 30.16%.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S08-COORDINATOR": {
  "video": "../../data/uat/videos/S08-COORDINATOR/page@64d10cb0d1e62f491e3debdbc274b351.webm",
  "situation": "Dam 2 piezometer reports pore pressure rise of 0.38m/week after rain.",
  "action": "Looks up tailings dam sensor readings and water balance logs \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational Reconciliation & Data\u201d Real figures from the recording: 0.38, 2.65, 136.1 kPa.",
  "logic": "Before answering it runs its GISTM Dam Conformance & Phreatic Surface Line method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S08-1-WATER": {
  "video": "../../data/uat/videos/S08-1-WATER/page@1875f394a9efcb3928f3bbca231031ba.webm",
  "situation": "Balance decant return water and evaporation pond volume.",
  "action": "Looks up water balance logs \u2014 the operation's live data \u2014 and answers in its own words: \u201cDecant Water Return & Evaporation Pond Water Balance\u201d Real figures from the recording: 183,156.10, 1,096.74, 100.00%.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S08-2-PORE": {
  "video": "../../data/uat/videos/S08-2-PORE/page@401b56a0d7e38623d15ccc6dd19f15aa.webm",
  "situation": "From the TSF piezometers, trend pore pressure and phreatic surface by location across the full record \u2014 show the values and flag the worst factor-of-safety readings. Then estimate the dissipation timeline directly from the observed decay between readings, in plain arithmetic with no consolidation formulas, quote it as a range, and name the single lab parameter that would firm it up.",
  "action": "Looks up tailings dam sensor readings \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Executive Summary & Operational\u201d Real figures from the recording: 61.10 kPa, 239.00 kPa, 154.67 kPa.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S08-3-THICK": {
  "video": "../../data/uat/videos/S08-3-THICK/page@121fa0ce91cfa410229293dc0b0989ce.webm",
  "situation": "Regulate flocculant dosing for 65% solids underflow.",
  "action": "Looks up plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational Assessment & Telemetry\u201d Real figures from the recording: 65.0%, 57.5%, 68.0%.",
  "logic": "Before answering it runs its Kynch Sedimentation Solids Flux Theory method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S08-R-CRITIC": {
  "video": "../../data/uat/videos/S08-R-CRITIC/page@2798e977174e09f1670b2c957675267e.webm",
  "situation": "Audit GISTM compliance and critical state soil mechanics.",
  "action": "Looks up tailings dam sensor readings and safety permits records \u2014 the operation's live data \u2014 and answers in its own words: \u201cAdversarial Geotechnical Audit: GISTM Compliance & Critical State Soil\u201d Real figures from the recording: 1.30, 1.135, 16.0%.",
  "logic": "Before answering it runs its Critical State Soil Mechanics & Static Liquefaction Index method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S09-COORDINATOR": {
  "video": "../../data/uat/videos/S09-COORDINATOR/page@3f4b4cc3623076a24998ed20d18ae3f1.webm",
  "situation": "SAG Mill pinion bearing vibration reaches 4.8 mm/s RMS at 1480 RPM.",
  "action": "Looks up the asset register, crusher telemetry and open work orders \u2014 the operation's live data \u2014 and answers in its own words: \u201cCoordinator ID: s09_coordinator (Asset Reliability Swarm Coordinator / P0 Crisis Arbiter / Reliability\u201d Real figures from the recording: 4.80 mm, 24.67, 14.8.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S09-1-VIBRATION": {
  "video": "../../data/uat/videos/S09-1-VIBRATION/page@8b3bd2504000791f37a1ebbd6d597ccd.webm",
  "situation": "From crusher telemetry, trend rotational torque and feed rate over the last 30 days \u2014 show the values and flag any outlier beyond 3 standard deviations with its timestamp. Spectral vibration data is absent: say so plainly, then use the assets register's stored physics parameters to state which defect signature we would expect to see, whether the trend is consistent with it, and finish with a clear inspect or do-not-inspect call.",
  "action": "Looks up the asset register and crusher telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Telemetry Trend Analysis (Last 30\u201d Real figures from the recording: 3,874.51, 145.47, 3,438.10.",
  "logic": "Before answering it runs its ISO 10816-3 RMS Velocity & BPFI Harmonics method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S09-2-TRIBOLOGY": {
  "video": "../../data/uat/videos/S09-2-TRIBOLOGY/page@9071994a3f4ace9ba7013f550a0ea236.webm",
  "situation": "Evaluate Karl Fischer moisture and PQ particle quantifier index.",
  "action": "Looks up the asset register and oil sample analyses \u2014 the operation's live data \u2014 and answers in its own words: \u201cExecutive Tribological\u201d Real figures from the recording: 705.4, 0.0705%, 0.0.",
  "logic": "Before answering it runs its PQ Index & Karl Fischer Moisture PPM method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S09-3-THERMAL": {
  "video": "../../data/uat/videos/S09-3-THERMAL/page@971bd19431ff803203abdeace2559910.webm",
  "situation": "Analyze thermal gradient across pinion bearing housing.",
  "action": "Looks up the asset register and crusher telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cThermal IR Specialist Assessment: Pinion Bearing Housing Thermal Gradient\u201d Real figures from the recording: 74.0, 4,205.0, 1,210.0 tph.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S09-R-CRITIC": {
  "video": "../../data/uat/videos/S09-R-CRITIC/page@1f7ede76f8dc75fc6b586cd1bdd08deb.webm",
  "situation": "Enforce Dual-Key HMAC MFA prior to staging SAP PM work pack.",
  "action": "Looks up the asset register and open work orders \u2014 the operation's live data \u2014 and answers in its own words: \u201cMaintenance Safety Critic (Red Team) \u2014 Safety Audit & Enforcement\u201d",
  "logic": "Before answering it runs its LOTO Isolation Integrity & Failure Window Safety Gate method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S10-COORDINATOR": {
  "video": "../../data/uat/videos/S10-COORDINATOR/page@9f65832d7bd76408e945ae4ef0fc04bd.webm",
  "situation": "Audit contractor haulage invoice #INV-8839 against signed MSA rate card.",
  "action": "Looks up supplier contracts and invoices \u2014 the operation's live data \u2014 and answers in its own words: \u201cInvoice Contract Matching & Rate Card Audit\u201d Real figures from the recording: 58,549.56, 7.6.",
  "logic": "Before answering it runs its Invoice Contract Matching & Rate Card Variance method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S10-1-CONTRACT": {
  "video": "../../data/uat/videos/S10-1-CONTRACT/page@1be6f7d1713597ad1de131a36782d9db.webm",
  "situation": "Fuzzy-match line items against signed Master Service Agreement.",
  "action": "Looks up supplier contracts \u2014 the operation's live data \u2014 and answers in its own words: \u201cContract Rate Auditor Audit\u201d Real figures from the recording: 1,149.35, 390.23, 1,116.43.",
  "logic": "Before answering it runs its Levenshtein Distance & Unit Price Deviation method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S10-2-ESCALATE": {
  "video": "../../data/uat/videos/S10-2-ESCALATE/page@274fe2eac11a0d9003e90f56f6f36dde.webm",
  "situation": "Compute labor and diesel escalation delta against PPI indices.",
  "action": "Looks up supplier contracts \u2014 the operation's live data \u2014 and answers in its own words: \u201cPPI Indexation Audit & Escalation\u201d Real figures from the recording: 1.0, 1.00, 0.00.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S10-3-WARRANTY": {
  "video": "../../data/uat/videos/S10-3-WARRANTY/page@17b82dc0017fae45c0e3ace352ca962a.webm",
  "situation": "Audit SAG liner premature failure against 8,000-hour MTBF warranty.",
  "action": "Looks up the asset register and supplier contracts \u2014 the operation's live data \u2014 and answers in its own words: \u201cExecutive Summary & Warranty Recovery\u201d Real figures from the recording: 0.00.",
  "logic": "Before answering it runs its MTBF vs Warranty Period Recovery Claimer method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S10-R-CRITIC": {
  "video": "../../data/uat/videos/S10-R-CRITIC/page@020e98ac12494a421b4ea528373d112f.webm",
  "situation": "Enforce FCPA compliance gate on sole-source supplier requisitions.",
  "action": "Looks up supplier contracts and invoices \u2014 the operation's live data \u2014 and answers in its own words: \u201cAnti-Bribery & FCPA Red Team Audit Report: Sole-Source Requisition & Vendor Compliance Gate\u201d Real figures from the recording: 17,444.19, 5.0, 78,737.49.",
  "logic": "Before answering it runs its Vendor Beneficial Ownership & Single-Source Flags method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S11-COORDINATOR": {
  "video": "../../data/uat/videos/S11-COORDINATOR/page@38a04bfed070d9966c86c1de17815738.webm",
  "situation": "Hydraulic cylinder stock is 0 with 8-week supplier lead time.",
  "action": "Looks up spare parts stock and purchase-order history \u2014 the operation's live data \u2014 and answers in its own words: \u201cInventory Reconciliation & Operational\u201d Real figures from the recording: 56 days, 7 days, 45 days.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S11-1-STOCK": {
  "video": "../../data/uat/videos/S11-1-STOCK/page@3b965bd8a823d77f9c94fcdfd0911e10.webm",
  "situation": "Calculate safety stock buffer for high-criticality bearings.",
  "action": "Looks up spare parts stock \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Spare Parts Inventory Status\u201d Real figures from the recording: 14 days, 1,250.00, 0.00.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S11-2-LEADTIME": {
  "video": "../../data/uat/videos/S11-2-LEADTIME/page@6e9fc9e33cedc9579f517726878ca4d1.webm",
  "situation": "Model Gamma distribution supplier lead-time variability.",
  "action": "Looks up purchase-order history \u2014 the operation's live data \u2014 and answers in its own words: \u201cGamma Distribution Supplier Lead-Time Variability\u201d Real figures from the recording: 1 day, 15.04, 6.81.",
  "logic": "Before answering it runs its Gamma Distribution Lead Time Modeling method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S11-3-HOLDING": {
  "video": "../../data/uat/videos/S11-3-HOLDING/page@06bfb54fc61c16622252580c1401eefa.webm",
  "situation": "Analyze working capital carrying cost on $45M MRO warehouse.",
  "action": "Looks up spare parts stock \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Assumption Reconciliation & Operational\u201d Real figures from the recording: 45,000,000.00, 45.00, 55,879,117.67.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S11-R-CRITIC": {
  "video": "../../data/uat/videos/S11-R-CRITIC/page@c380931bb3590a89297d73616fea1e8d.webm",
  "situation": "Flag non-moving spares (>365 days) for inventory buyback.",
  "action": "Looks up spare parts stock \u2014 the operation's live data \u2014 and answers in its own words: \u201cDead Stock Critic (Red Team) Audit: Inactive Inventory Aging (>365 Days) & Buyback\u201d Real figures from the recording: 2,880.00, 0.01%, 365 days.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S12-COORDINATOR": {
  "video": "../../data/uat/videos/S12-COORDINATOR/page@2c27ca5ea3461d820a218c2635bbc6f8.webm",
  "situation": "Vessel 'MV Cape Osprey' arrives in 48h for 160,000t loading.",
  "action": "Looks up rail schedules, vessel movements at the port and stockpile records \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational Assessment: Vessel 'MV Cape Osprey' Arrival & Dynamic Network\u201d Real figures from the recording: 61,262.1, 24,431.6, 100,619.2.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S12-1-RAIL": {
  "video": "../../data/uat/videos/S12-1-RAIL/page@9dea4b78667ca28b2aace1f7d1ff3fa3.webm",
  "situation": "Optimize train rake cycle time across 400km heavy-haul rail corridor.",
  "action": "Looks up rail schedules \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational Assessment & Train Rake Cycle Optimization (400 km Heavy-Haul\u201d Real figures from the recording: 2,149,409.5, 17,911.75, 9,061.80 t.",
  "logic": "Before answering it runs its Railway Headway & Velocity Optimization method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S12-2-BLEND": {
  "video": "../../data/uat/videos/S12-2-BLEND/page@5ba0983f1623f42ff676b980b53d374f.webm",
  "situation": "Formulate LP blend model for 28.0% Cu export specification.",
  "action": "Looks up stockpile records \u2014 the operation's live data \u2014 and answers in its own words: \u201cLinear Programming (LP) Blend Model Formulation for 28.0% Cu Export\u201d Real figures from the recording: 28.0%, 2,991,203.9, 0.4728%.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S12-3-BERTH": {
  "video": "../../data/uat/videos/S12-3-BERTH/page@883c977584e76b59bf90e7e310ccce52.webm",
  "situation": "Compute BIMCO laytime Statement of Fact deductions.",
  "action": "Looks up vessel movements at the port \u2014 the operation's live data \u2014 and answers in its own words: \u201cMarine Laytime & Demurrage Statement of Fact (SOF)\u201d Real figures from the recording: 2.0 days, 48 hours, 162 days.",
  "logic": "Before answering it runs its BIMCO Laytime Pro-Rata & Demurrage Liability method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S12-R-CRITIC": {
  "video": "../../data/uat/videos/S12-R-CRITIC/page@220cba1c1a025e4a4c655807f14f00d6.webm",
  "situation": "Enforce IMSBC Transportable Moisture Limit (TML < 9.2%).",
  "action": "Looks up vessel movements at the port and stockpile records \u2014 the operation's live data \u2014 and answers in its own words: \u201cGoverning Method &\u201d Real figures from the recording: 9.20%, 10.00%, 9.73%.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D01": {
  "video": "../../data/uat/videos/D01/page@00ead87e481d9c97351fdf3a0a50f2ee.webm",
  "situation": "Calculate RQD on drill core tray #104 with lengths [12, 18, 8, 22, 14, 5, 25]cm on 120cm run.",
  "action": "Looks up drill hole records \u2014 the operation's live data \u2014 and answers in its own words: \u201cCore Image Segmentation & RQD\u201d Real figures from the recording: 75.83%, 86.67%.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D02": {
  "video": "../../data/uat/videos/D02/page@1ed6e647f025e88506843263040609d1.webm",
  "situation": "Extract sericite vs illite crystallinity ratio from 2200nm SWIR spectral reflection.",
  "action": "Looks up drill hole records and assay results \u2014 the operation's live data \u2014 and answers in its own words: \u201cBased on an inspection of the project database (genial-union-475913-i7.mining_data), here is the spectral feature extraction evaluation and data\u201d Real figures from the recording: 1.743%, 1.213, 1.192%.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D03": {
  "video": "../../data/uat/videos/D03/page@68b64c6ed94cebda026b1a557be6a23d.webm",
  "situation": "Audit drill spacing confidence for 25x25m vs 50x50m drill grids.",
  "action": "Looks up drill hole records and the geological block model \u2014 the operation's live data \u2014 and answers in its own words: \u201cJORC Mineral Resource Classification Audit: Drill Spacing Confidence\u201d Real figures from the recording: 8,509.43, 0.30, 4.0.",
  "logic": "Before answering it runs its Spatial Drill Spacing Confidence Index method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D04": {
  "video": "../../data/uat/videos/D04/page@a8d67caa7071bde5702b06c660a63e3e.webm",
  "situation": "Calculate CJ detonation pressure for emulsion with density 1.18 g/cm3 and VOD 5400 m/s.",
  "action": "Looks up blast designs \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Data Reconciliation &\u201d Real figures from the recording: 1.18, 3.0, 8.602.",
  "logic": "Before answering it runs its Chapman-Jouguet Detonation Hugoniot Solver method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D05": {
  "video": "../../data/uat/videos/D05/page@595eb7a439c834db268a8e2919a34c65.webm",
  "situation": "Compute maximum flyrock travel distance for 45 deg ejection angle at v0=42 m/s.",
  "action": "Looks up blast designs \u2014 the operation's live data \u2014 and answers in its own words: \u201cThe maximum horizontal travel distance $R$ for a ballistic projectile (flyrock) is determined by the standard ballistic range\u201d Real figures from the recording: 9.81, 1.0, 179.82.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D06": {
  "video": "../../data/uat/videos/D06/page@b14b427713b787531a8d8d47dbaad4b6.webm",
  "situation": "Fit Rosin-Rammler muckpile curve for xc=120mm and uniformity index n=1.15.",
  "action": "Looks up blast designs \u2014 the operation's live data \u2014 and answers in its own words: \u201cRosin-Rammler Muckpile Fragmentation Curve\u201d Real figures from the recording: 63.21%, 1.15, 141.84.",
  "logic": "Before answering it runs its Split-Desktop High-Res Image Segmentation method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D07": {
  "video": "../../data/uat/videos/D07/page@858fc33d0c28bc46198ee88e74ff6a3e.webm",
  "situation": "Calculate Fukuzono inverse velocity failure time for 14 mm/day bench creep.",
  "action": "Looks up geotechnical sensor readings \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Reconciling Supplied Assumption vs. Operational Data\u201d Real figures from the recording: 6.341, 6.008, 6.28.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D08": {
  "video": "../../data/uat/videos/D08/page@8de16710f4d9ddb411d395072a2772e0.webm",
  "situation": "Compute microseismic b-value for 120 seismic events on North Pit fault.",
  "action": "Looks up geotechnical sensor readings \u2014 the operation's live data \u2014 and answers in its own words: \u201cBorehole Seismicity Sentinel Report\u201d Real figures from the recording: 2.40, 6.01, 35.9.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D09": {
  "video": "../../data/uat/videos/D09/page@3decbde598fc487ba82a6b49730f4902.webm",
  "situation": "Calculate discharge rate for 12 horizontal drain holes with k=1e-5 m/s.",
  "action": "Looks up pit designs \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Verification and Reconciliation Against\u201d Real figures from the recording: 2.52, 2.75, 0.864.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D10": {
  "video": "../../data/uat/videos/D10/page@112a90fa3cf58bf4231f9d983dd380c0.webm",
  "situation": "Calculate rimpull requirement for CAT 797F (550t GMW) on 8% ramp with 3% rolling resistance.",
  "action": "Looks up live fleet telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Reconciliation of Assumptions Against Operational\u201d Real figures from the recording: 205.02, 130.63, 239.97.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D11": {
  "video": "../../data/uat/videos/D11/page@bd0b9d1a815749e2fd65596269f58272.webm",
  "situation": "From fleet telemetry, list the haul-cycle metrics we actually record for the truck fleet with latest values \u2014 show them. Compute the fuel-efficiency measure this data genuinely supports, in plain arithmetic, and state plainly which additional logging a full litres-per-tonne-kilometre figure would need.",
  "action": "Looks up live fleet telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Haul-Cycle Metrics Recorded in Fleet\u201d Real figures from the recording: 240.0, 218.40, 32.50.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D12": {
  "video": "../../data/uat/videos/D12/page@cf5c703f217391780cabe5eb785f1071.webm",
  "situation": "Calculate tire TKPH for 238t payload at 24 km/h average cycle speed.",
  "action": "Looks up live fleet telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cTire TKPH Telemetry\u201d Real figures from the recording: 238.00, 205.02, 130.63.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D13": {
  "video": "../../data/uat/videos/D13/page@c03630720d779285ed985b4905b96920.webm",
  "situation": "Screen fleet telemetry for Shovel #04: list every metric we record with its latest value and the unit's operational status, and flag any metric whose latest reading sits more than 3 standard deviations from its trailing mean \u2014 show the values. State plainly which failure modes (for example a lost ground-engaging tooth) this data can and cannot detect, and name the instrument that would close the gap.",
  "action": "Looks up live fleet telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Telemetry Screening for Shovel\u201d Real figures from the recording: 42.0, 339.6, 97.1.",
  "logic": "Before answering it runs its YOLOv8 Ground Engaging Tool Watcher method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D14": {
  "video": "../../data/uat/videos/D14/page@2adebb6dcaacf7168cf8eb158d3a20e7.webm",
  "situation": "Analyze SAG mill acoustic FFT power spectrum at 1200-2400 Hz.",
  "action": "Looks up plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cAgent Profile & Methodological\u201d Real figures from the recording: 3.500, 4.086, 4.700.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D15": {
  "video": "../../data/uat/videos/D15/page@61bb2dbf0916815bc7c778da7cce8a5b.webm",
  "situation": "From plant telemetry around the SAG discharge, list the recorded metrics and trend the most relevant one over the last 30 days \u2014 show the values. Screen blinding is not directly instrumented: say so plainly, state what the throughput and power readings can and cannot tell us about a discharge restriction, and name the single measurement that would settle it.",
  "action": "Looks up plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Recorded Metrics Around the SAG Discharge\u201d Real figures from the recording: 3.911, 14.504, 4.491.",
  "logic": "Before answering it runs its Aperture Occlusion Optical Flow Percentage method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D16": {
  "video": "../../data/uat/videos/D16/page@73fc59d1bbc646ec7e4269446a724d37.webm",
  "situation": "Calculate available Net Positive Suction Head for slurry pump #3 at 65% solids.",
  "action": "Looks up plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Telemetry Reconciliation & Data\u201d Real figures from the recording: 65.4, 968.8, 6.2.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D17": {
  "video": "../../data/uat/videos/D17/page@89fefc6559ab1b69e68c690418453929.webm",
  "situation": "Regulate sump level PID speed for 3,800 tph feed slurry surge.",
  "action": "Looks up plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cSump Level Anti-Surge Control Action\u201d Real figures from the recording: 3,800 tph, 1,153.25 tph, 1,000.56 tph.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D18": {
  "video": "../../data/uat/videos/D18/page@42000aabfaa834385253bc258475ee9a.webm",
  "situation": "From flotation assays, report current feed grade, concentrate grade, tailings grade and recovery \u2014 show the values and verify recovery with a plain two-product check, no formula notation. Bubble-size instrumentation is absent: say so plainly, then quantify how far today's recovery sits below the best 30-day recovery in the data and what that gap is worth in contained-metal terms, quoted as a range.",
  "action": "Looks up flotation assay results and plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cCurrent Flotation Assays &\u201d Real figures from the recording: 1.09%, 26.20%, 0.076%.",
  "logic": "Before answering it runs its Sauter Mean Bubble Diameter d32 & RGB Grade Proxy method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D19": {
  "video": "../../data/uat/videos/D19/page@e4704920adb01abc9087341ef137c114.webm",
  "situation": "Calculate potassium amyl xanthate (PAX) potency after 72 hours storage at 32 deg C.",
  "action": "Looks up reagent stock levels \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Operational Inventory\u201d Real figures from the recording: 7 days, 57.54, 305.15.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D20": {
  "video": "../../data/uat/videos/D20/page@6c5a4b520f167bfafd4e819079d9e929.webm",
  "situation": "Calculate hydrated lime Ca(OH)2 dosage to neutralize pit sump pH from 3.2 to 7.5.",
  "action": "Looks up water balance logs \u2014 the operation's live data \u2014 and answers in its own words: \u201cHydrated Lime $\\text{Ca(OH)}_2$ Neutralization\u201d Real figures from the recording: 74.093, 3.2, 6.3096.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D21": {
  "video": "../../data/uat/videos/D21/page@c8593eb65ef461c6a4f98bc4cbfdd352.webm",
  "situation": "Predict beach slope angle for thickened tailings with yield stress 65 Pa.",
  "action": "Looks up tailings dam sensor readings \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Governing Method & Deposition\u201d Real figures from the recording: 45.10, 79.20, 119.60.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D22": {
  "video": "../../data/uat/videos/D22/page@42338f126c38f31a8de9ca7065e8abf7.webm",
  "situation": "From the assets register, report the Main Substation transformer record in full: type, criticality rating, installation date, current state and stored physics parameters \u2014 show them, and compute its age in years in plain arithmetic. Dissolved-gas readings are not in this estate: state that plainly and recommend the monitoring addition, using the criticality rating as the business justification.",
  "action": "Looks up the asset register \u2014 the operation's live data \u2014 and answers in its own words: \u201cAsset Record: Main Substation\u201d Real figures from the recording: 8.38, 65.0, 0.0403.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D23": {
  "video": "../../data/uat/videos/D23/page@a61ab03fb218d0f47afe89ca55af6d9e.webm",
  "situation": "Analyze stator winding partial discharge for 15 MW SAG mill synchronous motor.",
  "action": "Looks up the asset register \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Operational Asset Reconciliation & Technical\u201d Real figures from the recording: 4.0, 4.5, 4.25.",
  "logic": "Before answering it runs its High-Frequency Transient Phase-Resolved PD method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D24": {
  "video": "../../data/uat/videos/D24/page@f6711ae44cf24e85365e5ea0813341cc.webm",
  "situation": "Monitor ultrasonic sensor array on 4km overland coarse ore conveyor CV-01.",
  "action": "Looks up the asset register \u2014 the operation's live data \u2014 and answers in its own words: \u201cConveyor Belt Rip Ultra (Agent d24) \u2014 Asset & Sensor Monitoring\u201d Real figures from the recording: 116.8045, 23.1614, 5.24.",
  "logic": "Before answering it runs its Time-of-Flight Acoustic Wave Attenuation method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D25": {
  "video": "../../data/uat/videos/D25/page@d144b56260041be84b49918c2ffff276.webm",
  "situation": "From the assets register, report the primary crusher's record: type, criticality rating, installation date, current state and stored physics parameters \u2014 show them, and compute the asset's age in years in plain arithmetic. Liner thickness is not instrumented here: state that plainly, and recommend an inspection cadence justified by the age and criticality you just computed.",
  "action": "Looks up the asset register \u2014 the operation's live data \u2014 and answers in its own words: \u201cPrimary Crusher Asset\u201d Real figures from the recording: 116.8532, 23.1189, 4205.0.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D26": {
  "video": "../../data/uat/videos/D26/page@0e6f0137e680900e40fd6023711ffbf2.webm",
  "situation": "Calculate schedule float for SAG mill liner replacement critical path.",
  "action": "Looks up open work orders \u2014 the operation's live data \u2014 and answers in its own words: \u201cCritical Path Method (CPM) Schedule Float\u201d Real figures from the recording: 0.00.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D27": {
  "video": "../../data/uat/videos/D27/page@c525c326c2c75f33d6d1654db9cb044f.webm",
  "situation": "Audit 48 hours standby claim for contractor dozer fleet against FMS GPS movement.",
  "action": "Looks up supplier contracts and live fleet telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cContractor Idle Fee Audit\u201d Real figures from the recording: 48 hours, 162.18, 1,156.81.",
  "logic": "Before answering it runs its Standby Hours vs Daily Rate Dispute Validator method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D28": {
  "video": "../../data/uat/videos/D28/page@17de5aa53388596bcbb70d73d399e130.webm",
  "situation": "Calculate temperature-corrected diesel fuel volume for 120,000L bunkering at 34 deg C.",
  "action": "Looks up purchase-order history \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Data Reconcilement & Operational\u201d Real figures from the recording: 141.5, 131.5, 0.840.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D29": {
  "video": "../../data/uat/videos/D29/page@8b9ce19bf0bb522155fc21ab47f8eee3.webm",
  "situation": "From plant telemetry, report the mill's average power draw in megawatts \u2014 show the value and the reading count behind it. Using a stated media wear rate of 45 grams per kilowatt-hour, compute daily grinding ball consumption in tonnes per day in plain arithmetic, no formulas. Then check spares inventory for grinding media and state how many days the current stock covers.",
  "action": "Looks up spare parts stock and plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201cBased on operational records in plant_telemetry for asset MILL-01 (metric_name =\u201d Real figures from the recording: 4.086, 4.08603934, 0.16.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D30": {
  "video": "../../data/uat/videos/D30/page@6820cfea700bf9cee726173e630d1c49.webm",
  "situation": "Parse particle count data for SAG mill pinion lube oil reservoir.",
  "action": "Looks up the asset register and oil sample analyses \u2014 the operation's live data \u2014 and answers in its own words: \u201cAsset Name: SAG Grinding Mill 1 (Pinion / Drive Lubrication\u201d Real figures from the recording: 49.2, 14.9, 16.0.",
  "logic": "Before answering it runs its ISO 4406 Solid Contamination Cleanliness Code method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D32": {
  "video": "../../data/uat/videos/D32/page@fc9808e548fe33c5bee633aa66438356.webm",
  "situation": "Reconcile warehouse RFID scan against SAP goods issue for 12 pump seals.",
  "action": "Looks up spare parts stock \u2014 the operation's live data \u2014 and answers in its own words: \u201cReconciliation Summary: Warehouse RFID Scan vs. SAP Movement Type 201 Goods\u201d Real figures from the recording: 450.00, 900.00, 7 days.",
  "logic": "Before answering it runs its RFID Tag vs SAP Movement Type 201 Reconciler method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D33": {
  "video": "../../data/uat/videos/D33/page@ff59967d22a5db0eabfb22deb9006155.webm",
  "situation": "Parse port laytime statement for 'MV Bulk Pioneer' under rain interruptions.",
  "action": "Looks up vessel movements at the port \u2014 the operation's live data \u2014 and answers in its own words: \u201cLaytime & Statement of Fact (SOF) Parsing\u201d Real figures from the recording: 75,542.0, 9.73%, 10.0%.",
  "logic": "Before answering it runs its BIMCO Laytime Standard Statement of Fact Parser method, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D34": {
  "video": "../../data/uat/videos/D34/page@addc4908d57ffeb033140b879ebe3c7c.webm",
  "situation": "List every xanthate-class collector in reagent inventory with stock level, reorder point, lead time and unit price \u2014 show the numbers. Then, using this stated rule of thumb \u2014 6 months usable life at 20 C, halved for every 10 C above 20 C \u2014 work out usable life at 38 C storage in plain arithmetic (no formulas), and the dollar value of stock at risk if we cannot consume it in that window.",
  "action": "Looks up reagent stock levels \u2014 the operation's live data \u2014 and answers in its own words: \u201cXanthate-Class Collector\u201d Real figures from the recording: 7 days, 57.54, 51,037.98.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D35": {
  "video": "../../data/uat/videos/D35/page@c6434a46b46457e8990cfd2308292013.webm",
  "situation": "Calculate stopping distance for 12,000t loaded ore train at 60 km/h on 0.5% grade.",
  "action": "Looks up rail schedules \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational Reconciliation & Data\u201d Real figures from the recording: 061.8, 920.4, 911.7.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D36": {
  "video": "../../data/uat/videos/D36/page@827b2c2853d79934121e44dfb72594f2.webm",
  "situation": "For every vessel currently in port, compare cargo moisture percentage against its Transportable Moisture Limit and report the safety margin in percentage points \u2014 show the values per vessel and flag any within 1 point of the limit. State plainly that boom-clearance monitoring is not in this dataset, and confirm which loading-safety checks this data does support.",
  "action": "Looks up vessel movements at the port \u2014 the operation's live data \u2014 and answers in its own words: \u201cOperational Context & Sentinel\u201d Real figures from the recording: 5.0, 1.00, 9.00%.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D37": {
  "video": "../../data/uat/videos/D37/page@6936de6c8068a73e4cd8fba794576449.webm",
  "situation": "Calculate SAFTE bio-mathematical fatigue score for operator on 4th night shift.",
  "action": "Looks up fatigue monitoring logs records \u2014 the operation's live data \u2014 and answers in its own words: \u201cBiomathematical SAFTE Fatigue Evaluation (Operator on 4th Night\u201d Real figures from the recording: 2.13 hours, 2.06, 1.04.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D38": {
  "video": "../../data/uat/videos/D38/page@6855588a2dd6db0da1f892461cb90b88.webm",
  "situation": "From safety telemetry, report all recorded incidents around the mill and plant: count by severity level, the locations involved, and how many investigations are still open \u2014 show the numbers. Gas readings are not logged in this estate: state that plainly, then argue from the incident history whether the confined-space liner inspection should proceed and what monitoring must be in place first.",
  "action": "Looks up safety telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Telemetry and Gas Monitoring\u201d Real figures from the recording: 63.3%, 19.5%, 23.5%.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D39": {
  "video": "../../data/uat/videos/D39/page@1a441ac668c2203cd9ce5bac8eb3de64.webm",
  "situation": "From fleet and plant telemetry, total the energy-related metrics the data actually holds, month by month \u2014 show the monthly values. Using a stated grid factor of 0.7 kg CO2 per kilowatt-hour, compute the carbon measure the data supports in plain arithmetic, quoted as a range, and name exactly which missing inputs \u2014 fuel litres, cathode tonnes \u2014 would complete a per-tonne intensity figure.",
  "action": "Looks up live fleet telemetry and plant telemetry \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Reconciling Telemetry Data & Governing\u201d Real figures from the recording: 0.7, 0.700, 2 hours.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "D40": {
  "video": "../../data/uat/videos/D40/page@c0cab5bf484f0d244ffe3b98e0bed0d8.webm",
  "situation": "Audit statutory environmental water discharge permit expiry timelines.",
  "action": "Looks up tenement leases records and safety permits records \u2014 the operation's live data \u2014 and answers in its own words: \u201cExecutive Summary & Regulatory Audit\u201d Real figures from the recording: 10,885.50, 417,265.21, 2,482.00.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 },
 "S03-3-VIBRATION": {
  "video": "../../data/uat/videos/S03-3-VIBRATION/page@daecb9d01af18f2a367e5035cdd678e1.webm",
  "situation": "From blast design records, compute the scaled distance from our typical charge to the crusher at 450 metres \u2014 plain arithmetic from the recorded hole geometry and powder factor, values shown. Site attenuation constants are uncalibrated: say so plainly, bound the expected vibration as a range using the standard published constants as a named assumption, and recommend the calibration blast that would make it exact.",
  "action": "Looks up blast designs \u2014 the operation's live data \u2014 and answers in its own words: \u201c1. Reconciliation of Assumptions Against Operations &\u201d Real figures from the recording: 4.9, 5.77, 7.07.",
  "logic": "Before answering it runs its governing calculation, checks any numbers given in the question against what the records actually say, points out any difference, and names the records behind every figure. If it cannot back something with data, it says so."
 }
};
