/* SC-4 — the approval sheet. Raised from SC-2 and SC-3; never a destination.
 *
 * Fourteen of the fifty-two entrypoints carry hitl_required, which binds them
 * to request_approval, which writes one row to mining_data.agent_approvals with
 * decision = PENDING and can write nothing else. This sheet is the other half
 * of that write: the only path in the codebase by which PENDING becomes
 * anything else.
 *
 * Three decisions here are not stylistic, and each traces to a finding:
 *
 *   The UNVERIFIED band is drawn first and never collapses. docs/phase-2-ux.md
 *   calls it the most important element on the sheet — a supervisor who
 *   approves a recommendation without seeing what it could not settle has been
 *   given a false picture, and putting it below the fold or behind a toggle is
 *   how that happens.
 *
 *   The hold is two seconds of held contact, not a click and not a typed word.
 *   A click is one gloved-thumb slip away from committing; a typed
 *   confirmation phrase is unusable on the rugged tablets P3 and P6 work from.
 *   Two seconds of sustained intent is the shortest gesture that cannot be
 *   made by accident and can be made with one hand in a glove.
 *
 *   Completing the hold does not claim to have written anything. There is no
 *   runtime and no request, so the sheet reports the row it would have written
 *   and states plainly that it wrote nothing. An artifact that prints "approved
 *   and recorded" against a warehouse it never reached teaches its reader to
 *   distrust every other number on the screen.
 */

const HOLD_MS = 2000;

/* The catalog records which agents may raise an approval; it does not record
   what any of them would ask for, because action_type and the payload are
   composed by the agent at call time. Nothing here fills them in. */
const NOT_SUPPLIED =
  "supplied by the agent on the call — no call was made";

let openSheet = null;

function approvalRow(id) {
  const a = AGENTS[id];
  const flags = flagsFor([id]);

  /* Each field says where its value comes from, and the three the sheet itself
     owns — decision, approver_principal, decided_at — are marked as the
     human's, because that is the whole point of the table. */
  const values = {
    approval_id: ["generated by request_approval as APR-{uuid4}", "tool"],
    agent_id: [id, "catalog"],
    action_type: [NOT_SUPPLIED, "agent"],
    target_entity: ["JSON payload, " + NOT_SUPPLIED, "agent"],
    decision: [
      WS.approval.pending_decision + " until this sheet overwrites it",
      "you",
    ],
    approver_principal: [
      WS.approval.pending_principal + " until this sheet overwrites it",
      "you",
    ],
    decided_at: ["the moment the hold completes", "you"],
    hold_duration_ms: ["measured, not declared — see below", "you"],
    agent_reasoning_snapshot: [
      "the agent's own words, mandatory on the call — none exist",
      "agent",
    ],
    unverified_flags: [
      flags.map((f) => f.what).join(" | "),
      "derived on this screen",
    ],
    source_tables: [a.source_tables.join(", "), "catalog"],
  };

  return (
    '<table class="audit"><thead><tr>' +
    "<th>Column</th><th>Type</th><th>Value</th><th>Written by</th>" +
    "</tr></thead><tbody>" +
    WS.approval.fields
      .map((f) => {
        const [value, who] = values[f.column];
        return (
          `<tr><td class="v">${esc(f.column)}</td>` +
          `<td class="v t dim">${esc(f.type)}${f.mode === "REPEATED" ? "[]" : ""}</td>` +
          `<td>${esc(value)}</td>` +
          `<td class="v dim">${esc(who)}</td></tr>`
        );
      })
      .join("") +
    "</tbody></table>"
  );
}

/** Raise the approval sheet for one entrypoint. */
function openApproval(id) {
  if (openSheet) return;
  const a = AGENTS[id];
  const persona = PERSONAS[a.persona] || {};
  const returnFocus = document.activeElement;

  const back = document.createElement("div");
  back.className = "sheet-back";
  back.innerHTML =
    '<div class="sheet" role="dialog" aria-modal="true" aria-labelledby="sheet-title">' +
    '<div class="sheet-head">' +
    '<span class="badge b-warn">⚠ APPROVAL REQUIRED</span>' +
    `<h2 id="sheet-title">${esc(a.display_name)}</h2>` +
    `<span class="dim mono" style="font-size:11px">${esc(id)}</span>` +
    "</div>" +
    '<div class="sheet-body">' +
    unverified([id]) +
    '<div><div class="card-cap">Why this agent is asking</div>' +
    notConnected(
      "The reasoning a person approves is the agent's own, passed to " +
        "request_approval as a mandatory argument and stored verbatim in " +
        "agent_reasoning_snapshot. Nothing is written in its place here."
    ) +
    "</div>" +
    '<div><div class="card-cap">The row this decision writes</div>' +
    `<p class="dim" style="font-size:12.5px;margin:0 0 10px">One row in ` +
    `<span class="mono">${esc(WS.approval.table)}</span>. ${esc(WS.approval.rule)}</p>` +
    approvalRow(id) +
    "</div>" +
    '<div><div class="card-cap">Who is accountable</div>' +
    `<p style="margin:0;font-size:13.5px">${esc(persona.title || a.persona)}` +
    (persona.accountable_for
      ? ` — ${esc(persona.accountable_for.trim())}`
      : "") +
    "</p></div>" +
    '<div id="sheet-result"></div>' +
    "</div>" +
    '<div class="sheet-actions">' +
    '<button class="btn cancel" id="sheet-cancel">Cancel</button>' +
    '<button class="btn danger hold" id="sheet-hold">' +
    '<span class="hold-fill"></span>' +
    '<span class="lbl">⏻ Hold 2s to approve</span></button>' +
    '<span class="hold-hint">Press and hold, or focus the button and hold Space. ' +
    "Release early and nothing happens.</span>" +
    "</div></div>";

  document.body.appendChild(back);
  document.body.style.overflow = "hidden";
  openSheet = back;

  const hold = back.querySelector("#sheet-hold");
  const fill = back.querySelector(".hold-fill");
  const label = hold.querySelector(".lbl");
  const result = back.querySelector("#sheet-result");

  function close() {
    document.removeEventListener("keydown", onKeyDown);
    document.removeEventListener("keyup", onKeyUp);
    back.remove();
    document.body.style.overflow = "";
    openSheet = null;
    if (returnFocus && returnFocus.focus) returnFocus.focus();
  }

  /* The stroke is stepped on a timer and interpolated by the 60ms CSS
     transition on .hold-fill, rather than being drawn frame by frame.
     requestAnimationFrame would be the usual choice, but it does not fire while
     the document is hidden, which would leave a half-drawn stroke frozen at
     whatever width it had when the tab lost visibility. A timer keeps the
     control's state and its appearance in agreement.

     The elapsed time is read from the clock at each step and not accumulated
     from the interval, so the figure this reports afterwards is the time that
     was actually held. */
  const STEP_MS = 60;
  let start = 0;
  let timer = 0;

  function tick() {
    const held = performance.now() - start;
    fill.style.width = Math.min(100, (held / HOLD_MS) * 100) + "%";
    if (held >= HOLD_MS) complete(Math.round(held));
  }

  function begin() {
    if (start || hold.disabled) return;
    start = performance.now();
    label.textContent = "⏻ Holding — keep holding";
    timer = setInterval(tick, STEP_MS);
    tick();
  }

  function cancelHold() {
    if (!start) return;
    clearInterval(timer);
    start = 0;
    fill.style.width = "0%";
    label.textContent = "⏻ Hold 2s to approve";
  }

  function complete(ms) {
    clearInterval(timer);
    start = 0;
    hold.disabled = true;
    fill.style.width = "100%";
    label.textContent = "⏻ Held " + ms + " ms";

    /* What a person just did is real and is reported as such: they held the
       control for a measured interval. What did not happen is the write, and
       the sheet says which is which rather than blurring them into a success
       message. */
    result.innerHTML =
      '<div class="card-cap">What this hold did</div>' +
      `<p style="margin:0 0 12px;font-size:13.5px">The hold completed after ` +
      `<span class="mono">${ms}</span> ms, which is the value that would go to ` +
      '<span class="mono">hold_duration_ms</span>. Nothing was written.</p>' +
      notConnected(
        "Committing this decision means updating one row in " +
          WS.approval.table +
          " — setting decision, approver_principal and decided_at. That row " +
          "does not exist, because no agent raised a request."
      );
    result.scrollIntoView({ block: "nearest" });
  }

  /* Space is the keyboard equivalent of held contact. Browsers repeat keydown
     while a key is held, so the repeat flag is ignored rather than treated as a
     fresh press — otherwise the first repeat would restart the timer and the
     hold could never finish. */
  function onKeyDown(event) {
    if (event.key === "Escape") {
      close();
      return;
    }
    if (event.key === " " && document.activeElement === hold) {
      event.preventDefault();
      if (!event.repeat) begin();
    }
  }

  function onKeyUp(event) {
    if (event.key === " ") cancelHold();
  }

  hold.addEventListener("pointerdown", (event) => {
    event.preventDefault();
    hold.focus();
    begin();
  });
  hold.addEventListener("pointerup", cancelHold);
  hold.addEventListener("pointerleave", cancelHold);
  hold.addEventListener("pointercancel", cancelHold);
  /* A click that never involved a hold must do nothing at all, including not
     submitting anything a parent form might otherwise catch. */
  hold.addEventListener("click", (event) => event.preventDefault());

  back.querySelector("#sheet-cancel").addEventListener("click", close);
  back.addEventListener("mousedown", (event) => {
    if (event.target === back) close();
  });
  document.addEventListener("keydown", onKeyDown);
  document.addEventListener("keyup", onKeyUp);

  back.querySelector("#sheet-cancel").focus();
}
