"""Generate apps/frontend/data.js from the vault's agent catalogue.

WHY GENERATED, NOT PASTED
The five-screen front end was handed over as two HTML files whose agent data
had been injected at runtime by the deployed frontend service. Snapshotting
that injected blob would freeze a copy that drifts from the registry the moment
anyone edits an agent. `catalog_definitions.CATALOG` is the registry's own
source of truth -- 101 AgentCards -- so the screens are built from it directly.

The persona and node datasets have no such upstream: they are presentation
content that ships with the design. They live in data_static.js and are edited
by hand, which is stated here so nobody looks for a generator that isn't there.
"""
from __future__ import annotations

import json
import pathlib
import sys

VAULT = pathlib.Path(
    "/private/tmp/claude-501/-Users-amritharajendran-VivekWork/"
    "efc5e61e-5d05-4776-8d44-d90eaaca280e/scratchpad/vault/source"
)
sys.path.insert(0, str(VAULT / "services" / "agent_registry_service"))

import catalog_definitions as C  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "apps" / "frontend" / "data.js"

#: The four architectural tiers the screens group by, keyed off the catalogue's
#: own `pattern` enum so a new pattern surfaces as a KeyError here rather than
#: silently vanishing from the topology view.
TIER_OF = {
    "L0_STRATEGIC": "L0",
    "A_COORDINATOR": "L2",
    "A_SPECIALIST": "L2",
    "A_CRITIC": "L2",
    "B_DEEP": "L3",
}


def card(a) -> dict:
    return {
        "id": a.agent_id,
        "name": a.name,
        "tierKey": TIER_OF[a.pattern.value],
        "pattern": a.pattern.value,
        "apqc": f"APQC {a.apqc_code}",
        "department": a.department.value,
        "persona": a.persona,
        "process": a.persona,
        "authority": a.authority_level.value.replace("_", " "),
        "valueClass": a.value_class.value,
        "hitl": a.hitl_required,
        "endpoint": a.endpoint_type.value,
        "parent": a.parent_coordinator_id,
        "governingEquation": a.governing_equation,
        "mechanism": a.description,
        "provenance": [
            {"name": t, "type": "SAP" if "erp" in t.lower() else "BQ"}
            for t in a.source_tables
        ],
        "tools": list(a.tools),
        "model": a.model_id,
    }


def main() -> None:
    cat = sorted(C.CATALOG, key=lambda a: (TIER_OF[a.pattern.value], a.agent_id))
    agents = {a.agent_id: card(a) for a in cat}

    counts: dict[str, int] = {}
    for a in agents.values():
        counts[a["tierKey"]] = counts.get(a["tierKey"], 0) + 1

    body = (
        "/* GENERATED by scripts/build_frontend_data.py -- do not edit by hand.\n"
        " * Source: the agent registry's own catalogue (101 AgentCards).\n"
        " * Regenerate after any catalogue change; a stale copy here is the\n"
        " * failure this generator exists to prevent. */\n"
        f"window.agentCatalogData = {json.dumps(agents, indent=1)};\n\n"
        f"window.agentTierCounts = {json.dumps(counts, indent=1)};\n"
    )
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(ROOT)}  {len(agents)} agents  tiers={counts}")


if __name__ == "__main__":
    main()
