"""Deploy the 52 entrypoints and register them. The domain binding stops.

Ruling 1: The real ADK 2.6.3 CLI deploy verb is:
  python -m google.adk.cli deploy agent_engine \\
    --project=<PROJECT> --region=<REGION> --display_name=<NAME> <AGENT_DIRECTORY>
  There is no --service-account flag; the runtime SA must be annotated separately.
  There is no 'gcloud ai agents' group in this GCP project.

Ruling 2: deploy(dry_run=False) raises NotImplementedError — the 52 per-agent
packages have not been built, and the runtime SA attachment mechanism is
unresolved. Do not call with dry_run=False in any automated pipeline.

Ruling 3: DOMAIN_BINDING_COMMAND is NEVER executed by this module. It is
printed with a warning and the caller is required to run it manually if approved.
"""
from __future__ import annotations

import json

from agents.build import build_all
from agents.config import settings
from agents.registry import registrations

# ---------------------------------------------------------------------------
# The single copy of this command lives in docs/phase-3-design.md §5.5.
# This module NEVER executes it — see Ruling 3.
# ---------------------------------------------------------------------------
DOMAIN_BINDING_COMMAND = (
    "gcloud projects add-iam-policy-binding ${GOOGLE_CLOUD_PROJECT} \\\n"
    '  --member="domain:${GOOGLE_DOMAIN}" \\\n'
    '  --role="roles/aiplatform.user"'
)


def print_domain_binding_warning() -> None:
    """Print the resolved domain-binding command and an explicit warning.

    Ruling 3: this function exists to make the command auditable. It is
    NEVER called from a code path that executes it.
    """
    s = settings()
    resolved = DOMAIN_BINDING_COMMAND.replace(
        "${GOOGLE_CLOUD_PROJECT}", s.project_id
    )
    print("=" * 72)
    print("DOMAIN-WIDE IAM BINDING — REQUIRES EXPLICIT HUMAN APPROVAL")
    print(resolved)
    print()
    print("This grants access to EVERY user in the domain in one action.")
    print("Acceptable only because this is an Argolis sandbox.")
    print("DO NOT copy this binding into a production project.")
    print("This script will NOT run it. Run it yourself if you approve.")
    print("=" * 72)


def deploy(dry_run: bool = True) -> None:
    """Build and (dry-run) deploy the 52 externally-callable agents.

    dry_run=True (default): prints the real deploy command shape per agent,
    the full registration payload (auditor-readable), and the domain-binding
    warning block. No subprocess is spawned; no cloud state is touched.

    dry_run=False: raises NotImplementedError. The 52 per-agent packages are
    not generated by this build, and the runtime service-account attachment
    mechanism is unresolved per Ruling 1. Execute deploy only after:
      1. A per-agent directory (each exposing `root_agent`) has been built.
      2. The --service-account attachment mechanism is confirmed against the
         installed ADK CLI version.

    Ruling 3: DOMAIN_BINDING_COMMAND is printed and never executed.
    """
    if not dry_run:
        raise NotImplementedError(
            "deploy(dry_run=False) is not implemented. Two prerequisites are missing:\n"
            "  1. The 52 per-agent package directories (each exposing `root_agent`) "
            "have not been generated. The ADK CLI deploy verb requires a local agent "
            "directory, not an agent_id.\n"
            "  2. The runtime service-account attachment mechanism is unresolved: "
            "the `python -m google.adk.cli deploy agent_engine` verb has no "
            "--service-account flag. The SA must be attached via a separate "
            "IAM step that has not been scripted.\n"
            "Build the 52 packages and resolve the SA attachment before calling "
            "deploy(dry_run=False)."
        )

    s = settings()
    agents = build_all()
    print(f"built {len(agents)} entrypoints")
    print()

    for entry in registrations():
        agent_id = entry["agent_id"]
        sa = entry["service_account"]

        # Ruling 1: real ADK 2.6.3 CLI shape — positional arg is an agent directory.
        # There is no --service-account flag; print it as an explicit annotation.
        print(f"# --- {agent_id} ---")
        print(
            f"python -m google.adk.cli deploy agent_engine \\\n"
            f"  --project={s.project_id} \\\n"
            f"  --region={s.location} \\\n"
            f"  --display_name={entry['display_name']!r} \\\n"
            f"  ./packages/{agent_id}/"
        )
        print(f"# Runtime service account (attach separately): {sa}")
        print()

        # Print full payload — no truncation — so an auditor can read
        # caller_allowlist and guardrails (Ruling 6).
        print("Registration payload:")
        print(json.dumps(entry, indent=2))
        print()

    print_domain_binding_warning()


if __name__ == "__main__":
    deploy(dry_run=True)
