"""Generate the 52 per-agent packages that the ADK deploy verb requires.

`adk deploy agent_engine` takes a DIRECTORY, not an agent id — it stages the
directory, imports `root_agent` from it, and containerises the result. So each
externally-callable entrypoint needs a package of its own.

Each generated module is a two-line shim over `mining_agents.build.build_one`.
It deliberately contains no model name, no tool wiring, and no table reference:
the moment any of that is copied here, the generated tree becomes a second
source of truth and starts drifting from the catalog silently. The shared
`mining_agents` package travels to the container as an extra package, so the
shim imports the same code the tests exercise, not a copy of it.

The package is named `mining_agents`, not `agents`, because ADK stages every
deployment's source into `/app/agents/<name>`. An extra package called `agents`
therefore collides with the staging root and the deploy is rejected outright
("extra_packages entry has a conflicting name: agents"). No flag avoids this.

Regenerate with: python -m scripts.packages
"""
from __future__ import annotations

from pathlib import Path

from mining_agents.registry import registrable

AGENT_MODULE_NAME = "agent.py"
REQUIREMENTS_NAME = "requirements.txt"

# Packages the container does not need because nothing in `mining_agents/` imports
# them at runtime. Everything else in the repo's requirements.txt travels, so
# adding a runtime dependency there is enough — this module needs no edit.
_TEST_ONLY = ("pytest",)

_REPO_ROOT = Path(__file__).resolve().parent.parent

_AGENT_MODULE = '''"""Generated by scripts/packages.py — do not edit by hand.

Serves exactly one entrypoint: {entry_id}.
Regenerate with: python -m scripts.packages
"""
from mining_agents.build import build_one

root_agent = build_one("{entry_id}")
'''

_INIT_MODULE = '''"""Generated by scripts/packages.py — do not edit by hand."""
from . import agent

__all__ = ["agent"]
'''


def runtime_requirements() -> str:
    """The repo's requirements with the test-only ones removed.

    Derived rather than hand-listed so that a runtime dependency added to
    requirements.txt reaches the containers without anyone remembering to
    also edit this file.
    """
    lines = (_REPO_ROOT / REQUIREMENTS_NAME).read_text().splitlines()
    kept = [
        line for line in lines
        if line.strip()
        and not line.lstrip().startswith("#")
        and not line.split("=")[0].split(">")[0].split("<")[0].strip() in _TEST_ONLY
    ]
    return "\n".join(kept) + "\n"


def write_packages(root: Path) -> list[Path]:
    """Write one package per registrable agent under *root*; return their paths.

    Rewrites unconditionally rather than skipping existing files, so a stale
    shim left by an earlier catalog can never survive a regeneration.
    """
    root = Path(root)
    requirements = runtime_requirements()
    written: list[Path] = []
    for agent in registrable():
        pkg = root / agent.agent_id
        pkg.mkdir(parents=True, exist_ok=True)
        (pkg / "__init__.py").write_text(_INIT_MODULE)
        (pkg / AGENT_MODULE_NAME).write_text(
            _AGENT_MODULE.format(entry_id=agent.agent_id)
        )
        (pkg / REQUIREMENTS_NAME).write_text(requirements)
        written.append(pkg)
    return written


if __name__ == "__main__":
    paths = write_packages(Path("packages"))
    print(f"wrote {len(paths)} packages under packages/")
