"""Generate the 52 per-agent packages that the ADK deploy verb requires.

`adk deploy cloud_run` takes a DIRECTORY, not an agent id — it copies that
directory to `/app/agents/<app_name>/` in the container, imports `root_agent`
from it, and serves it. So each externally-callable entrypoint needs a package
of its own.

Each generated module is a two-line shim over `mining_agents.build.build_one`.
It deliberately contains no model name, no tool wiring, and no table reference:
the moment any of that is copied here, the generated tree becomes a second
source of truth and starts drifting from the catalog silently.

WHY EACH PACKAGE CARRIES ITS OWN COPY OF THE SHARED TREE
--------------------------------------------------------
The Cloud Run deploy verb has no `--extra_packages`. That is not an oversight
to work around: `cli_deploy.to_cloud_run` passes `extra_packages_copy=''` into
the Dockerfile template unconditionally, so the ONLY thing that reaches the
container is the agent directory itself. Anything the agent needs at runtime
must therefore live inside that directory.

So `write_packages` copies SHARED_TREES into every package. `references` is one
of them because it is read at RUNTIME, not just by tooling: `model_for_tier`
parses references/model-policy.md on every agent build. Omit it and the deploy
still succeeds, the container still builds, and the agent then dies on its
first query with FileNotFoundError — a failure that costs a full container
build to discover.

The copy also keeps `config._repo_root()` honest. That function is `parents[1]`
of the config module, so with the tree at `<pkg>/mining_agents/config.py` it
resolves to `<pkg>` — which is exactly where `references/` now sits, in the
container and in the checkout alike. Nothing in config had to learn about
deployment.

`packages/` is gitignored, so the duplication is untracked scratch that
`python -m scripts.packages` regenerates. Copies rather than symlinks: what
ships is then byte-identical to what the tests import, with no dependency on
how `shutil.copytree` treats links.

Regenerate with: python -m scripts.packages
"""
from __future__ import annotations

import shutil
from pathlib import Path

from mining_agents.registry import registrable

AGENT_MODULE_NAME = "agent.py"
REQUIREMENTS_NAME = "requirements.txt"

# Repo directories copied into every generated package because the container
# reads them at runtime. See the module docstring for why a copy is required.
SHARED_TREES = ("mining_agents", "references")

# Build artefacts must not travel: a stale .pyc compiled against a different
# interpreter is a failure that only appears inside the container.
_COPY_IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store")

# Packages the container does not need because nothing in `mining_agents/` imports
# them at runtime. Everything else in the repo's requirements.txt travels, so
# adding a runtime dependency there is enough — this module needs no edit.
_TEST_ONLY = ("pytest",)

_REPO_ROOT = Path(__file__).resolve().parent.parent

_AGENT_MODULE = '''"""Generated by scripts/packages.py — do not edit by hand.

Serves exactly one entrypoint: {entry_id}.
Regenerate with: python -m scripts.packages
"""
from mining_agents.build import build_one

root_agent = build_one("{entry_id}")
'''

# The sys.path line is load-bearing in the container and a no-op in the
# checkout, which is why it is easy to delete and expensive to have deleted.
_INIT_MODULE = '''"""Generated by scripts/packages.py — do not edit by hand."""
import os
import sys

# ADK's agent loader puts only the agents ROOT on sys.path — /app/agents — and
# never the individual agent directory (google/adk/cli/utils/agent_loader.py
# inserts `agents_dir` alone). `mining_agents` ships INSIDE this package, so
# without this line the absolute imports used throughout that tree cannot
# resolve and the container dies on import with ModuleNotFoundError.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from . import agent  # noqa: E402  — must follow the sys.path bootstrap above

__all__ = ["agent"]
'''


def runtime_requirements() -> str:
    """The repo's requirements with the test-only ones removed.

    Derived rather than hand-listed so that a runtime dependency added to
    requirements.txt reaches the containers without anyone remembering to
    also edit this file.
    """
    lines = (_REPO_ROOT / REQUIREMENTS_NAME).read_text().splitlines()
    kept = [
        line for line in lines
        if line.strip()
        and not line.lstrip().startswith("#")
        and not line.split("=")[0].split(">")[0].split("<")[0].strip() in _TEST_ONLY
    ]
    return "\n".join(kept) + "\n"


def write_packages(root: Path) -> list[Path]:
    """Write one self-contained package per registrable agent under *root*.

    Rewrites unconditionally rather than skipping existing files, so a stale
    shim or a shared tree left by an earlier catalog can never survive a
    regeneration — the copied trees are removed before being rewritten, which
    a plain overwrite would not achieve for a deleted module.
    """
    root = Path(root)
    requirements = runtime_requirements()
    written: list[Path] = []
    for agent in registrable():
        pkg = root / agent.agent_id
        pkg.mkdir(parents=True, exist_ok=True)
        (pkg / "__init__.py").write_text(_INIT_MODULE)
        (pkg / AGENT_MODULE_NAME).write_text(
            _AGENT_MODULE.format(entry_id=agent.agent_id)
        )
        (pkg / REQUIREMENTS_NAME).write_text(requirements)
        for tree in SHARED_TREES:
            destination = pkg / tree
            if destination.exists():
                shutil.rmtree(destination)
            shutil.copytree(_REPO_ROOT / tree, destination, ignore=_COPY_IGNORE)
        written.append(pkg)
    return written


if __name__ == "__main__":
    paths = write_packages(Path("packages"))
    print(f"wrote {len(paths)} self-contained packages under packages/")
